// <auto-generated/>

namespace TII_NewDatabase.AddNewForms
{
    partial class FormAddNewContact
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.txt_Fax = new System.Windows.Forms.TextBox();
            this.txt_CellPhone = new System.Windows.Forms.TextBox();
            this.txt_OfficePhone = new System.Windows.Forms.TextBox();
            this.txt_Email = new System.Windows.Forms.TextBox();
            this.lbl_ContactEmail = new System.Windows.Forms.Label();
            this.lbl_ContactFax = new System.Windows.Forms.Label();
            this.lbl_ContactCellPhone = new System.Windows.Forms.Label();
            this.lbl_ContactOfficePhone = new System.Windows.Forms.Label();
            this.lbl_ContactName = new System.Windows.Forms.Label();
            this.txt_Name = new System.Windows.Forms.TextBox();
            this.lbl_Extension = new System.Windows.Forms.Label();
            this.txt_Extension = new System.Windows.Forms.TextBox();
            this.groupBox1 = new System.Windows.Forms.GroupBox();
            this.btn_SaveEntry = new System.Windows.Forms.Button();
            this.btn_Cancel = new System.Windows.Forms.Button();
            this.groupBox1.SuspendLayout();
            this.SuspendLayout();
            // 
            // txt_Fax
            // 
            this.txt_Fax.Location = new System.Drawing.Point(90, 91);
            this.txt_Fax.Name = "txt_Fax";
            this.txt_Fax.Size = new System.Drawing.Size(100, 20);
            this.txt_Fax.TabIndex = 34;
            // 
            // txt_CellPhone
            // 
            this.txt_CellPhone.Location = new System.Drawing.Point(90, 65);
            this.txt_CellPhone.Name = "txt_CellPhone";
            this.txt_CellPhone.Size = new System.Drawing.Size(100, 20);
            this.txt_CellPhone.TabIndex = 33;
            // 
            // txt_OfficePhone
            // 
            this.txt_OfficePhone.Location = new System.Drawing.Point(90, 39);
            this.txt_OfficePhone.Name = "txt_OfficePhone";
            this.txt_OfficePhone.Size = new System.Drawing.Size(100, 20);
            this.txt_OfficePhone.TabIndex = 32;
            // 
            // txt_Email
            // 
            this.txt_Email.Location = new System.Drawing.Point(90, 117);
            this.txt_Email.Name = "txt_Email";
            this.txt_Email.Size = new System.Drawing.Size(160, 20);
            this.txt_Email.TabIndex = 31;
            // 
            // lbl_ContactEmail
            // 
            this.lbl_ContactEmail.AutoSize = true;
            this.lbl_ContactEmail.Location = new System.Drawing.Point(45, 120);
            this.lbl_ContactEmail.Name = "lbl_ContactEmail";
            this.lbl_ContactEmail.Size = new System.Drawing.Size(39, 13);
            this.lbl_ContactEmail.TabIndex = 30;
            this.lbl_ContactEmail.Text = "E-Mail:";
            // 
            // lbl_ContactFax
            // 
            this.lbl_ContactFax.AutoSize = true;
            this.lbl_ContactFax.Location = new System.Drawing.Point(57, 94);
            this.lbl_ContactFax.Name = "lbl_ContactFax";
            this.lbl_ContactFax.Size = new System.Drawing.Size(27, 13);
            this.lbl_ContactFax.TabIndex = 29;
            this.lbl_ContactFax.Text = "Fax:";
            // 
            // lbl_ContactCellPhone
            // 
            this.lbl_ContactCellPhone.AutoSize = true;
            this.lbl_ContactCellPhone.Location = new System.Drawing.Point(23, 68);
            this.lbl_ContactCellPhone.Name = "lbl_ContactCellPhone";
            this.lbl_ContactCellPhone.Size = new System.Drawing.Size(61, 13);
            this.lbl_ContactCellPhone.TabIndex = 28;
            this.lbl_ContactCellPhone.Text = "Cell Phone:";
            // 
            // lbl_ContactOfficePhone
            // 
            this.lbl_ContactOfficePhone.AutoSize = true;
            this.lbl_ContactOfficePhone.Location = new System.Drawing.Point(12, 42);
            this.lbl_ContactOfficePhone.Name = "lbl_ContactOfficePhone";
            this.lbl_ContactOfficePhone.Size = new System.Drawing.Size(72, 13);
            this.lbl_ContactOfficePhone.TabIndex = 27;
            this.lbl_ContactOfficePhone.Text = "Office Phone:";
            // 
            // lbl_ContactName
            // 
            this.lbl_ContactName.AutoSize = true;
            this.lbl_ContactName.Location = new System.Drawing.Point(45, 16);
            this.lbl_ContactName.Name = "lbl_ContactName";
            this.lbl_ContactName.Size = new System.Drawing.Size(38, 13);
            this.lbl_ContactName.TabIndex = 25;
            this.lbl_ContactName.Text = "Name:";
            // 
            // txt_Name
            // 
            this.txt_Name.Location = new System.Drawing.Point(90, 13);
            this.txt_Name.Name = "txt_Name";
            this.txt_Name.Size = new System.Drawing.Size(160, 20);
            this.txt_Name.TabIndex = 26;
            // 
            // lbl_Extension
            // 
            this.lbl_Extension.AutoSize = true;
            this.lbl_Extension.Location = new System.Drawing.Point(187, 42);
            this.lbl_Extension.Name = "lbl_Extension";
            this.lbl_Extension.Size = new System.Drawing.Size(12, 13);
            this.lbl_Extension.TabIndex = 35;
            this.lbl_Extension.Text = "x";
            // 
            // txt_Extension
            // 
            this.txt_Extension.Location = new System.Drawing.Point(196, 39);
            this.txt_Extension.Name = "txt_Extension";
            this.txt_Extension.Size = new System.Drawing.Size(54, 20);
            this.txt_Extension.TabIndex = 36;
            // 
            // groupBox1
            // 
            this.groupBox1.Controls.Add(this.btn_SaveEntry);
            this.groupBox1.Controls.Add(this.btn_Cancel);
            this.groupBox1.Location = new System.Drawing.Point(12, 143);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new System.Drawing.Size(260, 81);
            this.groupBox1.TabIndex = 37;
            this.groupBox1.TabStop = false;
            // 
            // btn_SaveEntry
            // 
            this.btn_SaveEntry.Location = new System.Drawing.Point(6, 19);
            this.btn_SaveEntry.Name = "btn_SaveEntry";
            this.btn_SaveEntry.Size = new System.Drawing.Size(248, 23);
            this.btn_SaveEntry.TabIndex = 0;
            this.btn_SaveEntry.Text = "Save As New Entry";
            this.btn_SaveEntry.UseVisualStyleBackColor = true;
            this.btn_SaveEntry.Click += new System.EventHandler(this.SaveEntry_Click);
            // 
            // btn_Cancel
            // 
            this.btn_Cancel.DialogResult = System.Windows.Forms.DialogResult.Cancel;
            this.btn_Cancel.Location = new System.Drawing.Point(6, 48);
            this.btn_Cancel.Name = "btn_Cancel";
            this.btn_Cancel.Size = new System.Drawing.Size(248, 23);
            this.btn_Cancel.TabIndex = 1;
            this.btn_Cancel.Text = "Cancel";
            this.btn_Cancel.UseVisualStyleBackColor = true;
            // 
            // FormAddNewContact
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(284, 235);
            this.Controls.Add(this.groupBox1);
            this.Controls.Add(this.txt_Extension);
            this.Controls.Add(this.lbl_Extension);
            this.Controls.Add(this.txt_Fax);
            this.Controls.Add(this.txt_CellPhone);
            this.Controls.Add(this.txt_OfficePhone);
            this.Controls.Add(this.txt_Email);
            this.Controls.Add(this.lbl_ContactEmail);
            this.Controls.Add(this.lbl_ContactFax);
            this.Controls.Add(this.lbl_ContactCellPhone);
            this.Controls.Add(this.lbl_ContactOfficePhone);
            this.Controls.Add(this.lbl_ContactName);
            this.Controls.Add(this.txt_Name);
            this.Name = "FormAddNewContact";
            this.Text = "Add New Contact";
            this.groupBox1.ResumeLayout(false);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.TextBox txt_Fax;
        private System.Windows.Forms.TextBox txt_CellPhone;
        private System.Windows.Forms.TextBox txt_OfficePhone;
        private System.Windows.Forms.TextBox txt_Email;
        private System.Windows.Forms.Label lbl_ContactEmail;
        private System.Windows.Forms.Label lbl_ContactFax;
        private System.Windows.Forms.Label lbl_ContactCellPhone;
        private System.Windows.Forms.Label lbl_ContactOfficePhone;
        private System.Windows.Forms.Label lbl_ContactName;
        private System.Windows.Forms.TextBox txt_Name;
        private System.Windows.Forms.Label lbl_Extension;
        private System.Windows.Forms.TextBox txt_Extension;
        private System.Windows.Forms.GroupBox groupBox1;
        private System.Windows.Forms.Button btn_SaveEntry;
        private System.Windows.Forms.Button btn_Cancel;
    }
}