// <auto-generated/>

namespace TII_NewDatabase
{
    partial class FormAddNewBuilding
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.groupBox1 = new System.Windows.Forms.GroupBox();
            this.btn_SaveEntry = new System.Windows.Forms.Button();
            this.btn_Cancel = new System.Windows.Forms.Button();
            this.lbl_BuildingAddress = new System.Windows.Forms.Label();
            this.txt_BuildingCity = new System.Windows.Forms.TextBox();
            this.txt_BuildingZip = new System.Windows.Forms.TextBox();
            this.txt_BuildingState = new System.Windows.Forms.TextBox();
            this.txt_BuildingStreet = new System.Windows.Forms.TextBox();
            this.txt_BuildingName = new System.Windows.Forms.TextBox();
            this.lbl_BuildingName = new System.Windows.Forms.Label();
            this.lbl_BuildingOwner = new System.Windows.Forms.Label();
            this.cbo_Owner = new System.Windows.Forms.ComboBox();
            this.cbo_BuildingCounty = new System.Windows.Forms.ComboBox();
            this.txt_HourlyFee = new System.Windows.Forms.TextBox();
            this.lbl_HourlyFee = new System.Windows.Forms.Label();
            this.txt_FirmFee = new System.Windows.Forms.TextBox();
            this.lbl_FirmFee = new System.Windows.Forms.Label();
            this.lbl_BuildingCounty = new System.Windows.Forms.Label();
            this.cbo_BuildingAnniversary = new System.Windows.Forms.ComboBox();
            this.lbl_Contractor = new System.Windows.Forms.Label();
            this.lbl_Anniversary = new System.Windows.Forms.Label();
            this.cbo_Contractor = new System.Windows.Forms.ComboBox();
            this.groupBox1.SuspendLayout();
            this.SuspendLayout();
            // 
            // groupBox1
            // 
            this.groupBox1.Controls.Add(this.btn_SaveEntry);
            this.groupBox1.Controls.Add(this.btn_Cancel);
            this.groupBox1.Location = new System.Drawing.Point(12, 281);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new System.Drawing.Size(242, 81);
            this.groupBox1.TabIndex = 19;
            this.groupBox1.TabStop = false;
            // 
            // btn_SaveEntry
            // 
            this.btn_SaveEntry.Location = new System.Drawing.Point(6, 19);
            this.btn_SaveEntry.Name = "btn_SaveEntry";
            this.btn_SaveEntry.Size = new System.Drawing.Size(230, 23);
            this.btn_SaveEntry.TabIndex = 0;
            this.btn_SaveEntry.Text = "Save As New Entry";
            this.btn_SaveEntry.UseVisualStyleBackColor = true;
            this.btn_SaveEntry.Click += new System.EventHandler(this.SaveEntry);
            // 
            // btn_Cancel
            // 
            this.btn_Cancel.DialogResult = System.Windows.Forms.DialogResult.Cancel;
            this.btn_Cancel.Location = new System.Drawing.Point(6, 48);
            this.btn_Cancel.Name = "btn_Cancel";
            this.btn_Cancel.Size = new System.Drawing.Size(230, 23);
            this.btn_Cancel.TabIndex = 1;
            this.btn_Cancel.Text = "Cancel";
            this.btn_Cancel.UseVisualStyleBackColor = true;
            // 
            // lbl_BuildingAddress
            // 
            this.lbl_BuildingAddress.AutoSize = true;
            this.lbl_BuildingAddress.Location = new System.Drawing.Point(30, 84);
            this.lbl_BuildingAddress.Name = "lbl_BuildingAddress";
            this.lbl_BuildingAddress.Size = new System.Drawing.Size(48, 13);
            this.lbl_BuildingAddress.TabIndex = 13;
            this.lbl_BuildingAddress.Text = "Address:";
            // 
            // txt_BuildingCity
            // 
            this.txt_BuildingCity.Location = new System.Drawing.Point(84, 107);
            this.txt_BuildingCity.Name = "txt_BuildingCity";
            this.txt_BuildingCity.Size = new System.Drawing.Size(80, 20);
            this.txt_BuildingCity.TabIndex = 3;
            // 
            // txt_BuildingZip
            // 
            this.txt_BuildingZip.Location = new System.Drawing.Point(203, 107);
            this.txt_BuildingZip.Name = "txt_BuildingZip";
            this.txt_BuildingZip.Size = new System.Drawing.Size(52, 20);
            this.txt_BuildingZip.TabIndex = 5;
            // 
            // txt_BuildingState
            // 
            this.txt_BuildingState.Location = new System.Drawing.Point(170, 107);
            this.txt_BuildingState.Name = "txt_BuildingState";
            this.txt_BuildingState.Size = new System.Drawing.Size(27, 20);
            this.txt_BuildingState.TabIndex = 4;
            // 
            // txt_BuildingStreet
            // 
            this.txt_BuildingStreet.Location = new System.Drawing.Point(84, 81);
            this.txt_BuildingStreet.Name = "txt_BuildingStreet";
            this.txt_BuildingStreet.Size = new System.Drawing.Size(171, 20);
            this.txt_BuildingStreet.TabIndex = 2;
            // 
            // txt_BuildingName
            // 
            this.txt_BuildingName.Location = new System.Drawing.Point(84, 55);
            this.txt_BuildingName.Name = "txt_BuildingName";
            this.txt_BuildingName.Size = new System.Drawing.Size(171, 20);
            this.txt_BuildingName.TabIndex = 1;
            // 
            // lbl_BuildingName
            // 
            this.lbl_BuildingName.AutoSize = true;
            this.lbl_BuildingName.Location = new System.Drawing.Point(40, 58);
            this.lbl_BuildingName.Name = "lbl_BuildingName";
            this.lbl_BuildingName.Size = new System.Drawing.Size(38, 13);
            this.lbl_BuildingName.TabIndex = 12;
            this.lbl_BuildingName.Text = "Name:";
            // 
            // lbl_BuildingOwner
            // 
            this.lbl_BuildingOwner.AutoSize = true;
            this.lbl_BuildingOwner.Location = new System.Drawing.Point(37, 18);
            this.lbl_BuildingOwner.Name = "lbl_BuildingOwner";
            this.lbl_BuildingOwner.Size = new System.Drawing.Size(41, 13);
            this.lbl_BuildingOwner.TabIndex = 11;
            this.lbl_BuildingOwner.Text = "Owner:";
            // 
            // cbo_Owner
            // 
            this.cbo_Owner.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.Suggest;
            this.cbo_Owner.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.ListItems;
            this.cbo_Owner.FormattingEnabled = true;
            this.cbo_Owner.Location = new System.Drawing.Point(84, 15);
            this.cbo_Owner.Name = "cbo_Owner";
            this.cbo_Owner.Size = new System.Drawing.Size(171, 21);
            this.cbo_Owner.TabIndex = 0;
            this.cbo_Owner.Leave += new System.EventHandler(this.EnsureValidListboxInput);
            // 
            // cbo_BuildingCounty
            // 
            this.cbo_BuildingCounty.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.Suggest;
            this.cbo_BuildingCounty.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.ListItems;
            this.cbo_BuildingCounty.BackColor = System.Drawing.SystemColors.Window;
            this.cbo_BuildingCounty.FormattingEnabled = true;
            this.cbo_BuildingCounty.Items.AddRange(new object[] {
            "Allegany",
            "Anne Arundel",
            "Baltimore",
            "Baltimore City",
            "Calvert",
            "Caroline",
            "Carroll",
            "Cecil",
            "Charles",
            "Dorchester",
            "Frederick",
            "Garrett",
            "Harford",
            "Howard",
            "Kent",
            "Montgomery",
            "Prince George\'s",
            "Queen Anne\'s",
            "Saint Mary\'s",
            "Somerset",
            "Talbot",
            "Washington",
            "Washington D.C.",
            "Wicomico",
            "Worcester"});
            this.cbo_BuildingCounty.Location = new System.Drawing.Point(84, 133);
            this.cbo_BuildingCounty.Name = "cbo_BuildingCounty";
            this.cbo_BuildingCounty.Size = new System.Drawing.Size(113, 21);
            this.cbo_BuildingCounty.TabIndex = 6;
            this.cbo_BuildingCounty.Leave += new System.EventHandler(this.EnsureValidListboxInput);
            // 
            // txt_HourlyFee
            // 
            this.txt_HourlyFee.Location = new System.Drawing.Point(85, 194);
            this.txt_HourlyFee.Name = "txt_HourlyFee";
            this.txt_HourlyFee.Size = new System.Drawing.Size(79, 20);
            this.txt_HourlyFee.TabIndex = 8;
            // 
            // lbl_HourlyFee
            // 
            this.lbl_HourlyFee.AutoSize = true;
            this.lbl_HourlyFee.Location = new System.Drawing.Point(36, 197);
            this.lbl_HourlyFee.Name = "lbl_HourlyFee";
            this.lbl_HourlyFee.Size = new System.Drawing.Size(40, 13);
            this.lbl_HourlyFee.TabIndex = 16;
            this.lbl_HourlyFee.Text = "Hourly:";
            // 
            // txt_FirmFee
            // 
            this.txt_FirmFee.Location = new System.Drawing.Point(84, 168);
            this.txt_FirmFee.Name = "txt_FirmFee";
            this.txt_FirmFee.Size = new System.Drawing.Size(79, 20);
            this.txt_FirmFee.TabIndex = 7;
            // 
            // lbl_FirmFee
            // 
            this.lbl_FirmFee.AutoSize = true;
            this.lbl_FirmFee.Location = new System.Drawing.Point(35, 171);
            this.lbl_FirmFee.Name = "lbl_FirmFee";
            this.lbl_FirmFee.Size = new System.Drawing.Size(29, 13);
            this.lbl_FirmFee.TabIndex = 15;
            this.lbl_FirmFee.Text = "Firm:";
            // 
            // lbl_BuildingCounty
            // 
            this.lbl_BuildingCounty.AutoSize = true;
            this.lbl_BuildingCounty.Location = new System.Drawing.Point(35, 136);
            this.lbl_BuildingCounty.Name = "lbl_BuildingCounty";
            this.lbl_BuildingCounty.Size = new System.Drawing.Size(43, 13);
            this.lbl_BuildingCounty.TabIndex = 14;
            this.lbl_BuildingCounty.Text = "County:";
            // 
            // cbo_BuildingAnniversary
            // 
            this.cbo_BuildingAnniversary.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.Suggest;
            this.cbo_BuildingAnniversary.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.ListItems;
            this.cbo_BuildingAnniversary.BackColor = System.Drawing.SystemColors.Window;
            this.cbo_BuildingAnniversary.FormattingEnabled = true;
            this.cbo_BuildingAnniversary.Items.AddRange(new object[] {
            "January",
            "February",
            "March",
            "April",
            "May",
            "June",
            "July",
            "August",
            "September",
            "October",
            "November",
            "December"});
            this.cbo_BuildingAnniversary.Location = new System.Drawing.Point(84, 220);
            this.cbo_BuildingAnniversary.Name = "cbo_BuildingAnniversary";
            this.cbo_BuildingAnniversary.Size = new System.Drawing.Size(115, 21);
            this.cbo_BuildingAnniversary.TabIndex = 9;
            this.cbo_BuildingAnniversary.Leave += new System.EventHandler(this.EnsureValidListboxInput);
            // 
            // lbl_Contractor
            // 
            this.lbl_Contractor.AutoSize = true;
            this.lbl_Contractor.Location = new System.Drawing.Point(18, 249);
            this.lbl_Contractor.Name = "lbl_Contractor";
            this.lbl_Contractor.Size = new System.Drawing.Size(59, 13);
            this.lbl_Contractor.TabIndex = 18;
            this.lbl_Contractor.Text = "Contractor:";
            // 
            // lbl_Anniversary
            // 
            this.lbl_Anniversary.AutoSize = true;
            this.lbl_Anniversary.Location = new System.Drawing.Point(12, 223);
            this.lbl_Anniversary.Name = "lbl_Anniversary";
            this.lbl_Anniversary.Size = new System.Drawing.Size(65, 13);
            this.lbl_Anniversary.TabIndex = 17;
            this.lbl_Anniversary.Text = "Anniversary:";
            // 
            // cbo_Contractor
            // 
            this.cbo_Contractor.FormattingEnabled = true;
            this.cbo_Contractor.Location = new System.Drawing.Point(83, 246);
            this.cbo_Contractor.Name = "cbo_Contractor";
            this.cbo_Contractor.Size = new System.Drawing.Size(165, 21);
            this.cbo_Contractor.TabIndex = 20;
            // 
            // FormAddNewBuilding
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.CancelButton = this.btn_Cancel;
            this.ClientSize = new System.Drawing.Size(266, 374);
            this.Controls.Add(this.cbo_Contractor);
            this.Controls.Add(this.cbo_BuildingAnniversary);
            this.Controls.Add(this.lbl_Contractor);
            this.Controls.Add(this.lbl_Anniversary);
            this.Controls.Add(this.cbo_BuildingCounty);
            this.Controls.Add(this.txt_HourlyFee);
            this.Controls.Add(this.lbl_HourlyFee);
            this.Controls.Add(this.txt_FirmFee);
            this.Controls.Add(this.lbl_FirmFee);
            this.Controls.Add(this.lbl_BuildingCounty);
            this.Controls.Add(this.cbo_Owner);
            this.Controls.Add(this.lbl_BuildingOwner);
            this.Controls.Add(this.groupBox1);
            this.Controls.Add(this.lbl_BuildingAddress);
            this.Controls.Add(this.txt_BuildingCity);
            this.Controls.Add(this.txt_BuildingZip);
            this.Controls.Add(this.txt_BuildingState);
            this.Controls.Add(this.txt_BuildingStreet);
            this.Controls.Add(this.txt_BuildingName);
            this.Controls.Add(this.lbl_BuildingName);
            this.Name = "FormAddNewBuilding";
            this.Text = "Add New Building";
            this.Load += new System.EventHandler(this.OnLoad);
            this.groupBox1.ResumeLayout(false);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.GroupBox groupBox1;
        private System.Windows.Forms.Button btn_SaveEntry;
        private System.Windows.Forms.Button btn_Cancel;
        private System.Windows.Forms.Label lbl_BuildingAddress;
        private System.Windows.Forms.TextBox txt_BuildingCity;
        private System.Windows.Forms.TextBox txt_BuildingZip;
        private System.Windows.Forms.TextBox txt_BuildingState;
        private System.Windows.Forms.TextBox txt_BuildingStreet;
        private System.Windows.Forms.TextBox txt_BuildingName;
        private System.Windows.Forms.Label lbl_BuildingName;
        private System.Windows.Forms.Label lbl_BuildingOwner;
        private System.Windows.Forms.ComboBox cbo_Owner;
        private System.Windows.Forms.ComboBox cbo_BuildingCounty;
        private System.Windows.Forms.TextBox txt_HourlyFee;
        private System.Windows.Forms.Label lbl_HourlyFee;
        private System.Windows.Forms.TextBox txt_FirmFee;
        private System.Windows.Forms.Label lbl_FirmFee;
        private System.Windows.Forms.Label lbl_BuildingCounty;
        private System.Windows.Forms.ComboBox cbo_BuildingAnniversary;
        private System.Windows.Forms.Label lbl_Contractor;
        private System.Windows.Forms.Label lbl_Anniversary;
        private System.Windows.Forms.ComboBox cbo_Contractor;
    }
}