// <auto-generated/>

namespace TII_NewDatabase.AddNewForms
{
    partial class FormAddNewElevator
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            this.lbl_ElevatorNumber = new System.Windows.Forms.Label();
            this.txt_ElevatorNumber = new System.Windows.Forms.TextBox();
            this.lbl_ElevatorType = new System.Windows.Forms.Label();
            this.txt_ElevatorNick = new System.Windows.Forms.TextBox();
            this.lbl_ElevatorNick = new System.Windows.Forms.Label();
            this.cbo_ElevatorType = new System.Windows.Forms.ComboBox();
            this.btn_SaveEntry = new System.Windows.Forms.Button();
            this.btn_Cancel = new System.Windows.Forms.Button();
            this.error_provider = new System.Windows.Forms.ErrorProvider(this.components);
            this.btn_GenerateNumber = new System.Windows.Forms.Button();
            ((System.ComponentModel.ISupportInitialize)(this.error_provider)).BeginInit();
            this.SuspendLayout();
            // 
            // lbl_ElevatorNumber
            // 
            this.lbl_ElevatorNumber.AutoSize = true;
            this.lbl_ElevatorNumber.Location = new System.Drawing.Point(54, 15);
            this.lbl_ElevatorNumber.Name = "lbl_ElevatorNumber";
            this.lbl_ElevatorNumber.Size = new System.Drawing.Size(89, 13);
            this.lbl_ElevatorNumber.TabIndex = 0;
            this.lbl_ElevatorNumber.Text = "Elevator Number:";
            // 
            // txt_ElevatorNumber
            // 
            this.txt_ElevatorNumber.Location = new System.Drawing.Point(149, 12);
            this.txt_ElevatorNumber.MaxLength = 20;
            this.txt_ElevatorNumber.Name = "txt_ElevatorNumber";
            this.txt_ElevatorNumber.Size = new System.Drawing.Size(100, 20);
            this.txt_ElevatorNumber.TabIndex = 1;
            this.txt_ElevatorNumber.TextChanged += new System.EventHandler(this.ValidateData);
            // 
            // lbl_ElevatorType
            // 
            this.lbl_ElevatorType.AutoSize = true;
            this.lbl_ElevatorType.Location = new System.Drawing.Point(67, 41);
            this.lbl_ElevatorType.Name = "lbl_ElevatorType";
            this.lbl_ElevatorType.Size = new System.Drawing.Size(76, 13);
            this.lbl_ElevatorType.TabIndex = 3;
            this.lbl_ElevatorType.Text = "Elevator Type:";
            // 
            // txt_ElevatorNick
            // 
            this.txt_ElevatorNick.Location = new System.Drawing.Point(149, 64);
            this.txt_ElevatorNick.Name = "txt_ElevatorNick";
            this.txt_ElevatorNick.Size = new System.Drawing.Size(100, 20);
            this.txt_ElevatorNick.TabIndex = 4;
            this.txt_ElevatorNick.TextChanged += new System.EventHandler(this.ValidateData);
            // 
            // lbl_ElevatorNick
            // 
            this.lbl_ElevatorNick.AutoSize = true;
            this.lbl_ElevatorNick.Location = new System.Drawing.Point(85, 67);
            this.lbl_ElevatorNick.Name = "lbl_ElevatorNick";
            this.lbl_ElevatorNick.Size = new System.Drawing.Size(58, 13);
            this.lbl_ElevatorNick.TabIndex = 5;
            this.lbl_ElevatorNick.Text = "Nickname:";
            // 
            // cbo_ElevatorType
            // 
            this.cbo_ElevatorType.FormattingEnabled = true;
            this.cbo_ElevatorType.Location = new System.Drawing.Point(149, 38);
            this.cbo_ElevatorType.Name = "cbo_ElevatorType";
            this.cbo_ElevatorType.Size = new System.Drawing.Size(100, 21);
            this.cbo_ElevatorType.TabIndex = 6;
            this.cbo_ElevatorType.TextChanged += new System.EventHandler(this.ValidateData);
            // 
            // btn_SaveEntry
            // 
            this.btn_SaveEntry.DialogResult = System.Windows.Forms.DialogResult.OK;
            this.btn_SaveEntry.Enabled = false;
            this.btn_SaveEntry.Location = new System.Drawing.Point(12, 90);
            this.btn_SaveEntry.Name = "btn_SaveEntry";
            this.btn_SaveEntry.Size = new System.Drawing.Size(310, 23);
            this.btn_SaveEntry.TabIndex = 7;
            this.btn_SaveEntry.Text = "Save Entry";
            this.btn_SaveEntry.UseVisualStyleBackColor = true;
            this.btn_SaveEntry.Click += new System.EventHandler(this.SaveEntry);
            // 
            // btn_Cancel
            // 
            this.btn_Cancel.DialogResult = System.Windows.Forms.DialogResult.Cancel;
            this.btn_Cancel.Location = new System.Drawing.Point(12, 119);
            this.btn_Cancel.Name = "btn_Cancel";
            this.btn_Cancel.Size = new System.Drawing.Size(310, 23);
            this.btn_Cancel.TabIndex = 8;
            this.btn_Cancel.Text = "Cancel";
            this.btn_Cancel.UseVisualStyleBackColor = true;
            // 
            // error_provider
            // 
            this.error_provider.ContainerControl = this;
            // 
            // btn_GenerateNumber
            // 
            this.btn_GenerateNumber.Location = new System.Drawing.Point(255, 12);
            this.btn_GenerateNumber.Name = "btn_GenerateNumber";
            this.btn_GenerateNumber.Size = new System.Drawing.Size(67, 20);
            this.btn_GenerateNumber.TabIndex = 9;
            this.btn_GenerateNumber.Text = "Generate...";
            this.btn_GenerateNumber.UseVisualStyleBackColor = true;
            this.btn_GenerateNumber.Click += new System.EventHandler(this.GenerateNumber);
            // 
            // FormAddNewElevator
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(334, 153);
            this.Controls.Add(this.btn_GenerateNumber);
            this.Controls.Add(this.btn_Cancel);
            this.Controls.Add(this.btn_SaveEntry);
            this.Controls.Add(this.cbo_ElevatorType);
            this.Controls.Add(this.lbl_ElevatorNick);
            this.Controls.Add(this.txt_ElevatorNick);
            this.Controls.Add(this.lbl_ElevatorType);
            this.Controls.Add(this.txt_ElevatorNumber);
            this.Controls.Add(this.lbl_ElevatorNumber);
            this.Name = "FormAddNewElevator";
            this.Text = "FormAddNewElevator";
            ((System.ComponentModel.ISupportInitialize)(this.error_provider)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.Label lbl_ElevatorNumber;
        private System.Windows.Forms.TextBox txt_ElevatorNumber;
        private System.Windows.Forms.Label lbl_ElevatorType;
        private System.Windows.Forms.TextBox txt_ElevatorNick;
        private System.Windows.Forms.Label lbl_ElevatorNick;
        private System.Windows.Forms.ComboBox cbo_ElevatorType;
        private System.Windows.Forms.Button btn_SaveEntry;
        private System.Windows.Forms.Button btn_Cancel;
        private System.Windows.Forms.ErrorProvider error_provider;
        private System.Windows.Forms.Button btn_GenerateNumber;
    }
}