//<auto-generated/>

namespace TII_NewDatabase.AddNewForms
{
    partial class FormAddNewCompany
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.lbl_CompanyName = new System.Windows.Forms.Label();
            this.txt_CompanyName = new System.Windows.Forms.TextBox();
            this.lbl_CompanyAddress = new System.Windows.Forms.Label();
            this.txt_CompanyCity = new System.Windows.Forms.TextBox();
            this.txt_CompanyZip = new System.Windows.Forms.TextBox();
            this.txt_CompanyState = new System.Windows.Forms.TextBox();
            this.txt_CompanyStreet = new System.Windows.Forms.TextBox();
            this.btn_SaveEntry = new System.Windows.Forms.Button();
            this.btn_Cancel = new System.Windows.Forms.Button();
            this.groupBox1 = new System.Windows.Forms.GroupBox();
            this.groupBox1.SuspendLayout();
            this.SuspendLayout();
            // 
            // lbl_CompanyName
            // 
            this.lbl_CompanyName.AutoSize = true;
            this.lbl_CompanyName.Location = new System.Drawing.Point(22, 14);
            this.lbl_CompanyName.Name = "lbl_CompanyName";
            this.lbl_CompanyName.Size = new System.Drawing.Size(38, 13);
            this.lbl_CompanyName.TabIndex = 0;
            this.lbl_CompanyName.Text = "Name:";
            // 
            // txt_CompanyName
            // 
            this.txt_CompanyName.Location = new System.Drawing.Point(66, 11);
            this.txt_CompanyName.Name = "txt_CompanyName";
            this.txt_CompanyName.Size = new System.Drawing.Size(171, 20);
            this.txt_CompanyName.TabIndex = 1;
            // 
            // lbl_CompanyAddress
            // 
            this.lbl_CompanyAddress.AutoSize = true;
            this.lbl_CompanyAddress.Location = new System.Drawing.Point(12, 40);
            this.lbl_CompanyAddress.Name = "lbl_CompanyAddress";
            this.lbl_CompanyAddress.Size = new System.Drawing.Size(48, 13);
            this.lbl_CompanyAddress.TabIndex = 21;
            this.lbl_CompanyAddress.Text = "Address:";
            // 
            // txt_CompanyCity
            // 
            this.txt_CompanyCity.Location = new System.Drawing.Point(66, 63);
            this.txt_CompanyCity.Name = "txt_CompanyCity";
            this.txt_CompanyCity.Size = new System.Drawing.Size(80, 20);
            this.txt_CompanyCity.TabIndex = 23;
            // 
            // txt_CompanyZip
            // 
            this.txt_CompanyZip.Location = new System.Drawing.Point(185, 63);
            this.txt_CompanyZip.Name = "txt_CompanyZip";
            this.txt_CompanyZip.Size = new System.Drawing.Size(52, 20);
            this.txt_CompanyZip.TabIndex = 25;
            // 
            // txt_CompanyState
            // 
            this.txt_CompanyState.Location = new System.Drawing.Point(152, 63);
            this.txt_CompanyState.Name = "txt_CompanyState";
            this.txt_CompanyState.Size = new System.Drawing.Size(27, 20);
            this.txt_CompanyState.TabIndex = 24;
            // 
            // txt_CompanyStreet
            // 
            this.txt_CompanyStreet.Location = new System.Drawing.Point(66, 37);
            this.txt_CompanyStreet.Name = "txt_CompanyStreet";
            this.txt_CompanyStreet.Size = new System.Drawing.Size(171, 20);
            this.txt_CompanyStreet.TabIndex = 22;
            // 
            // btn_SaveEntry
            // 
            this.btn_SaveEntry.Location = new System.Drawing.Point(6, 19);
            this.btn_SaveEntry.Name = "btn_SaveEntry";
            this.btn_SaveEntry.Size = new System.Drawing.Size(159, 23);
            this.btn_SaveEntry.TabIndex = 26;
            this.btn_SaveEntry.Text = "Save As New Entry";
            this.btn_SaveEntry.UseVisualStyleBackColor = true;
            this.btn_SaveEntry.Click += new System.EventHandler(this.SaveEntry);
            // 
            // btn_Cancel
            // 
            this.btn_Cancel.DialogResult = System.Windows.Forms.DialogResult.Cancel;
            this.btn_Cancel.Location = new System.Drawing.Point(6, 48);
            this.btn_Cancel.Name = "btn_Cancel";
            this.btn_Cancel.Size = new System.Drawing.Size(159, 23);
            this.btn_Cancel.TabIndex = 27;
            this.btn_Cancel.Text = "Cancel";
            this.btn_Cancel.UseVisualStyleBackColor = true;
            // 
            // groupBox1
            // 
            this.groupBox1.Controls.Add(this.btn_SaveEntry);
            this.groupBox1.Controls.Add(this.btn_Cancel);
            this.groupBox1.Location = new System.Drawing.Point(66, 90);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new System.Drawing.Size(171, 81);
            this.groupBox1.TabIndex = 28;
            this.groupBox1.TabStop = false;
            // 
            // FormAddNewCompany
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.CancelButton = this.btn_Cancel;
            this.ClientSize = new System.Drawing.Size(248, 185);
            this.Controls.Add(this.groupBox1);
            this.Controls.Add(this.lbl_CompanyAddress);
            this.Controls.Add(this.txt_CompanyCity);
            this.Controls.Add(this.txt_CompanyZip);
            this.Controls.Add(this.txt_CompanyState);
            this.Controls.Add(this.txt_CompanyStreet);
            this.Controls.Add(this.txt_CompanyName);
            this.Controls.Add(this.lbl_CompanyName);
            this.MaximizeBox = false;
            this.MinimizeBox = false;
            this.Name = "FormAddNewCompany";
            this.Text = "Add New Company";
            this.groupBox1.ResumeLayout(false);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.Label lbl_CompanyName;
        private System.Windows.Forms.TextBox txt_CompanyName;
        private System.Windows.Forms.Label lbl_CompanyAddress;
        private System.Windows.Forms.TextBox txt_CompanyCity;
        private System.Windows.Forms.TextBox txt_CompanyZip;
        private System.Windows.Forms.TextBox txt_CompanyState;
        private System.Windows.Forms.TextBox txt_CompanyStreet;
        private System.Windows.Forms.Button btn_SaveEntry;
        private System.Windows.Forms.Button btn_Cancel;
        private System.Windows.Forms.GroupBox groupBox1;
    }
}