// <auto-generated/>

namespace TII_NewDatabase
{
    partial class FormAddNewContact
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.txt_Email = new System.Windows.Forms.TextBox();
            this.lbl_ContactEmail = new System.Windows.Forms.Label();
            this.lbl_ContactFax = new System.Windows.Forms.Label();
            this.lbl_ContactCellPhone = new System.Windows.Forms.Label();
            this.lbl_ContactOfficePhone = new System.Windows.Forms.Label();
            this.lbl_ContactName = new System.Windows.Forms.Label();
            this.txt_Name = new System.Windows.Forms.TextBox();
            this.lbl_Extension = new System.Windows.Forms.Label();
            this.txt_Extension = new System.Windows.Forms.TextBox();
            this.groupBox1 = new System.Windows.Forms.GroupBox();
            this.btn_SaveEntry = new System.Windows.Forms.Button();
            this.btn_Cancel = new System.Windows.Forms.Button();
            this.cbo_Honorific = new System.Windows.Forms.ComboBox();
            this.txt_CellPhone = new System.Windows.Forms.MaskedTextBox();
            this.txt_Fax = new System.Windows.Forms.MaskedTextBox();
            this.txt_OfficePhone = new System.Windows.Forms.MaskedTextBox();
            this.tabctrl_Associate = new System.Windows.Forms.TabControl();
            this.tab_Company = new System.Windows.Forms.TabPage();
            this.btn_RemoveCompany = new System.Windows.Forms.Button();
            this.btn_AddCompany = new System.Windows.Forms.Button();
            this.lbx_AssociatedCompanies = new System.Windows.Forms.ListBox();
            this.txt_CompanyFilter = new System.Windows.Forms.TextBox();
            this.lbx_CompanyList = new System.Windows.Forms.ListBox();
            this.tab_Building = new System.Windows.Forms.TabPage();
            this.btn_RemoveBuilding = new System.Windows.Forms.Button();
            this.btn_AddBuilding = new System.Windows.Forms.Button();
            this.lbx_AssociatedBuildings = new System.Windows.Forms.ListBox();
            this.txt_BuildingFilter = new System.Windows.Forms.TextBox();
            this.lbx_BuildingList = new System.Windows.Forms.ListBox();
            this.groupBox1.SuspendLayout();
            this.tabctrl_Associate.SuspendLayout();
            this.tab_Company.SuspendLayout();
            this.tab_Building.SuspendLayout();
            this.SuspendLayout();
            // 
            // txt_Email
            // 
            this.txt_Email.Location = new System.Drawing.Point(90, 117);
            this.txt_Email.Name = "txt_Email";
            this.txt_Email.Size = new System.Drawing.Size(160, 20);
            this.txt_Email.TabIndex = 6;
            // 
            // lbl_ContactEmail
            // 
            this.lbl_ContactEmail.AutoSize = true;
            this.lbl_ContactEmail.Location = new System.Drawing.Point(45, 120);
            this.lbl_ContactEmail.Name = "lbl_ContactEmail";
            this.lbl_ContactEmail.Size = new System.Drawing.Size(39, 13);
            this.lbl_ContactEmail.TabIndex = 10;
            this.lbl_ContactEmail.Text = "E-Mail:";
            // 
            // lbl_ContactFax
            // 
            this.lbl_ContactFax.AutoSize = true;
            this.lbl_ContactFax.Location = new System.Drawing.Point(57, 94);
            this.lbl_ContactFax.Name = "lbl_ContactFax";
            this.lbl_ContactFax.Size = new System.Drawing.Size(27, 13);
            this.lbl_ContactFax.TabIndex = 9;
            this.lbl_ContactFax.Text = "Fax:";
            // 
            // lbl_ContactCellPhone
            // 
            this.lbl_ContactCellPhone.AutoSize = true;
            this.lbl_ContactCellPhone.Location = new System.Drawing.Point(23, 68);
            this.lbl_ContactCellPhone.Name = "lbl_ContactCellPhone";
            this.lbl_ContactCellPhone.Size = new System.Drawing.Size(61, 13);
            this.lbl_ContactCellPhone.TabIndex = 8;
            this.lbl_ContactCellPhone.Text = "Cell Phone:";
            // 
            // lbl_ContactOfficePhone
            // 
            this.lbl_ContactOfficePhone.AutoSize = true;
            this.lbl_ContactOfficePhone.Location = new System.Drawing.Point(12, 42);
            this.lbl_ContactOfficePhone.Name = "lbl_ContactOfficePhone";
            this.lbl_ContactOfficePhone.Size = new System.Drawing.Size(72, 13);
            this.lbl_ContactOfficePhone.TabIndex = 13;
            this.lbl_ContactOfficePhone.Text = "Office Phone:";
            // 
            // lbl_ContactName
            // 
            this.lbl_ContactName.AutoSize = true;
            this.lbl_ContactName.Location = new System.Drawing.Point(45, 16);
            this.lbl_ContactName.Name = "lbl_ContactName";
            this.lbl_ContactName.Size = new System.Drawing.Size(38, 13);
            this.lbl_ContactName.TabIndex = 7;
            this.lbl_ContactName.Text = "Name:";
            // 
            // txt_Name
            // 
            this.txt_Name.Location = new System.Drawing.Point(135, 13);
            this.txt_Name.Name = "txt_Name";
            this.txt_Name.Size = new System.Drawing.Size(115, 20);
            this.txt_Name.TabIndex = 1;
            // 
            // lbl_Extension
            // 
            this.lbl_Extension.AutoSize = true;
            this.lbl_Extension.Location = new System.Drawing.Point(187, 42);
            this.lbl_Extension.Name = "lbl_Extension";
            this.lbl_Extension.Size = new System.Drawing.Size(12, 13);
            this.lbl_Extension.TabIndex = 12;
            this.lbl_Extension.Text = "x";
            // 
            // txt_Extension
            // 
            this.txt_Extension.Location = new System.Drawing.Point(196, 39);
            this.txt_Extension.Name = "txt_Extension";
            this.txt_Extension.Size = new System.Drawing.Size(54, 20);
            this.txt_Extension.TabIndex = 3;
            // 
            // groupBox1
            // 
            this.groupBox1.Controls.Add(this.btn_SaveEntry);
            this.groupBox1.Controls.Add(this.btn_Cancel);
            this.groupBox1.Location = new System.Drawing.Point(12, 143);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new System.Drawing.Size(260, 81);
            this.groupBox1.TabIndex = 11;
            this.groupBox1.TabStop = false;
            // 
            // btn_SaveEntry
            // 
            this.btn_SaveEntry.Location = new System.Drawing.Point(6, 19);
            this.btn_SaveEntry.Name = "btn_SaveEntry";
            this.btn_SaveEntry.Size = new System.Drawing.Size(248, 23);
            this.btn_SaveEntry.TabIndex = 0;
            this.btn_SaveEntry.Text = "Save As New Entry";
            this.btn_SaveEntry.UseVisualStyleBackColor = true;
            this.btn_SaveEntry.Click += new System.EventHandler(this.SaveEntry_Click);
            // 
            // btn_Cancel
            // 
            this.btn_Cancel.DialogResult = System.Windows.Forms.DialogResult.Cancel;
            this.btn_Cancel.Location = new System.Drawing.Point(6, 48);
            this.btn_Cancel.Name = "btn_Cancel";
            this.btn_Cancel.Size = new System.Drawing.Size(248, 23);
            this.btn_Cancel.TabIndex = 1;
            this.btn_Cancel.Text = "Cancel";
            this.btn_Cancel.UseVisualStyleBackColor = true;
            // 
            // cbo_Honorific
            // 
            this.cbo_Honorific.FormattingEnabled = true;
            this.cbo_Honorific.Items.AddRange(new object[] {
            "Mr.",
            "Ms.",
            "Mrs.",
            "Dr.",
            "Rev.",
            "Sr."});
            this.cbo_Honorific.Location = new System.Drawing.Point(90, 12);
            this.cbo_Honorific.Name = "cbo_Honorific";
            this.cbo_Honorific.Size = new System.Drawing.Size(39, 21);
            this.cbo_Honorific.TabIndex = 0;
            // 
            // txt_CellPhone
            // 
            this.txt_CellPhone.Location = new System.Drawing.Point(90, 65);
            this.txt_CellPhone.Mask = "(999) 000-0000";
            this.txt_CellPhone.Name = "txt_CellPhone";
            this.txt_CellPhone.Size = new System.Drawing.Size(100, 20);
            this.txt_CellPhone.TabIndex = 4;
            // 
            // txt_Fax
            // 
            this.txt_Fax.Location = new System.Drawing.Point(90, 91);
            this.txt_Fax.Mask = "(999) 000-0000";
            this.txt_Fax.Name = "txt_Fax";
            this.txt_Fax.Size = new System.Drawing.Size(100, 20);
            this.txt_Fax.TabIndex = 5;
            // 
            // txt_OfficePhone
            // 
            this.txt_OfficePhone.Location = new System.Drawing.Point(90, 39);
            this.txt_OfficePhone.Mask = "(999) 000-0000";
            this.txt_OfficePhone.Name = "txt_OfficePhone";
            this.txt_OfficePhone.Size = new System.Drawing.Size(100, 20);
            this.txt_OfficePhone.TabIndex = 2;
            // 
            // tabctrl_Associate
            // 
            this.tabctrl_Associate.Controls.Add(this.tab_Company);
            this.tabctrl_Associate.Controls.Add(this.tab_Building);
            this.tabctrl_Associate.Location = new System.Drawing.Point(278, 12);
            this.tabctrl_Associate.Name = "tabctrl_Associate";
            this.tabctrl_Associate.SelectedIndex = 0;
            this.tabctrl_Associate.Size = new System.Drawing.Size(304, 211);
            this.tabctrl_Associate.TabIndex = 14;
            // 
            // tab_Company
            // 
            this.tab_Company.Controls.Add(this.btn_RemoveCompany);
            this.tab_Company.Controls.Add(this.btn_AddCompany);
            this.tab_Company.Controls.Add(this.lbx_AssociatedCompanies);
            this.tab_Company.Controls.Add(this.txt_CompanyFilter);
            this.tab_Company.Controls.Add(this.lbx_CompanyList);
            this.tab_Company.Location = new System.Drawing.Point(4, 22);
            this.tab_Company.Name = "tab_Company";
            this.tab_Company.Padding = new System.Windows.Forms.Padding(3);
            this.tab_Company.Size = new System.Drawing.Size(296, 185);
            this.tab_Company.TabIndex = 0;
            this.tab_Company.Text = "Company";
            this.tab_Company.UseVisualStyleBackColor = true;
            // 
            // btn_RemoveCompany
            // 
            this.btn_RemoveCompany.Location = new System.Drawing.Point(132, 89);
            this.btn_RemoveCompany.Name = "btn_RemoveCompany";
            this.btn_RemoveCompany.Size = new System.Drawing.Size(29, 23);
            this.btn_RemoveCompany.TabIndex = 18;
            this.btn_RemoveCompany.Text = "<<";
            this.btn_RemoveCompany.UseVisualStyleBackColor = true;
            // 
            // btn_AddCompany
            // 
            this.btn_AddCompany.Location = new System.Drawing.Point(132, 60);
            this.btn_AddCompany.Name = "btn_AddCompany";
            this.btn_AddCompany.Size = new System.Drawing.Size(29, 23);
            this.btn_AddCompany.TabIndex = 17;
            this.btn_AddCompany.Text = ">>";
            this.btn_AddCompany.UseVisualStyleBackColor = true;
            // 
            // lbx_AssociatedCompanies
            // 
            this.lbx_AssociatedCompanies.FormattingEnabled = true;
            this.lbx_AssociatedCompanies.Location = new System.Drawing.Point(167, 34);
            this.lbx_AssociatedCompanies.Name = "lbx_AssociatedCompanies";
            this.lbx_AssociatedCompanies.Size = new System.Drawing.Size(120, 147);
            this.lbx_AssociatedCompanies.TabIndex = 15;
            // 
            // txt_CompanyFilter
            // 
            this.txt_CompanyFilter.Location = new System.Drawing.Point(6, 6);
            this.txt_CompanyFilter.Name = "txt_CompanyFilter";
            this.txt_CompanyFilter.Size = new System.Drawing.Size(120, 20);
            this.txt_CompanyFilter.TabIndex = 16;
            // 
            // lbx_CompanyList
            // 
            this.lbx_CompanyList.FormattingEnabled = true;
            this.lbx_CompanyList.Location = new System.Drawing.Point(6, 35);
            this.lbx_CompanyList.Name = "lbx_CompanyList";
            this.lbx_CompanyList.Size = new System.Drawing.Size(120, 147);
            this.lbx_CompanyList.TabIndex = 15;
            // 
            // tab_Building
            // 
            this.tab_Building.Controls.Add(this.btn_RemoveBuilding);
            this.tab_Building.Controls.Add(this.btn_AddBuilding);
            this.tab_Building.Controls.Add(this.lbx_AssociatedBuildings);
            this.tab_Building.Controls.Add(this.txt_BuildingFilter);
            this.tab_Building.Controls.Add(this.lbx_BuildingList);
            this.tab_Building.Location = new System.Drawing.Point(4, 22);
            this.tab_Building.Name = "tab_Building";
            this.tab_Building.Padding = new System.Windows.Forms.Padding(3);
            this.tab_Building.Size = new System.Drawing.Size(296, 185);
            this.tab_Building.TabIndex = 1;
            this.tab_Building.Text = "Building";
            this.tab_Building.UseVisualStyleBackColor = true;
            // 
            // btn_RemoveBuilding
            // 
            this.btn_RemoveBuilding.Location = new System.Drawing.Point(132, 89);
            this.btn_RemoveBuilding.Name = "btn_RemoveBuilding";
            this.btn_RemoveBuilding.Size = new System.Drawing.Size(29, 23);
            this.btn_RemoveBuilding.TabIndex = 23;
            this.btn_RemoveBuilding.Text = "<<";
            this.btn_RemoveBuilding.UseVisualStyleBackColor = true;
            // 
            // btn_AddBuilding
            // 
            this.btn_AddBuilding.Location = new System.Drawing.Point(132, 60);
            this.btn_AddBuilding.Name = "btn_AddBuilding";
            this.btn_AddBuilding.Size = new System.Drawing.Size(29, 23);
            this.btn_AddBuilding.TabIndex = 22;
            this.btn_AddBuilding.Text = ">>";
            this.btn_AddBuilding.UseVisualStyleBackColor = true;
            // 
            // lbx_AssociatedBuildings
            // 
            this.lbx_AssociatedBuildings.FormattingEnabled = true;
            this.lbx_AssociatedBuildings.Location = new System.Drawing.Point(167, 34);
            this.lbx_AssociatedBuildings.Name = "lbx_AssociatedBuildings";
            this.lbx_AssociatedBuildings.Size = new System.Drawing.Size(120, 147);
            this.lbx_AssociatedBuildings.TabIndex = 19;
            // 
            // txt_BuildingFilter
            // 
            this.txt_BuildingFilter.Location = new System.Drawing.Point(6, 6);
            this.txt_BuildingFilter.Name = "txt_BuildingFilter";
            this.txt_BuildingFilter.Size = new System.Drawing.Size(120, 20);
            this.txt_BuildingFilter.TabIndex = 21;
            // 
            // lbx_BuildingList
            // 
            this.lbx_BuildingList.FormattingEnabled = true;
            this.lbx_BuildingList.Location = new System.Drawing.Point(6, 35);
            this.lbx_BuildingList.Name = "lbx_BuildingList";
            this.lbx_BuildingList.Size = new System.Drawing.Size(120, 147);
            this.lbx_BuildingList.TabIndex = 20;
            // 
            // FormAddNewContact
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(596, 235);
            this.Controls.Add(this.tabctrl_Associate);
            this.Controls.Add(this.txt_OfficePhone);
            this.Controls.Add(this.txt_Fax);
            this.Controls.Add(this.txt_CellPhone);
            this.Controls.Add(this.cbo_Honorific);
            this.Controls.Add(this.groupBox1);
            this.Controls.Add(this.txt_Extension);
            this.Controls.Add(this.lbl_Extension);
            this.Controls.Add(this.txt_Email);
            this.Controls.Add(this.lbl_ContactEmail);
            this.Controls.Add(this.lbl_ContactFax);
            this.Controls.Add(this.lbl_ContactCellPhone);
            this.Controls.Add(this.lbl_ContactOfficePhone);
            this.Controls.Add(this.lbl_ContactName);
            this.Controls.Add(this.txt_Name);
            this.MaximizeBox = false;
            this.MinimizeBox = false;
            this.Name = "FormAddNewContact";
            this.Text = "Add New Contact";
            this.groupBox1.ResumeLayout(false);
            this.tabctrl_Associate.ResumeLayout(false);
            this.tab_Company.ResumeLayout(false);
            this.tab_Company.PerformLayout();
            this.tab_Building.ResumeLayout(false);
            this.tab_Building.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.TextBox txt_Email;
        private System.Windows.Forms.Label lbl_ContactEmail;
        private System.Windows.Forms.Label lbl_ContactFax;
        private System.Windows.Forms.Label lbl_ContactCellPhone;
        private System.Windows.Forms.Label lbl_ContactOfficePhone;
        private System.Windows.Forms.Label lbl_ContactName;
        private System.Windows.Forms.TextBox txt_Name;
        private System.Windows.Forms.Label lbl_Extension;
        private System.Windows.Forms.TextBox txt_Extension;
        private System.Windows.Forms.GroupBox groupBox1;
        private System.Windows.Forms.Button btn_SaveEntry;
        private System.Windows.Forms.Button btn_Cancel;
        private System.Windows.Forms.ComboBox cbo_Honorific;
        private System.Windows.Forms.MaskedTextBox txt_CellPhone;
        private System.Windows.Forms.MaskedTextBox txt_Fax;
        private System.Windows.Forms.MaskedTextBox txt_OfficePhone;
        private System.Windows.Forms.TabControl tabctrl_Associate;
        private System.Windows.Forms.TabPage tab_Company;
        private System.Windows.Forms.TabPage tab_Building;
        private System.Windows.Forms.Button btn_RemoveCompany;
        private System.Windows.Forms.Button btn_AddCompany;
        private System.Windows.Forms.ListBox lbx_AssociatedCompanies;
        private System.Windows.Forms.TextBox txt_CompanyFilter;
        private System.Windows.Forms.ListBox lbx_CompanyList;
        private System.Windows.Forms.Button btn_RemoveBuilding;
        private System.Windows.Forms.Button btn_AddBuilding;
        private System.Windows.Forms.ListBox lbx_AssociatedBuildings;
        private System.Windows.Forms.TextBox txt_BuildingFilter;
        private System.Windows.Forms.ListBox lbx_BuildingList;
    }
}