// <auto-generated />

namespace TII_NewDatabase
{
    partial class FormPreferances
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.lbl_ReportFileLocation = new System.Windows.Forms.Label();
            this.txt_ReportFileLocation = new System.Windows.Forms.TextBox();
            this.btn_BrowseForReportFolder = new System.Windows.Forms.Button();
            this.btn_Save = new System.Windows.Forms.Button();
            this.SuspendLayout();
            // 
            // lbl_ReportFileLocation
            // 
            this.lbl_ReportFileLocation.AutoSize = true;
            this.lbl_ReportFileLocation.Location = new System.Drawing.Point(12, 9);
            this.lbl_ReportFileLocation.Name = "lbl_ReportFileLocation";
            this.lbl_ReportFileLocation.Size = new System.Drawing.Size(105, 13);
            this.lbl_ReportFileLocation.TabIndex = 0;
            this.lbl_ReportFileLocation.Text = "Report File Location:";
            // 
            // txt_ReportFileLocation
            // 
            this.txt_ReportFileLocation.Location = new System.Drawing.Point(15, 25);
            this.txt_ReportFileLocation.Name = "txt_ReportFileLocation";
            this.txt_ReportFileLocation.Size = new System.Drawing.Size(257, 20);
            this.txt_ReportFileLocation.TabIndex = 1;
            // 
            // btn_BrowseForReportFolder
            // 
            this.btn_BrowseForReportFolder.Location = new System.Drawing.Point(213, 51);
            this.btn_BrowseForReportFolder.Name = "btn_BrowseForReportFolder";
            this.btn_BrowseForReportFolder.Size = new System.Drawing.Size(59, 21);
            this.btn_BrowseForReportFolder.TabIndex = 2;
            this.btn_BrowseForReportFolder.Text = "Browse...";
            this.btn_BrowseForReportFolder.UseVisualStyleBackColor = true;
            this.btn_BrowseForReportFolder.Click += new System.EventHandler(this.OnClick_BrowseForReportFolder);
            // 
            // btn_Save
            // 
            this.btn_Save.DialogResult = System.Windows.Forms.DialogResult.OK;
            this.btn_Save.Location = new System.Drawing.Point(15, 230);
            this.btn_Save.Name = "btn_Save";
            this.btn_Save.Size = new System.Drawing.Size(257, 23);
            this.btn_Save.TabIndex = 3;
            this.btn_Save.Text = "Save";
            this.btn_Save.UseVisualStyleBackColor = true;
            this.btn_Save.Click += new System.EventHandler(this.OnClick_SaveAndExit);
            // 
            // FormPreferances
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(284, 265);
            this.Controls.Add(this.btn_Save);
            this.Controls.Add(this.btn_BrowseForReportFolder);
            this.Controls.Add(this.txt_ReportFileLocation);
            this.Controls.Add(this.lbl_ReportFileLocation);
            this.Name = "FormPreferances";
            this.Text = "Preferances";
            this.Load += new System.EventHandler(this.OnLoad);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.Label lbl_ReportFileLocation;
        private System.Windows.Forms.TextBox txt_ReportFileLocation;
        private System.Windows.Forms.Button btn_BrowseForReportFolder;
        private System.Windows.Forms.Button btn_Save;
    }
}