// <auto-generated />

namespace TII_NewDatabase
{
    /// <summary>
    /// Partial class - contains the code generated by the Form Creator.
    /// </summary>
    public partial class Main_Form
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Main Menu Strip Bar.
        /// </summary>
        private System.Windows.Forms.MenuStrip mnuMainMenuStrip;

        /// <summary>
        /// File Menu Dropdown.
        /// </summary>
        private System.Windows.Forms.ToolStripMenuItem fileToolStripMenuItem;

        /// <summary>
        /// Settings Menu Dropdown.
        /// </summary>
        private System.Windows.Forms.ToolStripMenuItem settingsToolStripMenuItem;

        /// <summary>
        /// Forces the creation of a backup outside of the scheduled backups.
        /// </summary>
        private System.Windows.Forms.ToolStripMenuItem forceBackupToolStripMenuItem;

        /// <summary>
        /// Exit the Database Program.
        /// </summary>
        private System.Windows.Forms.ToolStripMenuItem exitToolStripMenuItem;

        /// <summary>
        /// View the Connection settings and edit if required.
        /// </summary>
        private System.Windows.Forms.ToolStripMenuItem connectionsToolStripMenuItem;

        /// <summary>
        /// View/Edit the user preferences.
        /// </summary>
        private System.Windows.Forms.ToolStripMenuItem preferencesToolStripMenuItem;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">True if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (this.components != null))
            {
                this.components.Dispose();
            }

            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            this.mnuMainMenuStrip = new System.Windows.Forms.MenuStrip();
            this.fileToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.forceBackupToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.exitToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.settingsToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.connectionsToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.preferencesToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.testMethodToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.gbx_InspectionHistory = new System.Windows.Forms.GroupBox();
            this.btn_EnterNewInspection = new System.Windows.Forms.Button();
            this.lvw_InspectionList = new System.Windows.Forms.ListView();
            this.col_Date = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.col_InspectionType = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.col_Status = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.col_Inspector = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.col_Report = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.gbx_Building = new System.Windows.Forms.GroupBox();
            this.btn_EditBuilding = new System.Windows.Forms.Button();
            this.cbo_BuildingAnniversary = new System.Windows.Forms.ComboBox();
            this.cbo_BuildingCounty = new System.Windows.Forms.ComboBox();
            this.lvw_RelatedDocuments = new System.Windows.Forms.ListView();
            this.col_Title = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.col_Desc = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.btn_AddBldgDocument = new System.Windows.Forms.Button();
            this.lbx_ElevatorList = new System.Windows.Forms.ListBox();
            this.btn_ViewMap = new System.Windows.Forms.Button();
            this.txt_Contractor = new System.Windows.Forms.TextBox();
            this.lbl_Contractor = new System.Windows.Forms.Label();
            this.lbl_Anniversary = new System.Windows.Forms.Label();
            this.txt_HourlyFee = new System.Windows.Forms.TextBox();
            this.lbl_HourlyFee = new System.Windows.Forms.Label();
            this.txt_FirmFee = new System.Windows.Forms.TextBox();
            this.lbl_FirmFee = new System.Windows.Forms.Label();
            this.lbl_BuildingCounty = new System.Windows.Forms.Label();
            this.lbl_RelatedDocs = new System.Windows.Forms.Label();
            this.txt_BuildingName = new System.Windows.Forms.TextBox();
            this.lbl_BuildingName = new System.Windows.Forms.Label();
            this.cbx_BuildingActive = new System.Windows.Forms.CheckBox();
            this.lbl_BuildingAddress = new System.Windows.Forms.Label();
            this.txt_BuildingZip = new System.Windows.Forms.TextBox();
            this.txt_BuildingAddress = new System.Windows.Forms.TextBox();
            this.txt_BuildingState = new System.Windows.Forms.TextBox();
            this.txt_BuildingCity = new System.Windows.Forms.TextBox();
            this.gbx_Company = new System.Windows.Forms.GroupBox();
            this.btn_EditCompany = new System.Windows.Forms.Button();
            this.txt_CompanyName = new System.Windows.Forms.TextBox();
            this.lbl_OtherBuildings = new System.Windows.Forms.Label();
            this.lbl_CompanyName = new System.Windows.Forms.Label();
            this.lbx_OtherCompanyBuildings = new System.Windows.Forms.ListBox();
            this.lbl_CompanyAddress = new System.Windows.Forms.Label();
            this.txt_CompanyCity = new System.Windows.Forms.TextBox();
            this.txt_CompanyZip = new System.Windows.Forms.TextBox();
            this.txt_CompanyState = new System.Windows.Forms.TextBox();
            this.txt_CompanyStreet = new System.Windows.Forms.TextBox();
            this.tab_BuildingCompanySelector = new System.Windows.Forms.TabControl();
            this.tab_ByCompany = new System.Windows.Forms.TabPage();
            this.lbx_CompanyList = new System.Windows.Forms.ListBox();
            this.txt_FilterCompany = new System.Windows.Forms.TextBox();
            this.tab_ByBuilding = new System.Windows.Forms.TabPage();
            this.lbx_BuildingList = new System.Windows.Forms.ListBox();
            this.txt_FilterAddress = new System.Windows.Forms.TextBox();
            this.gbx_ResultFilters = new System.Windows.Forms.GroupBox();
            this.cbx_ShowInactive = new System.Windows.Forms.CheckBox();
            this.cbx_ShowDC = new System.Windows.Forms.CheckBox();
            this.cbx_ShowMD = new System.Windows.Forms.CheckBox();
            this.tab_MainTabControl = new System.Windows.Forms.TabControl();
            this.tab_DatabaseBrowser = new System.Windows.Forms.TabPage();
            this.gbx_ButtonContainer = new System.Windows.Forms.GroupBox();
            this.btn_NewBuilding = new System.Windows.Forms.Button();
            this.btn_AddNewCompany = new System.Windows.Forms.Button();
            this.gbx_Contacts = new System.Windows.Forms.GroupBox();
            this.gbx_ContactInfo = new System.Windows.Forms.GroupBox();
            this.btn_EditContact = new System.Windows.Forms.Button();
            this.txt_Fax = new System.Windows.Forms.TextBox();
            this.txt_CellPhone = new System.Windows.Forms.TextBox();
            this.txt_OfficePhone = new System.Windows.Forms.TextBox();
            this.txt_Email = new System.Windows.Forms.TextBox();
            this.lbl_ContactEmail = new System.Windows.Forms.Label();
            this.lbl_ContactFax = new System.Windows.Forms.Label();
            this.lbl_ContactCellPhone = new System.Windows.Forms.Label();
            this.lbl_ContactOfficePhone = new System.Windows.Forms.Label();
            this.lbl_ContactName = new System.Windows.Forms.Label();
            this.txt_ContactName = new System.Windows.Forms.TextBox();
            this.lbl_BuildingContacts = new System.Windows.Forms.Label();
            this.lbx_BuildingContacts = new System.Windows.Forms.ListBox();
            this.lbl_CompanyContacts = new System.Windows.Forms.Label();
            this.lbx_CompanyContacts = new System.Windows.Forms.ListBox();
            this.tab_UpcomingAndOverdue = new System.Windows.Forms.TabPage();
            this.gbx_ContactLog = new System.Windows.Forms.GroupBox();
            this.groupBox6 = new System.Windows.Forms.GroupBox();
            this.listView1 = new System.Windows.Forms.ListView();
            this.columnHeader1 = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.columnHeader2 = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.columnHeader3 = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.columnHeader4 = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.columnHeader5 = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.tlp_UpcomingAndOverdue = new System.Windows.Forms.TableLayoutPanel();
            this.groupBox2 = new System.Windows.Forms.GroupBox();
            this.groupBox3 = new System.Windows.Forms.GroupBox();
            this.groupBox4 = new System.Windows.Forms.GroupBox();
            this.groupBox5 = new System.Windows.Forms.GroupBox();
            this.textBox1 = new System.Windows.Forms.TextBox();
            this.textBox2 = new System.Windows.Forms.TextBox();
            this.textBox3 = new System.Windows.Forms.TextBox();
            this.textBox4 = new System.Windows.Forms.TextBox();
            this.label1 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.label4 = new System.Windows.Forms.Label();
            this.label5 = new System.Windows.Forms.Label();
            this.textBox5 = new System.Windows.Forms.TextBox();
            this.label6 = new System.Windows.Forms.Label();
            this.listBox1 = new System.Windows.Forms.ListBox();
            this.label7 = new System.Windows.Forms.Label();
            this.listBox2 = new System.Windows.Forms.ListBox();
            this.cmu_Contact = new System.Windows.Forms.ContextMenuStrip(this.components);
            this.cmi_AddContact = new System.Windows.Forms.ToolStripMenuItem();
            this.cmi_RemoveContact = new System.Windows.Forms.ToolStripMenuItem();
            this.mnuMainMenuStrip.SuspendLayout();
            this.gbx_InspectionHistory.SuspendLayout();
            this.gbx_Building.SuspendLayout();
            this.gbx_Company.SuspendLayout();
            this.tab_BuildingCompanySelector.SuspendLayout();
            this.tab_ByCompany.SuspendLayout();
            this.tab_ByBuilding.SuspendLayout();
            this.gbx_ResultFilters.SuspendLayout();
            this.tab_MainTabControl.SuspendLayout();
            this.tab_DatabaseBrowser.SuspendLayout();
            this.gbx_ButtonContainer.SuspendLayout();
            this.gbx_Contacts.SuspendLayout();
            this.gbx_ContactInfo.SuspendLayout();
            this.tab_UpcomingAndOverdue.SuspendLayout();
            this.groupBox6.SuspendLayout();
            this.tlp_UpcomingAndOverdue.SuspendLayout();
            this.groupBox4.SuspendLayout();
            this.groupBox5.SuspendLayout();
            this.cmu_Contact.SuspendLayout();
            this.SuspendLayout();
            // 
            // mnuMainMenuStrip
            // 
            this.mnuMainMenuStrip.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.fileToolStripMenuItem,
            this.settingsToolStripMenuItem,
            this.testMethodToolStripMenuItem});
            this.mnuMainMenuStrip.Location = new System.Drawing.Point(0, 0);
            this.mnuMainMenuStrip.Name = "mnuMainMenuStrip";
            this.mnuMainMenuStrip.Size = new System.Drawing.Size(1664, 24);
            this.mnuMainMenuStrip.TabIndex = 0;
            this.mnuMainMenuStrip.Text = "menuStrip1";
            // 
            // fileToolStripMenuItem
            // 
            this.fileToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.forceBackupToolStripMenuItem,
            this.exitToolStripMenuItem});
            this.fileToolStripMenuItem.Name = "fileToolStripMenuItem";
            this.fileToolStripMenuItem.Size = new System.Drawing.Size(37, 20);
            this.fileToolStripMenuItem.Text = "&File";
            // 
            // forceBackupToolStripMenuItem
            // 
            this.forceBackupToolStripMenuItem.Name = "forceBackupToolStripMenuItem";
            this.forceBackupToolStripMenuItem.Size = new System.Drawing.Size(146, 22);
            this.forceBackupToolStripMenuItem.Text = "Force &Backup";
            // 
            // exitToolStripMenuItem
            // 
            this.exitToolStripMenuItem.Name = "exitToolStripMenuItem";
            this.exitToolStripMenuItem.Size = new System.Drawing.Size(146, 22);
            this.exitToolStripMenuItem.Text = "E&xit";
            this.exitToolStripMenuItem.Click += new System.EventHandler(this.ExitToolStripMenuItem_Click);
            // 
            // settingsToolStripMenuItem
            // 
            this.settingsToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.connectionsToolStripMenuItem,
            this.preferencesToolStripMenuItem});
            this.settingsToolStripMenuItem.Name = "settingsToolStripMenuItem";
            this.settingsToolStripMenuItem.Size = new System.Drawing.Size(60, 20);
            this.settingsToolStripMenuItem.Text = "&Settings";
            // 
            // connectionsToolStripMenuItem
            // 
            this.connectionsToolStripMenuItem.Name = "connectionsToolStripMenuItem";
            this.connectionsToolStripMenuItem.Size = new System.Drawing.Size(140, 22);
            this.connectionsToolStripMenuItem.Text = "C&onnections";
            this.connectionsToolStripMenuItem.Click += new System.EventHandler(this.OpenConnectionSettingsForm);
            // 
            // preferencesToolStripMenuItem
            // 
            this.preferencesToolStripMenuItem.Name = "preferencesToolStripMenuItem";
            this.preferencesToolStripMenuItem.Size = new System.Drawing.Size(140, 22);
            this.preferencesToolStripMenuItem.Text = "&Preferences";
            // 
            // testMethodToolStripMenuItem
            // 
            this.testMethodToolStripMenuItem.Name = "testMethodToolStripMenuItem";
            this.testMethodToolStripMenuItem.Size = new System.Drawing.Size(12, 20);
            // 
            // gbx_InspectionHistory
            // 
            this.gbx_InspectionHistory.Controls.Add(this.btn_EnterNewInspection);
            this.gbx_InspectionHistory.Controls.Add(this.lvw_InspectionList);
            this.gbx_InspectionHistory.Location = new System.Drawing.Point(248, 716);
            this.gbx_InspectionHistory.Name = "gbx_InspectionHistory";
            this.gbx_InspectionHistory.Size = new System.Drawing.Size(574, 170);
            this.gbx_InspectionHistory.TabIndex = 2;
            this.gbx_InspectionHistory.TabStop = false;
            this.gbx_InspectionHistory.Text = "Inspection History";
            // 
            // btn_EnterNewInspection
            // 
            this.btn_EnterNewInspection.Location = new System.Drawing.Point(485, 24);
            this.btn_EnterNewInspection.Name = "btn_EnterNewInspection";
            this.btn_EnterNewInspection.Size = new System.Drawing.Size(75, 129);
            this.btn_EnterNewInspection.TabIndex = 16;
            this.btn_EnterNewInspection.Text = "Enter New Inspection";
            this.btn_EnterNewInspection.UseVisualStyleBackColor = true;
            this.btn_EnterNewInspection.Click += new System.EventHandler(this.OpenChildForm);
            // 
            // lvw_InspectionList
            // 
            this.lvw_InspectionList.Columns.AddRange(new System.Windows.Forms.ColumnHeader[] {
            this.col_Date,
            this.col_InspectionType,
            this.col_Status,
            this.col_Inspector,
            this.col_Report});
            this.lvw_InspectionList.FullRowSelect = true;
            this.lvw_InspectionList.Location = new System.Drawing.Point(14, 24);
            this.lvw_InspectionList.MultiSelect = false;
            this.lvw_InspectionList.Name = "lvw_InspectionList";
            this.lvw_InspectionList.Size = new System.Drawing.Size(458, 129);
            this.lvw_InspectionList.TabIndex = 15;
            this.lvw_InspectionList.UseCompatibleStateImageBehavior = false;
            this.lvw_InspectionList.View = System.Windows.Forms.View.Details;
            this.lvw_InspectionList.MouseClick += new System.Windows.Forms.MouseEventHandler(this.Inspection_RightClick);
            // 
            // col_Date
            // 
            this.col_Date.Text = "Date";
            this.col_Date.Width = 70;
            // 
            // col_InspectionType
            // 
            this.col_InspectionType.Text = "Inspection Type";
            this.col_InspectionType.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.col_InspectionType.Width = 100;
            // 
            // col_Status
            // 
            this.col_Status.Text = "Status";
            this.col_Status.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.col_Status.Width = 100;
            // 
            // col_Inspector
            // 
            this.col_Inspector.Text = "Inspector";
            this.col_Inspector.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.col_Inspector.Width = 80;
            // 
            // col_Report
            // 
            this.col_Report.Text = "Report Available";
            this.col_Report.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.col_Report.Width = 100;
            // 
            // gbx_Building
            // 
            this.gbx_Building.Controls.Add(this.btn_EditBuilding);
            this.gbx_Building.Controls.Add(this.cbo_BuildingAnniversary);
            this.gbx_Building.Controls.Add(this.cbo_BuildingCounty);
            this.gbx_Building.Controls.Add(this.lvw_RelatedDocuments);
            this.gbx_Building.Controls.Add(this.btn_AddBldgDocument);
            this.gbx_Building.Controls.Add(this.lbx_ElevatorList);
            this.gbx_Building.Controls.Add(this.btn_ViewMap);
            this.gbx_Building.Controls.Add(this.txt_Contractor);
            this.gbx_Building.Controls.Add(this.lbl_Contractor);
            this.gbx_Building.Controls.Add(this.lbl_Anniversary);
            this.gbx_Building.Controls.Add(this.txt_HourlyFee);
            this.gbx_Building.Controls.Add(this.lbl_HourlyFee);
            this.gbx_Building.Controls.Add(this.txt_FirmFee);
            this.gbx_Building.Controls.Add(this.lbl_FirmFee);
            this.gbx_Building.Controls.Add(this.lbl_BuildingCounty);
            this.gbx_Building.Controls.Add(this.lbl_RelatedDocs);
            this.gbx_Building.Controls.Add(this.txt_BuildingName);
            this.gbx_Building.Controls.Add(this.lbl_BuildingName);
            this.gbx_Building.Controls.Add(this.cbx_BuildingActive);
            this.gbx_Building.Controls.Add(this.lbl_BuildingAddress);
            this.gbx_Building.Controls.Add(this.txt_BuildingZip);
            this.gbx_Building.Controls.Add(this.txt_BuildingAddress);
            this.gbx_Building.Controls.Add(this.txt_BuildingState);
            this.gbx_Building.Controls.Add(this.txt_BuildingCity);
            this.gbx_Building.Location = new System.Drawing.Point(248, 216);
            this.gbx_Building.Name = "gbx_Building";
            this.gbx_Building.Size = new System.Drawing.Size(574, 230);
            this.gbx_Building.TabIndex = 7;
            this.gbx_Building.TabStop = false;
            this.gbx_Building.Text = "Building";
            // 
            // btn_EditBuilding
            // 
            this.btn_EditBuilding.Location = new System.Drawing.Point(236, 19);
            this.btn_EditBuilding.Name = "btn_EditBuilding";
            this.btn_EditBuilding.Size = new System.Drawing.Size(56, 20);
            this.btn_EditBuilding.TabIndex = 29;
            this.btn_EditBuilding.Text = "Edit";
            this.btn_EditBuilding.UseVisualStyleBackColor = true;
            this.btn_EditBuilding.Click += new System.EventHandler(this.EnableEditing);
            // 
            // cbo_BuildingAnniversary
            // 
            this.cbo_BuildingAnniversary.BackColor = System.Drawing.SystemColors.Control;
            this.cbo_BuildingAnniversary.Enabled = false;
            this.cbo_BuildingAnniversary.FormattingEnabled = true;
            this.cbo_BuildingAnniversary.Items.AddRange(new object[] {
            "January",
            "February",
            "March",
            "April",
            "May",
            "June",
            "July",
            "August",
            "September",
            "October",
            "November",
            "December"});
            this.cbo_BuildingAnniversary.Location = new System.Drawing.Point(247, 144);
            this.cbo_BuildingAnniversary.Name = "cbo_BuildingAnniversary";
            this.cbo_BuildingAnniversary.Size = new System.Drawing.Size(115, 21);
            this.cbo_BuildingAnniversary.TabIndex = 28;
            // 
            // cbo_BuildingCounty
            // 
            this.cbo_BuildingCounty.BackColor = System.Drawing.SystemColors.Control;
            this.cbo_BuildingCounty.Enabled = false;
            this.cbo_BuildingCounty.FormattingEnabled = true;
            this.cbo_BuildingCounty.Items.AddRange(new object[] {
            "Allegany",
            "Anne Arundel",
            "Baltimore",
            "Baltimore City",
            "Calvert",
            "Caroline",
            "Carroll",
            "Cecil",
            "Charles",
            "Dorchester",
            "Frederick",
            "Garrett",
            "Harford",
            "Howard",
            "Kent",
            "Montgomery",
            "Prince George\'s",
            "Queen Anne\'s",
            "Saint Mary\'s",
            "Somerset",
            "Talbot",
            "Washington",
            "Washington D.C.",
            "Wicomico",
            "Worcester"});
            this.cbo_BuildingCounty.Location = new System.Drawing.Point(59, 109);
            this.cbo_BuildingCounty.Name = "cbo_BuildingCounty";
            this.cbo_BuildingCounty.Size = new System.Drawing.Size(113, 21);
            this.cbo_BuildingCounty.TabIndex = 27;
            // 
            // lvw_RelatedDocuments
            // 
            this.lvw_RelatedDocuments.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lvw_RelatedDocuments.Columns.AddRange(new System.Windows.Forms.ColumnHeader[] {
            this.col_Title,
            this.col_Desc});
            this.lvw_RelatedDocuments.Enabled = false;
            this.lvw_RelatedDocuments.Location = new System.Drawing.Point(302, 38);
            this.lvw_RelatedDocuments.Name = "lvw_RelatedDocuments";
            this.lvw_RelatedDocuments.Size = new System.Drawing.Size(266, 87);
            this.lvw_RelatedDocuments.TabIndex = 26;
            this.lvw_RelatedDocuments.UseCompatibleStateImageBehavior = false;
            this.lvw_RelatedDocuments.View = System.Windows.Forms.View.Details;
            // 
            // col_Title
            // 
            this.col_Title.Text = "Title";
            this.col_Title.Width = 100;
            // 
            // col_Desc
            // 
            this.col_Desc.Text = "Description";
            this.col_Desc.Width = 150;
            // 
            // btn_AddBldgDocument
            // 
            this.btn_AddBldgDocument.Enabled = false;
            this.btn_AddBldgDocument.Location = new System.Drawing.Point(479, 15);
            this.btn_AddBldgDocument.Name = "btn_AddBldgDocument";
            this.btn_AddBldgDocument.Size = new System.Drawing.Size(89, 20);
            this.btn_AddBldgDocument.TabIndex = 25;
            this.btn_AddBldgDocument.Text = "Add Document";
            this.btn_AddBldgDocument.UseVisualStyleBackColor = true;
            // 
            // lbx_ElevatorList
            // 
            this.lbx_ElevatorList.FormattingEnabled = true;
            this.lbx_ElevatorList.Location = new System.Drawing.Point(386, 134);
            this.lbx_ElevatorList.Name = "lbx_ElevatorList";
            this.lbx_ElevatorList.Size = new System.Drawing.Size(182, 82);
            this.lbx_ElevatorList.TabIndex = 7;
            // 
            // btn_ViewMap
            // 
            this.btn_ViewMap.Enabled = false;
            this.btn_ViewMap.Location = new System.Drawing.Point(178, 107);
            this.btn_ViewMap.Name = "btn_ViewMap";
            this.btn_ViewMap.Size = new System.Drawing.Size(75, 23);
            this.btn_ViewMap.TabIndex = 7;
            this.btn_ViewMap.Text = "View Map";
            this.btn_ViewMap.UseVisualStyleBackColor = true;
            // 
            // txt_Contractor
            // 
            this.txt_Contractor.Location = new System.Drawing.Point(246, 170);
            this.txt_Contractor.Name = "txt_Contractor";
            this.txt_Contractor.ReadOnly = true;
            this.txt_Contractor.Size = new System.Drawing.Size(116, 20);
            this.txt_Contractor.TabIndex = 24;
            // 
            // lbl_Contractor
            // 
            this.lbl_Contractor.AutoSize = true;
            this.lbl_Contractor.Location = new System.Drawing.Point(181, 173);
            this.lbl_Contractor.Name = "lbl_Contractor";
            this.lbl_Contractor.Size = new System.Drawing.Size(59, 13);
            this.lbl_Contractor.TabIndex = 23;
            this.lbl_Contractor.Text = "Contractor:";
            // 
            // lbl_Anniversary
            // 
            this.lbl_Anniversary.AutoSize = true;
            this.lbl_Anniversary.Location = new System.Drawing.Point(175, 147);
            this.lbl_Anniversary.Name = "lbl_Anniversary";
            this.lbl_Anniversary.Size = new System.Drawing.Size(65, 13);
            this.lbl_Anniversary.TabIndex = 21;
            this.lbl_Anniversary.Text = "Anniversary:";
            // 
            // txt_HourlyFee
            // 
            this.txt_HourlyFee.Location = new System.Drawing.Point(60, 170);
            this.txt_HourlyFee.Name = "txt_HourlyFee";
            this.txt_HourlyFee.ReadOnly = true;
            this.txt_HourlyFee.Size = new System.Drawing.Size(79, 20);
            this.txt_HourlyFee.TabIndex = 20;
            // 
            // lbl_HourlyFee
            // 
            this.lbl_HourlyFee.AutoSize = true;
            this.lbl_HourlyFee.Location = new System.Drawing.Point(11, 173);
            this.lbl_HourlyFee.Name = "lbl_HourlyFee";
            this.lbl_HourlyFee.Size = new System.Drawing.Size(40, 13);
            this.lbl_HourlyFee.TabIndex = 19;
            this.lbl_HourlyFee.Text = "Hourly:";
            // 
            // txt_FirmFee
            // 
            this.txt_FirmFee.Location = new System.Drawing.Point(59, 144);
            this.txt_FirmFee.Name = "txt_FirmFee";
            this.txt_FirmFee.ReadOnly = true;
            this.txt_FirmFee.Size = new System.Drawing.Size(79, 20);
            this.txt_FirmFee.TabIndex = 16;
            // 
            // lbl_FirmFee
            // 
            this.lbl_FirmFee.AutoSize = true;
            this.lbl_FirmFee.Location = new System.Drawing.Point(10, 147);
            this.lbl_FirmFee.Name = "lbl_FirmFee";
            this.lbl_FirmFee.Size = new System.Drawing.Size(29, 13);
            this.lbl_FirmFee.TabIndex = 15;
            this.lbl_FirmFee.Text = "Firm:";
            // 
            // lbl_BuildingCounty
            // 
            this.lbl_BuildingCounty.AutoSize = true;
            this.lbl_BuildingCounty.Location = new System.Drawing.Point(10, 112);
            this.lbl_BuildingCounty.Name = "lbl_BuildingCounty";
            this.lbl_BuildingCounty.Size = new System.Drawing.Size(43, 13);
            this.lbl_BuildingCounty.TabIndex = 7;
            this.lbl_BuildingCounty.Text = "County:";
            // 
            // lbl_RelatedDocs
            // 
            this.lbl_RelatedDocs.AutoSize = true;
            this.lbl_RelatedDocs.Location = new System.Drawing.Point(299, 22);
            this.lbl_RelatedDocs.Name = "lbl_RelatedDocs";
            this.lbl_RelatedDocs.Size = new System.Drawing.Size(101, 13);
            this.lbl_RelatedDocs.TabIndex = 13;
            this.lbl_RelatedDocs.Text = "Related Documents";
            // 
            // txt_BuildingName
            // 
            this.txt_BuildingName.Location = new System.Drawing.Point(59, 19);
            this.txt_BuildingName.Name = "txt_BuildingName";
            this.txt_BuildingName.ReadOnly = true;
            this.txt_BuildingName.Size = new System.Drawing.Size(171, 20);
            this.txt_BuildingName.TabIndex = 6;
            // 
            // lbl_BuildingName
            // 
            this.lbl_BuildingName.AutoSize = true;
            this.lbl_BuildingName.Location = new System.Drawing.Point(15, 22);
            this.lbl_BuildingName.Name = "lbl_BuildingName";
            this.lbl_BuildingName.Size = new System.Drawing.Size(38, 13);
            this.lbl_BuildingName.TabIndex = 6;
            this.lbl_BuildingName.Text = "Name:";
            // 
            // cbx_BuildingActive
            // 
            this.cbx_BuildingActive.AutoSize = true;
            this.cbx_BuildingActive.Enabled = false;
            this.cbx_BuildingActive.Location = new System.Drawing.Point(240, 73);
            this.cbx_BuildingActive.Name = "cbx_BuildingActive";
            this.cbx_BuildingActive.Size = new System.Drawing.Size(56, 17);
            this.cbx_BuildingActive.TabIndex = 12;
            this.cbx_BuildingActive.Text = "Active";
            this.cbx_BuildingActive.UseVisualStyleBackColor = true;
            // 
            // lbl_BuildingAddress
            // 
            this.lbl_BuildingAddress.AutoSize = true;
            this.lbl_BuildingAddress.Location = new System.Drawing.Point(5, 48);
            this.lbl_BuildingAddress.Name = "lbl_BuildingAddress";
            this.lbl_BuildingAddress.Size = new System.Drawing.Size(48, 13);
            this.lbl_BuildingAddress.TabIndex = 7;
            this.lbl_BuildingAddress.Text = "Address:";
            // 
            // txt_BuildingZip
            // 
            this.txt_BuildingZip.Location = new System.Drawing.Point(178, 71);
            this.txt_BuildingZip.Name = "txt_BuildingZip";
            this.txt_BuildingZip.ReadOnly = true;
            this.txt_BuildingZip.Size = new System.Drawing.Size(52, 20);
            this.txt_BuildingZip.TabIndex = 11;
            // 
            // txt_BuildingAddress
            // 
            this.txt_BuildingAddress.Location = new System.Drawing.Point(59, 45);
            this.txt_BuildingAddress.Name = "txt_BuildingAddress";
            this.txt_BuildingAddress.ReadOnly = true;
            this.txt_BuildingAddress.Size = new System.Drawing.Size(171, 20);
            this.txt_BuildingAddress.TabIndex = 8;
            // 
            // txt_BuildingState
            // 
            this.txt_BuildingState.Location = new System.Drawing.Point(145, 71);
            this.txt_BuildingState.Name = "txt_BuildingState";
            this.txt_BuildingState.ReadOnly = true;
            this.txt_BuildingState.Size = new System.Drawing.Size(27, 20);
            this.txt_BuildingState.TabIndex = 10;
            // 
            // txt_BuildingCity
            // 
            this.txt_BuildingCity.Location = new System.Drawing.Point(59, 71);
            this.txt_BuildingCity.Name = "txt_BuildingCity";
            this.txt_BuildingCity.ReadOnly = true;
            this.txt_BuildingCity.Size = new System.Drawing.Size(80, 20);
            this.txt_BuildingCity.TabIndex = 9;
            // 
            // gbx_Company
            // 
            this.gbx_Company.Controls.Add(this.btn_EditCompany);
            this.gbx_Company.Controls.Add(this.txt_CompanyName);
            this.gbx_Company.Controls.Add(this.lbl_OtherBuildings);
            this.gbx_Company.Controls.Add(this.lbl_CompanyName);
            this.gbx_Company.Controls.Add(this.lbx_OtherCompanyBuildings);
            this.gbx_Company.Controls.Add(this.lbl_CompanyAddress);
            this.gbx_Company.Controls.Add(this.txt_CompanyCity);
            this.gbx_Company.Controls.Add(this.txt_CompanyZip);
            this.gbx_Company.Controls.Add(this.txt_CompanyState);
            this.gbx_Company.Controls.Add(this.txt_CompanyStreet);
            this.gbx_Company.Location = new System.Drawing.Point(248, 92);
            this.gbx_Company.Name = "gbx_Company";
            this.gbx_Company.Size = new System.Drawing.Size(574, 118);
            this.gbx_Company.TabIndex = 6;
            this.gbx_Company.TabStop = false;
            this.gbx_Company.Text = "Company";
            // 
            // btn_EditCompany
            // 
            this.btn_EditCompany.Location = new System.Drawing.Point(236, 19);
            this.btn_EditCompany.Name = "btn_EditCompany";
            this.btn_EditCompany.Size = new System.Drawing.Size(56, 20);
            this.btn_EditCompany.TabIndex = 9;
            this.btn_EditCompany.Text = "Edit";
            this.btn_EditCompany.UseVisualStyleBackColor = true;
            this.btn_EditCompany.Click += new System.EventHandler(this.EnableEditing);
            // 
            // txt_CompanyName
            // 
            this.txt_CompanyName.Location = new System.Drawing.Point(59, 19);
            this.txt_CompanyName.Name = "txt_CompanyName";
            this.txt_CompanyName.ReadOnly = true;
            this.txt_CompanyName.Size = new System.Drawing.Size(171, 20);
            this.txt_CompanyName.TabIndex = 14;
            // 
            // lbl_OtherBuildings
            // 
            this.lbl_OtherBuildings.AutoSize = true;
            this.lbl_OtherBuildings.Location = new System.Drawing.Point(299, 14);
            this.lbl_OtherBuildings.Name = "lbl_OtherBuildings";
            this.lbl_OtherBuildings.Size = new System.Drawing.Size(157, 13);
            this.lbl_OtherBuildings.TabIndex = 13;
            this.lbl_OtherBuildings.Text = "Other Buildings Under Company";
            // 
            // lbl_CompanyName
            // 
            this.lbl_CompanyName.AutoSize = true;
            this.lbl_CompanyName.Location = new System.Drawing.Point(15, 22);
            this.lbl_CompanyName.Name = "lbl_CompanyName";
            this.lbl_CompanyName.Size = new System.Drawing.Size(38, 13);
            this.lbl_CompanyName.TabIndex = 15;
            this.lbl_CompanyName.Text = "Name:";
            // 
            // lbx_OtherCompanyBuildings
            // 
            this.lbx_OtherCompanyBuildings.FormattingEnabled = true;
            this.lbx_OtherCompanyBuildings.Location = new System.Drawing.Point(302, 30);
            this.lbx_OtherCompanyBuildings.Name = "lbx_OtherCompanyBuildings";
            this.lbx_OtherCompanyBuildings.Size = new System.Drawing.Size(266, 82);
            this.lbx_OtherCompanyBuildings.TabIndex = 7;
            this.lbx_OtherCompanyBuildings.SelectedIndexChanged += new System.EventHandler(this.ListBox_ItemSelected);
            // 
            // lbl_CompanyAddress
            // 
            this.lbl_CompanyAddress.AutoSize = true;
            this.lbl_CompanyAddress.Location = new System.Drawing.Point(5, 48);
            this.lbl_CompanyAddress.Name = "lbl_CompanyAddress";
            this.lbl_CompanyAddress.Size = new System.Drawing.Size(48, 13);
            this.lbl_CompanyAddress.TabIndex = 16;
            this.lbl_CompanyAddress.Text = "Address:";
            // 
            // txt_CompanyCity
            // 
            this.txt_CompanyCity.Location = new System.Drawing.Point(59, 71);
            this.txt_CompanyCity.Name = "txt_CompanyCity";
            this.txt_CompanyCity.ReadOnly = true;
            this.txt_CompanyCity.Size = new System.Drawing.Size(80, 20);
            this.txt_CompanyCity.TabIndex = 18;
            // 
            // txt_CompanyZip
            // 
            this.txt_CompanyZip.Location = new System.Drawing.Point(178, 71);
            this.txt_CompanyZip.Name = "txt_CompanyZip";
            this.txt_CompanyZip.ReadOnly = true;
            this.txt_CompanyZip.Size = new System.Drawing.Size(52, 20);
            this.txt_CompanyZip.TabIndex = 20;
            // 
            // txt_CompanyState
            // 
            this.txt_CompanyState.Location = new System.Drawing.Point(145, 71);
            this.txt_CompanyState.Name = "txt_CompanyState";
            this.txt_CompanyState.ReadOnly = true;
            this.txt_CompanyState.Size = new System.Drawing.Size(27, 20);
            this.txt_CompanyState.TabIndex = 19;
            // 
            // txt_CompanyStreet
            // 
            this.txt_CompanyStreet.Location = new System.Drawing.Point(59, 45);
            this.txt_CompanyStreet.Name = "txt_CompanyStreet";
            this.txt_CompanyStreet.ReadOnly = true;
            this.txt_CompanyStreet.Size = new System.Drawing.Size(171, 20);
            this.txt_CompanyStreet.TabIndex = 17;
            // 
            // tab_BuildingCompanySelector
            // 
            this.tab_BuildingCompanySelector.Controls.Add(this.tab_ByCompany);
            this.tab_BuildingCompanySelector.Controls.Add(this.tab_ByBuilding);
            this.tab_BuildingCompanySelector.HotTrack = true;
            this.tab_BuildingCompanySelector.Location = new System.Drawing.Point(6, 6);
            this.tab_BuildingCompanySelector.Name = "tab_BuildingCompanySelector";
            this.tab_BuildingCompanySelector.SelectedIndex = 0;
            this.tab_BuildingCompanySelector.Size = new System.Drawing.Size(229, 880);
            this.tab_BuildingCompanySelector.TabIndex = 3;
            this.tab_BuildingCompanySelector.SelectedIndexChanged += new System.EventHandler(this.Filter_TextChanged);
            // 
            // tab_ByCompany
            // 
            this.tab_ByCompany.Controls.Add(this.lbx_CompanyList);
            this.tab_ByCompany.Controls.Add(this.txt_FilterCompany);
            this.tab_ByCompany.Location = new System.Drawing.Point(4, 22);
            this.tab_ByCompany.Name = "tab_ByCompany";
            this.tab_ByCompany.Padding = new System.Windows.Forms.Padding(3);
            this.tab_ByCompany.Size = new System.Drawing.Size(221, 854);
            this.tab_ByCompany.TabIndex = 0;
            this.tab_ByCompany.Text = "By Company";
            this.tab_ByCompany.UseVisualStyleBackColor = true;
            // 
            // lbx_CompanyList
            // 
            this.lbx_CompanyList.FormattingEnabled = true;
            this.lbx_CompanyList.Location = new System.Drawing.Point(6, 32);
            this.lbx_CompanyList.Name = "lbx_CompanyList";
            this.lbx_CompanyList.Size = new System.Drawing.Size(209, 810);
            this.lbx_CompanyList.Sorted = true;
            this.lbx_CompanyList.TabIndex = 1;
            this.lbx_CompanyList.SelectedIndexChanged += new System.EventHandler(this.ListBox_ItemSelected);
            // 
            // txt_FilterCompany
            // 
            this.txt_FilterCompany.Location = new System.Drawing.Point(6, 6);
            this.txt_FilterCompany.Name = "txt_FilterCompany";
            this.txt_FilterCompany.Size = new System.Drawing.Size(209, 20);
            this.txt_FilterCompany.TabIndex = 0;
            this.txt_FilterCompany.TextChanged += new System.EventHandler(this.Filter_TextChanged);
            // 
            // tab_ByBuilding
            // 
            this.tab_ByBuilding.Controls.Add(this.lbx_BuildingList);
            this.tab_ByBuilding.Controls.Add(this.txt_FilterAddress);
            this.tab_ByBuilding.Location = new System.Drawing.Point(4, 22);
            this.tab_ByBuilding.Name = "tab_ByBuilding";
            this.tab_ByBuilding.Padding = new System.Windows.Forms.Padding(3);
            this.tab_ByBuilding.Size = new System.Drawing.Size(221, 854);
            this.tab_ByBuilding.TabIndex = 1;
            this.tab_ByBuilding.Text = "By Address";
            this.tab_ByBuilding.UseVisualStyleBackColor = true;
            // 
            // lbx_BuildingList
            // 
            this.lbx_BuildingList.FormattingEnabled = true;
            this.lbx_BuildingList.Location = new System.Drawing.Point(6, 32);
            this.lbx_BuildingList.Name = "lbx_BuildingList";
            this.lbx_BuildingList.Size = new System.Drawing.Size(209, 810);
            this.lbx_BuildingList.Sorted = true;
            this.lbx_BuildingList.TabIndex = 1;
            this.lbx_BuildingList.SelectedIndexChanged += new System.EventHandler(this.ListBox_ItemSelected);
            // 
            // txt_FilterAddress
            // 
            this.txt_FilterAddress.Location = new System.Drawing.Point(6, 6);
            this.txt_FilterAddress.Name = "txt_FilterAddress";
            this.txt_FilterAddress.Size = new System.Drawing.Size(209, 20);
            this.txt_FilterAddress.TabIndex = 0;
            this.txt_FilterAddress.TextChanged += new System.EventHandler(this.Filter_TextChanged);
            // 
            // gbx_ResultFilters
            // 
            this.gbx_ResultFilters.Controls.Add(this.cbx_ShowInactive);
            this.gbx_ResultFilters.Controls.Add(this.cbx_ShowDC);
            this.gbx_ResultFilters.Controls.Add(this.cbx_ShowMD);
            this.gbx_ResultFilters.Location = new System.Drawing.Point(12, 27);
            this.gbx_ResultFilters.Name = "gbx_ResultFilters";
            this.gbx_ResultFilters.Size = new System.Drawing.Size(391, 40);
            this.gbx_ResultFilters.TabIndex = 2;
            this.gbx_ResultFilters.TabStop = false;
            this.gbx_ResultFilters.Text = "Filters";
            // 
            // cbx_ShowInactive
            // 
            this.cbx_ShowInactive.AutoSize = true;
            this.cbx_ShowInactive.Location = new System.Drawing.Point(252, 18);
            this.cbx_ShowInactive.Name = "cbx_ShowInactive";
            this.cbx_ShowInactive.Size = new System.Drawing.Size(99, 17);
            this.cbx_ShowInactive.TabIndex = 2;
            this.cbx_ShowInactive.Text = "Show Inactives";
            this.cbx_ShowInactive.UseVisualStyleBackColor = true;
            this.cbx_ShowInactive.CheckedChanged += new System.EventHandler(this.FilterChanged);
            // 
            // cbx_ShowDC
            // 
            this.cbx_ShowDC.AutoSize = true;
            this.cbx_ShowDC.Location = new System.Drawing.Point(130, 19);
            this.cbx_ShowDC.Name = "cbx_ShowDC";
            this.cbx_ShowDC.Size = new System.Drawing.Size(116, 17);
            this.cbx_ShowDC.TabIndex = 1;
            this.cbx_ShowDC.Text = "Show DC Buildings";
            this.cbx_ShowDC.UseVisualStyleBackColor = true;
            this.cbx_ShowDC.CheckedChanged += new System.EventHandler(this.FilterChanged);
            // 
            // cbx_ShowMD
            // 
            this.cbx_ShowMD.AutoSize = true;
            this.cbx_ShowMD.Location = new System.Drawing.Point(6, 19);
            this.cbx_ShowMD.Name = "cbx_ShowMD";
            this.cbx_ShowMD.Size = new System.Drawing.Size(118, 17);
            this.cbx_ShowMD.TabIndex = 0;
            this.cbx_ShowMD.Text = "Show MD Buildings";
            this.cbx_ShowMD.UseVisualStyleBackColor = true;
            this.cbx_ShowMD.CheckedChanged += new System.EventHandler(this.FilterChanged);
            // 
            // tab_MainTabControl
            // 
            this.tab_MainTabControl.Controls.Add(this.tab_DatabaseBrowser);
            this.tab_MainTabControl.Controls.Add(this.tab_UpcomingAndOverdue);
            this.tab_MainTabControl.Location = new System.Drawing.Point(12, 73);
            this.tab_MainTabControl.Name = "tab_MainTabControl";
            this.tab_MainTabControl.SelectedIndex = 0;
            this.tab_MainTabControl.Size = new System.Drawing.Size(887, 930);
            this.tab_MainTabControl.TabIndex = 8;
            // 
            // tab_DatabaseBrowser
            // 
            this.tab_DatabaseBrowser.Controls.Add(this.gbx_ButtonContainer);
            this.tab_DatabaseBrowser.Controls.Add(this.gbx_Contacts);
            this.tab_DatabaseBrowser.Controls.Add(this.gbx_InspectionHistory);
            this.tab_DatabaseBrowser.Controls.Add(this.gbx_Building);
            this.tab_DatabaseBrowser.Controls.Add(this.tab_BuildingCompanySelector);
            this.tab_DatabaseBrowser.Controls.Add(this.gbx_Company);
            this.tab_DatabaseBrowser.Location = new System.Drawing.Point(4, 22);
            this.tab_DatabaseBrowser.Name = "tab_DatabaseBrowser";
            this.tab_DatabaseBrowser.Padding = new System.Windows.Forms.Padding(3);
            this.tab_DatabaseBrowser.Size = new System.Drawing.Size(879, 904);
            this.tab_DatabaseBrowser.TabIndex = 0;
            this.tab_DatabaseBrowser.Text = "Database Browser";
            this.tab_DatabaseBrowser.UseVisualStyleBackColor = true;
            // 
            // gbx_ButtonContainer
            // 
            this.gbx_ButtonContainer.Controls.Add(this.btn_NewBuilding);
            this.gbx_ButtonContainer.Controls.Add(this.btn_AddNewCompany);
            this.gbx_ButtonContainer.Location = new System.Drawing.Point(248, 11);
            this.gbx_ButtonContainer.Name = "gbx_ButtonContainer";
            this.gbx_ButtonContainer.Size = new System.Drawing.Size(574, 75);
            this.gbx_ButtonContainer.TabIndex = 9;
            this.gbx_ButtonContainer.TabStop = false;
            this.gbx_ButtonContainer.Text = "Database Operations";
            // 
            // btn_NewBuilding
            // 
            this.btn_NewBuilding.Location = new System.Drawing.Point(105, 19);
            this.btn_NewBuilding.Name = "btn_NewBuilding";
            this.btn_NewBuilding.Size = new System.Drawing.Size(93, 23);
            this.btn_NewBuilding.TabIndex = 10;
            this.btn_NewBuilding.Text = "New Building";
            this.btn_NewBuilding.UseVisualStyleBackColor = true;
            this.btn_NewBuilding.Click += new System.EventHandler(this.OpenChildForm);
            // 
            // btn_AddNewCompany
            // 
            this.btn_AddNewCompany.Location = new System.Drawing.Point(6, 19);
            this.btn_AddNewCompany.Name = "btn_AddNewCompany";
            this.btn_AddNewCompany.Size = new System.Drawing.Size(93, 23);
            this.btn_AddNewCompany.TabIndex = 9;
            this.btn_AddNewCompany.Text = "New Company";
            this.btn_AddNewCompany.UseVisualStyleBackColor = true;
            this.btn_AddNewCompany.Click += new System.EventHandler(this.OpenChildForm);
            // 
            // gbx_Contacts
            // 
            this.gbx_Contacts.Controls.Add(this.gbx_ContactInfo);
            this.gbx_Contacts.Controls.Add(this.lbl_BuildingContacts);
            this.gbx_Contacts.Controls.Add(this.lbx_BuildingContacts);
            this.gbx_Contacts.Controls.Add(this.lbl_CompanyContacts);
            this.gbx_Contacts.Controls.Add(this.lbx_CompanyContacts);
            this.gbx_Contacts.Location = new System.Drawing.Point(248, 533);
            this.gbx_Contacts.Name = "gbx_Contacts";
            this.gbx_Contacts.Size = new System.Drawing.Size(574, 177);
            this.gbx_Contacts.TabIndex = 9;
            this.gbx_Contacts.TabStop = false;
            this.gbx_Contacts.Text = "Contacts";
            // 
            // gbx_ContactInfo
            // 
            this.gbx_ContactInfo.Controls.Add(this.btn_EditContact);
            this.gbx_ContactInfo.Controls.Add(this.txt_Fax);
            this.gbx_ContactInfo.Controls.Add(this.txt_CellPhone);
            this.gbx_ContactInfo.Controls.Add(this.txt_OfficePhone);
            this.gbx_ContactInfo.Controls.Add(this.txt_Email);
            this.gbx_ContactInfo.Controls.Add(this.lbl_ContactEmail);
            this.gbx_ContactInfo.Controls.Add(this.lbl_ContactFax);
            this.gbx_ContactInfo.Controls.Add(this.lbl_ContactCellPhone);
            this.gbx_ContactInfo.Controls.Add(this.lbl_ContactOfficePhone);
            this.gbx_ContactInfo.Controls.Add(this.lbl_ContactName);
            this.gbx_ContactInfo.Controls.Add(this.txt_ContactName);
            this.gbx_ContactInfo.Location = new System.Drawing.Point(144, 16);
            this.gbx_ContactInfo.Name = "gbx_ContactInfo";
            this.gbx_ContactInfo.Size = new System.Drawing.Size(256, 153);
            this.gbx_ContactInfo.TabIndex = 14;
            this.gbx_ContactInfo.TabStop = false;
            this.gbx_ContactInfo.Text = "Selected Contact";
            // 
            // btn_EditContact
            // 
            this.btn_EditContact.Location = new System.Drawing.Point(190, 71);
            this.btn_EditContact.Name = "btn_EditContact";
            this.btn_EditContact.Size = new System.Drawing.Size(56, 20);
            this.btn_EditContact.TabIndex = 25;
            this.btn_EditContact.Text = "Edit";
            this.btn_EditContact.UseVisualStyleBackColor = true;
            this.btn_EditContact.Click += new System.EventHandler(this.EnableEditing);
            // 
            // txt_Fax
            // 
            this.txt_Fax.Location = new System.Drawing.Point(84, 97);
            this.txt_Fax.Name = "txt_Fax";
            this.txt_Fax.ReadOnly = true;
            this.txt_Fax.Size = new System.Drawing.Size(100, 20);
            this.txt_Fax.TabIndex = 24;
            // 
            // txt_CellPhone
            // 
            this.txt_CellPhone.Location = new System.Drawing.Point(84, 71);
            this.txt_CellPhone.Name = "txt_CellPhone";
            this.txt_CellPhone.ReadOnly = true;
            this.txt_CellPhone.Size = new System.Drawing.Size(100, 20);
            this.txt_CellPhone.TabIndex = 23;
            // 
            // txt_OfficePhone
            // 
            this.txt_OfficePhone.Location = new System.Drawing.Point(84, 45);
            this.txt_OfficePhone.Name = "txt_OfficePhone";
            this.txt_OfficePhone.ReadOnly = true;
            this.txt_OfficePhone.Size = new System.Drawing.Size(125, 20);
            this.txt_OfficePhone.TabIndex = 22;
            // 
            // txt_Email
            // 
            this.txt_Email.Location = new System.Drawing.Point(84, 123);
            this.txt_Email.Name = "txt_Email";
            this.txt_Email.ReadOnly = true;
            this.txt_Email.Size = new System.Drawing.Size(160, 20);
            this.txt_Email.TabIndex = 21;
            // 
            // lbl_ContactEmail
            // 
            this.lbl_ContactEmail.AutoSize = true;
            this.lbl_ContactEmail.Location = new System.Drawing.Point(39, 126);
            this.lbl_ContactEmail.Name = "lbl_ContactEmail";
            this.lbl_ContactEmail.Size = new System.Drawing.Size(39, 13);
            this.lbl_ContactEmail.TabIndex = 20;
            this.lbl_ContactEmail.Text = "E-Mail:";
            // 
            // lbl_ContactFax
            // 
            this.lbl_ContactFax.AutoSize = true;
            this.lbl_ContactFax.Location = new System.Drawing.Point(51, 100);
            this.lbl_ContactFax.Name = "lbl_ContactFax";
            this.lbl_ContactFax.Size = new System.Drawing.Size(27, 13);
            this.lbl_ContactFax.TabIndex = 18;
            this.lbl_ContactFax.Text = "Fax:";
            // 
            // lbl_ContactCellPhone
            // 
            this.lbl_ContactCellPhone.AutoSize = true;
            this.lbl_ContactCellPhone.Location = new System.Drawing.Point(17, 74);
            this.lbl_ContactCellPhone.Name = "lbl_ContactCellPhone";
            this.lbl_ContactCellPhone.Size = new System.Drawing.Size(61, 13);
            this.lbl_ContactCellPhone.TabIndex = 16;
            this.lbl_ContactCellPhone.Text = "Cell Phone:";
            // 
            // lbl_ContactOfficePhone
            // 
            this.lbl_ContactOfficePhone.AutoSize = true;
            this.lbl_ContactOfficePhone.Location = new System.Drawing.Point(6, 48);
            this.lbl_ContactOfficePhone.Name = "lbl_ContactOfficePhone";
            this.lbl_ContactOfficePhone.Size = new System.Drawing.Size(72, 13);
            this.lbl_ContactOfficePhone.TabIndex = 14;
            this.lbl_ContactOfficePhone.Text = "Office Phone:";
            // 
            // lbl_ContactName
            // 
            this.lbl_ContactName.AutoSize = true;
            this.lbl_ContactName.Location = new System.Drawing.Point(39, 22);
            this.lbl_ContactName.Name = "lbl_ContactName";
            this.lbl_ContactName.Size = new System.Drawing.Size(38, 13);
            this.lbl_ContactName.TabIndex = 9;
            this.lbl_ContactName.Text = "Name:";
            // 
            // txt_ContactName
            // 
            this.txt_ContactName.Location = new System.Drawing.Point(84, 19);
            this.txt_ContactName.Name = "txt_ContactName";
            this.txt_ContactName.ReadOnly = true;
            this.txt_ContactName.Size = new System.Drawing.Size(160, 20);
            this.txt_ContactName.TabIndex = 13;
            // 
            // lbl_BuildingContacts
            // 
            this.lbl_BuildingContacts.AutoSize = true;
            this.lbl_BuildingContacts.Location = new System.Drawing.Point(7, 97);
            this.lbl_BuildingContacts.Name = "lbl_BuildingContacts";
            this.lbl_BuildingContacts.Size = new System.Drawing.Size(92, 13);
            this.lbl_BuildingContacts.TabIndex = 12;
            this.lbl_BuildingContacts.Text = "Building Contacts:";
            // 
            // lbx_BuildingContacts
            // 
            this.lbx_BuildingContacts.FormattingEnabled = true;
            this.lbx_BuildingContacts.Location = new System.Drawing.Point(9, 113);
            this.lbx_BuildingContacts.Name = "lbx_BuildingContacts";
            this.lbx_BuildingContacts.Size = new System.Drawing.Size(120, 56);
            this.lbx_BuildingContacts.TabIndex = 11;
            this.lbx_BuildingContacts.Click += new System.EventHandler(this.Contact_Selected);
            this.lbx_BuildingContacts.MouseDown += new System.Windows.Forms.MouseEventHandler(this.Contacts_MouseClick);
            // 
            // lbl_CompanyContacts
            // 
            this.lbl_CompanyContacts.AutoSize = true;
            this.lbl_CompanyContacts.Location = new System.Drawing.Point(6, 16);
            this.lbl_CompanyContacts.Name = "lbl_CompanyContacts";
            this.lbl_CompanyContacts.Size = new System.Drawing.Size(99, 13);
            this.lbl_CompanyContacts.TabIndex = 10;
            this.lbl_CompanyContacts.Text = "Company Contacts:";
            // 
            // lbx_CompanyContacts
            // 
            this.lbx_CompanyContacts.FormattingEnabled = true;
            this.lbx_CompanyContacts.Location = new System.Drawing.Point(9, 32);
            this.lbx_CompanyContacts.Name = "lbx_CompanyContacts";
            this.lbx_CompanyContacts.Size = new System.Drawing.Size(120, 56);
            this.lbx_CompanyContacts.TabIndex = 9;
            this.lbx_CompanyContacts.Click += new System.EventHandler(this.Contact_Selected);
            this.lbx_CompanyContacts.MouseDown += new System.Windows.Forms.MouseEventHandler(this.Contacts_MouseClick);
            // 
            // tab_UpcomingAndOverdue
            // 
            this.tab_UpcomingAndOverdue.Controls.Add(this.gbx_ContactLog);
            this.tab_UpcomingAndOverdue.Controls.Add(this.groupBox6);
            this.tab_UpcomingAndOverdue.Controls.Add(this.tlp_UpcomingAndOverdue);
            this.tab_UpcomingAndOverdue.Controls.Add(this.groupBox4);
            this.tab_UpcomingAndOverdue.Location = new System.Drawing.Point(4, 22);
            this.tab_UpcomingAndOverdue.Name = "tab_UpcomingAndOverdue";
            this.tab_UpcomingAndOverdue.Padding = new System.Windows.Forms.Padding(3);
            this.tab_UpcomingAndOverdue.Size = new System.Drawing.Size(879, 904);
            this.tab_UpcomingAndOverdue.TabIndex = 1;
            this.tab_UpcomingAndOverdue.Text = "Upcoming / Overdue ";
            this.tab_UpcomingAndOverdue.UseVisualStyleBackColor = true;
            // 
            // gbx_ContactLog
            // 
            this.gbx_ContactLog.Location = new System.Drawing.Point(349, 330);
            this.gbx_ContactLog.Name = "gbx_ContactLog";
            this.gbx_ContactLog.Size = new System.Drawing.Size(527, 448);
            this.gbx_ContactLog.TabIndex = 11;
            this.gbx_ContactLog.TabStop = false;
            this.gbx_ContactLog.Text = "Contact Log";
            // 
            // groupBox6
            // 
            this.groupBox6.Controls.Add(this.listView1);
            this.groupBox6.Location = new System.Drawing.Point(349, 784);
            this.groupBox6.Name = "groupBox6";
            this.groupBox6.Size = new System.Drawing.Size(514, 170);
            this.groupBox6.TabIndex = 9;
            this.groupBox6.TabStop = false;
            this.groupBox6.Text = "Inspection History";
            // 
            // listView1
            // 
            this.listView1.Columns.AddRange(new System.Windows.Forms.ColumnHeader[] {
            this.columnHeader1,
            this.columnHeader2,
            this.columnHeader3,
            this.columnHeader4,
            this.columnHeader5});
            this.listView1.FullRowSelect = true;
            this.listView1.Location = new System.Drawing.Point(14, 24);
            this.listView1.MultiSelect = false;
            this.listView1.Name = "listView1";
            this.listView1.Size = new System.Drawing.Size(494, 129);
            this.listView1.TabIndex = 15;
            this.listView1.UseCompatibleStateImageBehavior = false;
            this.listView1.View = System.Windows.Forms.View.Details;
            // 
            // columnHeader1
            // 
            this.columnHeader1.Text = "Date";
            this.columnHeader1.Width = 70;
            // 
            // columnHeader2
            // 
            this.columnHeader2.Text = "Inspection Type";
            this.columnHeader2.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.columnHeader2.Width = 100;
            // 
            // columnHeader3
            // 
            this.columnHeader3.Text = "Status";
            this.columnHeader3.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.columnHeader3.Width = 100;
            // 
            // columnHeader4
            // 
            this.columnHeader4.Text = "Inspector";
            this.columnHeader4.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.columnHeader4.Width = 80;
            // 
            // columnHeader5
            // 
            this.columnHeader5.Text = "Report Available";
            this.columnHeader5.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.columnHeader5.Width = 100;
            // 
            // tlp_UpcomingAndOverdue
            // 
            this.tlp_UpcomingAndOverdue.ColumnCount = 1;
            this.tlp_UpcomingAndOverdue.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 40F));
            this.tlp_UpcomingAndOverdue.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 60F));
            this.tlp_UpcomingAndOverdue.Controls.Add(this.groupBox2, 0, 0);
            this.tlp_UpcomingAndOverdue.Controls.Add(this.groupBox3, 0, 1);
            this.tlp_UpcomingAndOverdue.Location = new System.Drawing.Point(7, 63);
            this.tlp_UpcomingAndOverdue.Name = "tlp_UpcomingAndOverdue";
            this.tlp_UpcomingAndOverdue.RowCount = 2;
            this.tlp_UpcomingAndOverdue.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tlp_UpcomingAndOverdue.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tlp_UpcomingAndOverdue.Size = new System.Drawing.Size(336, 891);
            this.tlp_UpcomingAndOverdue.TabIndex = 1;
            // 
            // groupBox2
            // 
            this.groupBox2.Location = new System.Drawing.Point(3, 3);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Size = new System.Drawing.Size(330, 439);
            this.groupBox2.TabIndex = 0;
            this.groupBox2.TabStop = false;
            this.groupBox2.Text = "Upcoming";
            // 
            // groupBox3
            // 
            this.groupBox3.Location = new System.Drawing.Point(3, 448);
            this.groupBox3.Name = "groupBox3";
            this.groupBox3.Size = new System.Drawing.Size(330, 440);
            this.groupBox3.TabIndex = 1;
            this.groupBox3.TabStop = false;
            this.groupBox3.Text = "Overdue";
            // 
            // groupBox4
            // 
            this.groupBox4.Controls.Add(this.groupBox5);
            this.groupBox4.Controls.Add(this.label6);
            this.groupBox4.Controls.Add(this.listBox1);
            this.groupBox4.Controls.Add(this.label7);
            this.groupBox4.Controls.Add(this.listBox2);
            this.groupBox4.Location = new System.Drawing.Point(349, 66);
            this.groupBox4.Name = "groupBox4";
            this.groupBox4.Size = new System.Drawing.Size(284, 258);
            this.groupBox4.TabIndex = 10;
            this.groupBox4.TabStop = false;
            this.groupBox4.Text = "Contacts";
            // 
            // groupBox5
            // 
            this.groupBox5.Controls.Add(this.textBox1);
            this.groupBox5.Controls.Add(this.textBox2);
            this.groupBox5.Controls.Add(this.textBox3);
            this.groupBox5.Controls.Add(this.textBox4);
            this.groupBox5.Controls.Add(this.label1);
            this.groupBox5.Controls.Add(this.label2);
            this.groupBox5.Controls.Add(this.label3);
            this.groupBox5.Controls.Add(this.label4);
            this.groupBox5.Controls.Add(this.label5);
            this.groupBox5.Controls.Add(this.textBox5);
            this.groupBox5.Location = new System.Drawing.Point(9, 81);
            this.groupBox5.Name = "groupBox5";
            this.groupBox5.Size = new System.Drawing.Size(256, 153);
            this.groupBox5.TabIndex = 14;
            this.groupBox5.TabStop = false;
            this.groupBox5.Text = "Selected Contact";
            // 
            // textBox1
            // 
            this.textBox1.Location = new System.Drawing.Point(84, 97);
            this.textBox1.Name = "textBox1";
            this.textBox1.Size = new System.Drawing.Size(100, 20);
            this.textBox1.TabIndex = 24;
            // 
            // textBox2
            // 
            this.textBox2.Location = new System.Drawing.Point(84, 71);
            this.textBox2.Name = "textBox2";
            this.textBox2.Size = new System.Drawing.Size(100, 20);
            this.textBox2.TabIndex = 23;
            // 
            // textBox3
            // 
            this.textBox3.Location = new System.Drawing.Point(84, 45);
            this.textBox3.Name = "textBox3";
            this.textBox3.Size = new System.Drawing.Size(125, 20);
            this.textBox3.TabIndex = 22;
            // 
            // textBox4
            // 
            this.textBox4.Location = new System.Drawing.Point(84, 123);
            this.textBox4.Name = "textBox4";
            this.textBox4.Size = new System.Drawing.Size(160, 20);
            this.textBox4.TabIndex = 21;
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Location = new System.Drawing.Point(39, 126);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(39, 13);
            this.label1.TabIndex = 20;
            this.label1.Text = "E-Mail:";
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Location = new System.Drawing.Point(51, 100);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(27, 13);
            this.label2.TabIndex = 18;
            this.label2.Text = "Fax:";
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.Location = new System.Drawing.Point(17, 74);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(61, 13);
            this.label3.TabIndex = 16;
            this.label3.Text = "Cell Phone:";
            // 
            // label4
            // 
            this.label4.AutoSize = true;
            this.label4.Location = new System.Drawing.Point(6, 48);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(72, 13);
            this.label4.TabIndex = 14;
            this.label4.Text = "Office Phone:";
            // 
            // label5
            // 
            this.label5.AutoSize = true;
            this.label5.Location = new System.Drawing.Point(39, 22);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(38, 13);
            this.label5.TabIndex = 9;
            this.label5.Text = "Name:";
            // 
            // textBox5
            // 
            this.textBox5.Location = new System.Drawing.Point(84, 19);
            this.textBox5.Name = "textBox5";
            this.textBox5.Size = new System.Drawing.Size(160, 20);
            this.textBox5.TabIndex = 13;
            // 
            // label6
            // 
            this.label6.AutoSize = true;
            this.label6.Location = new System.Drawing.Point(142, 16);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(92, 13);
            this.label6.TabIndex = 12;
            this.label6.Text = "Building Contacts:";
            // 
            // listBox1
            // 
            this.listBox1.FormattingEnabled = true;
            this.listBox1.Location = new System.Drawing.Point(145, 32);
            this.listBox1.Name = "listBox1";
            this.listBox1.Size = new System.Drawing.Size(120, 43);
            this.listBox1.TabIndex = 11;
            // 
            // label7
            // 
            this.label7.AutoSize = true;
            this.label7.Location = new System.Drawing.Point(6, 16);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(99, 13);
            this.label7.TabIndex = 10;
            this.label7.Text = "Company Contacts:";
            // 
            // listBox2
            // 
            this.listBox2.FormattingEnabled = true;
            this.listBox2.Location = new System.Drawing.Point(9, 32);
            this.listBox2.Name = "listBox2";
            this.listBox2.Size = new System.Drawing.Size(120, 43);
            this.listBox2.TabIndex = 9;
            // 
            // cmu_Contact
            // 
            this.cmu_Contact.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.cmi_AddContact,
            this.cmi_RemoveContact});
            this.cmu_Contact.Name = "cmu_Contact";
            this.cmu_Contact.Size = new System.Drawing.Size(161, 48);
            // 
            // cmi_AddContact
            // 
            this.cmi_AddContact.Name = "cmi_AddContact";
            this.cmi_AddContact.Size = new System.Drawing.Size(160, 22);
            this.cmi_AddContact.Text = "Add Contact";
            this.cmi_AddContact.Click += new System.EventHandler(this.AddContact);
            // 
            // cmi_RemoveContact
            // 
            this.cmi_RemoveContact.Name = "cmi_RemoveContact";
            this.cmi_RemoveContact.Size = new System.Drawing.Size(160, 22);
            this.cmi_RemoveContact.Text = "Remove Contact";
            this.cmi_RemoveContact.Click += new System.EventHandler(this.RemoveContact);
            // 
            // Main_Form
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1664, 1015);
            this.Controls.Add(this.tab_MainTabControl);
            this.Controls.Add(this.mnuMainMenuStrip);
            this.Controls.Add(this.gbx_ResultFilters);
            this.MainMenuStrip = this.mnuMainMenuStrip;
            this.MaximizeBox = false;
            this.MinimizeBox = false;
            this.Name = "Main_Form";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "TII Inspection Database";
            this.Load += new System.EventHandler(this.Main_Form_Load);
            this.mnuMainMenuStrip.ResumeLayout(false);
            this.mnuMainMenuStrip.PerformLayout();
            this.gbx_InspectionHistory.ResumeLayout(false);
            this.gbx_Building.ResumeLayout(false);
            this.gbx_Building.PerformLayout();
            this.gbx_Company.ResumeLayout(false);
            this.gbx_Company.PerformLayout();
            this.tab_BuildingCompanySelector.ResumeLayout(false);
            this.tab_ByCompany.ResumeLayout(false);
            this.tab_ByCompany.PerformLayout();
            this.tab_ByBuilding.ResumeLayout(false);
            this.tab_ByBuilding.PerformLayout();
            this.gbx_ResultFilters.ResumeLayout(false);
            this.gbx_ResultFilters.PerformLayout();
            this.tab_MainTabControl.ResumeLayout(false);
            this.tab_DatabaseBrowser.ResumeLayout(false);
            this.gbx_ButtonContainer.ResumeLayout(false);
            this.gbx_Contacts.ResumeLayout(false);
            this.gbx_Contacts.PerformLayout();
            this.gbx_ContactInfo.ResumeLayout(false);
            this.gbx_ContactInfo.PerformLayout();
            this.tab_UpcomingAndOverdue.ResumeLayout(false);
            this.groupBox6.ResumeLayout(false);
            this.tlp_UpcomingAndOverdue.ResumeLayout(false);
            this.groupBox4.ResumeLayout(false);
            this.groupBox4.PerformLayout();
            this.groupBox5.ResumeLayout(false);
            this.groupBox5.PerformLayout();
            this.cmu_Contact.ResumeLayout(false);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.TabControl tab_BuildingCompanySelector;
        private System.Windows.Forms.TabPage tab_ByCompany;
        private System.Windows.Forms.ListBox lbx_CompanyList;
        private System.Windows.Forms.TextBox txt_FilterCompany;
        private System.Windows.Forms.TabPage tab_ByBuilding;
        private System.Windows.Forms.TextBox txt_FilterAddress;
        private System.Windows.Forms.GroupBox gbx_ResultFilters;
        private System.Windows.Forms.CheckBox cbx_ShowInactive;
        private System.Windows.Forms.CheckBox cbx_ShowDC;
        private System.Windows.Forms.CheckBox cbx_ShowMD;
        private System.Windows.Forms.ListBox lbx_BuildingList;
        private System.Windows.Forms.ToolStripMenuItem testMethodToolStripMenuItem;
        private System.Windows.Forms.GroupBox gbx_Company;
        private System.Windows.Forms.TextBox txt_CompanyName;
        private System.Windows.Forms.Label lbl_OtherBuildings;
        private System.Windows.Forms.Label lbl_CompanyName;
        private System.Windows.Forms.ListBox lbx_OtherCompanyBuildings;
        private System.Windows.Forms.Label lbl_CompanyAddress;
        private System.Windows.Forms.TextBox txt_CompanyCity;
        private System.Windows.Forms.TextBox txt_CompanyZip;
        private System.Windows.Forms.TextBox txt_CompanyState;
        private System.Windows.Forms.TextBox txt_CompanyStreet;
        private System.Windows.Forms.GroupBox gbx_Building;
        private System.Windows.Forms.ListView lvw_RelatedDocuments;
        private System.Windows.Forms.ColumnHeader col_Title;
        private System.Windows.Forms.ColumnHeader col_Desc;
        private System.Windows.Forms.Button btn_AddBldgDocument;
        private System.Windows.Forms.ListBox lbx_ElevatorList;
        private System.Windows.Forms.Button btn_ViewMap;
        private System.Windows.Forms.TextBox txt_Contractor;
        private System.Windows.Forms.Label lbl_Contractor;
        private System.Windows.Forms.Label lbl_Anniversary;
        private System.Windows.Forms.TextBox txt_HourlyFee;
        private System.Windows.Forms.Label lbl_HourlyFee;
        private System.Windows.Forms.TextBox txt_FirmFee;
        private System.Windows.Forms.Label lbl_FirmFee;
        private System.Windows.Forms.Label lbl_BuildingCounty;
        private System.Windows.Forms.Label lbl_RelatedDocs;
        private System.Windows.Forms.TextBox txt_BuildingName;
        private System.Windows.Forms.Label lbl_BuildingName;
        private System.Windows.Forms.CheckBox cbx_BuildingActive;
        private System.Windows.Forms.Label lbl_BuildingAddress;
        private System.Windows.Forms.TextBox txt_BuildingZip;
        private System.Windows.Forms.TextBox txt_BuildingAddress;
        private System.Windows.Forms.TextBox txt_BuildingState;
        private System.Windows.Forms.TextBox txt_BuildingCity;
        private System.Windows.Forms.ComboBox cbo_BuildingCounty;
        private System.Windows.Forms.ComboBox cbo_BuildingAnniversary;
        private System.Windows.Forms.GroupBox gbx_InspectionHistory;
        private System.Windows.Forms.Button btn_EnterNewInspection;
        private System.Windows.Forms.ListView lvw_InspectionList;
        private System.Windows.Forms.ColumnHeader col_Date;
        private System.Windows.Forms.ColumnHeader col_InspectionType;
        private System.Windows.Forms.ColumnHeader col_Status;
        private System.Windows.Forms.ColumnHeader col_Inspector;
        private System.Windows.Forms.ColumnHeader col_Report;
        private System.Windows.Forms.TabControl tab_MainTabControl;
        private System.Windows.Forms.TabPage tab_DatabaseBrowser;
        private System.Windows.Forms.TabPage tab_UpcomingAndOverdue;
        private System.Windows.Forms.GroupBox gbx_Contacts;
        private System.Windows.Forms.Label lbl_BuildingContacts;
        private System.Windows.Forms.ListBox lbx_BuildingContacts;
        private System.Windows.Forms.Label lbl_CompanyContacts;
        private System.Windows.Forms.ListBox lbx_CompanyContacts;
        private System.Windows.Forms.GroupBox gbx_ContactInfo;
        private System.Windows.Forms.TextBox txt_Fax;
        private System.Windows.Forms.TextBox txt_CellPhone;
        private System.Windows.Forms.TextBox txt_OfficePhone;
        private System.Windows.Forms.TextBox txt_Email;
        private System.Windows.Forms.Label lbl_ContactEmail;
        private System.Windows.Forms.Label lbl_ContactFax;
        private System.Windows.Forms.Label lbl_ContactCellPhone;
        private System.Windows.Forms.Label lbl_ContactOfficePhone;
        private System.Windows.Forms.Label lbl_ContactName;
        private System.Windows.Forms.TextBox txt_ContactName;
        private System.Windows.Forms.TableLayoutPanel tlp_UpcomingAndOverdue;
        private System.Windows.Forms.GroupBox groupBox2;
        private System.Windows.Forms.GroupBox groupBox3;
        private System.Windows.Forms.GroupBox groupBox4;
        private System.Windows.Forms.GroupBox groupBox5;
        private System.Windows.Forms.TextBox textBox1;
        private System.Windows.Forms.TextBox textBox2;
        private System.Windows.Forms.TextBox textBox3;
        private System.Windows.Forms.TextBox textBox4;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.TextBox textBox5;
        private System.Windows.Forms.Label label6;
        private System.Windows.Forms.ListBox listBox1;
        private System.Windows.Forms.Label label7;
        private System.Windows.Forms.ListBox listBox2;
        private System.Windows.Forms.GroupBox groupBox6;
        private System.Windows.Forms.ListView listView1;
        private System.Windows.Forms.ColumnHeader columnHeader1;
        private System.Windows.Forms.ColumnHeader columnHeader2;
        private System.Windows.Forms.ColumnHeader columnHeader3;
        private System.Windows.Forms.ColumnHeader columnHeader4;
        private System.Windows.Forms.ColumnHeader columnHeader5;
        private System.Windows.Forms.GroupBox gbx_ContactLog;
        private System.Windows.Forms.Button btn_EditCompany;
        private System.Windows.Forms.GroupBox gbx_ButtonContainer;
        private System.Windows.Forms.Button btn_AddNewCompany;
        private System.Windows.Forms.Button btn_EditBuilding;
        private System.Windows.Forms.Button btn_EditContact;
        private System.Windows.Forms.Button btn_NewBuilding;
        private System.Windows.Forms.ContextMenuStrip cmu_Contact;
        private System.Windows.Forms.ToolStripMenuItem cmi_AddContact;
        private System.Windows.Forms.ToolStripMenuItem cmi_RemoveContact;
    }
}