// <auto-generated />

namespace TII_NewDatabase
{
    /// <summary>
    /// Partial class - contains the code generated by the Form Creator.
    /// </summary>
    public partial class Main_Form
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Main Menu Strip Bar.
        /// </summary>
        private System.Windows.Forms.MenuStrip mnuMainMenuStrip;

        /// <summary>
        /// File Menu Dropdown.
        /// </summary>
        private System.Windows.Forms.ToolStripMenuItem fileToolStripMenuItem;

        /// <summary>
        /// Settings Menu Dropdown.
        /// </summary>
        private System.Windows.Forms.ToolStripMenuItem settingsToolStripMenuItem;

        /// <summary>
        /// Forces the creation of a backup outside of the scheduled backups.
        /// </summary>
        private System.Windows.Forms.ToolStripMenuItem forceBackupToolStripMenuItem;

        /// <summary>
        /// Exit the Database Program.
        /// </summary>
        private System.Windows.Forms.ToolStripMenuItem exitToolStripMenuItem;

        /// <summary>
        /// View the Connection settings and edit if required.
        /// </summary>
        private System.Windows.Forms.ToolStripMenuItem connectionsToolStripMenuItem;

        /// <summary>
        /// View/Edit the user preferences.
        /// </summary>
        private System.Windows.Forms.ToolStripMenuItem mnu_Preferances;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">True if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (this.components != null))
            {
                this.components.Dispose();
            }

            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            this.mnuMainMenuStrip = new System.Windows.Forms.MenuStrip();
            this.fileToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.forceBackupToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.exitToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.settingsToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.connectionsToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.mnu_Preferances = new System.Windows.Forms.ToolStripMenuItem();
            this.testMethodToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.gbx_InspectionHistory = new System.Windows.Forms.GroupBox();
            this.btn_EnterNewInspection = new System.Windows.Forms.Button();
            this.lvw_InspectionList = new System.Windows.Forms.ListView();
            this.col_Date = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.col_InspectionType = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.col_Status = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.col_Inspector = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.col_Report = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.gbx_Building = new System.Windows.Forms.GroupBox();
            this.cbx_Heats = new System.Windows.Forms.CheckBox();
            this.cbo_Contractor = new System.Windows.Forms.ComboBox();
            this.cbx_EmPwr = new System.Windows.Forms.CheckBox();
            this.cbx_FES = new System.Windows.Forms.CheckBox();
            this.btn_EditBuilding = new System.Windows.Forms.Button();
            this.cbo_BuildingAnniversary = new System.Windows.Forms.ComboBox();
            this.cbo_BuildingCounty = new System.Windows.Forms.ComboBox();
            this.lvw_RelatedDocuments = new System.Windows.Forms.ListView();
            this.col_Title = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.col_Desc = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.btn_AddBldgDocument = new System.Windows.Forms.Button();
            this.lbx_ElevatorList = new System.Windows.Forms.ListBox();
            this.btn_ViewMap = new System.Windows.Forms.Button();
            this.lbl_Contractor = new System.Windows.Forms.Label();
            this.lbl_Anniversary = new System.Windows.Forms.Label();
            this.txt_HourlyFee = new System.Windows.Forms.TextBox();
            this.lbl_HourlyFee = new System.Windows.Forms.Label();
            this.txt_FirmFee = new System.Windows.Forms.TextBox();
            this.lbl_FirmFee = new System.Windows.Forms.Label();
            this.lbl_BuildingCounty = new System.Windows.Forms.Label();
            this.lbl_RelatedDocs = new System.Windows.Forms.Label();
            this.txt_BuildingName = new System.Windows.Forms.TextBox();
            this.lbl_BuildingName = new System.Windows.Forms.Label();
            this.cbx_BuildingActive = new System.Windows.Forms.CheckBox();
            this.lbl_BuildingAddress = new System.Windows.Forms.Label();
            this.txt_BuildingZip = new System.Windows.Forms.TextBox();
            this.txt_BuildingAddress = new System.Windows.Forms.TextBox();
            this.txt_BuildingState = new System.Windows.Forms.TextBox();
            this.txt_BuildingCity = new System.Windows.Forms.TextBox();
            this.gbx_Company = new System.Windows.Forms.GroupBox();
            this.btn_EditCompany = new System.Windows.Forms.Button();
            this.txt_CompanyName = new System.Windows.Forms.TextBox();
            this.lbl_OtherBuildings = new System.Windows.Forms.Label();
            this.lbl_CompanyName = new System.Windows.Forms.Label();
            this.lbx_OtherCompanyBuildings = new System.Windows.Forms.ListBox();
            this.lbl_CompanyAddress = new System.Windows.Forms.Label();
            this.txt_CompanyCity = new System.Windows.Forms.TextBox();
            this.txt_CompanyZip = new System.Windows.Forms.TextBox();
            this.txt_CompanyState = new System.Windows.Forms.TextBox();
            this.txt_CompanyStreet = new System.Windows.Forms.TextBox();
            this.tab_BuildingCompanySelector = new System.Windows.Forms.TabControl();
            this.tab_ByCompany = new System.Windows.Forms.TabPage();
            this.lbx_CompanyList = new System.Windows.Forms.ListBox();
            this.txt_FilterCompany = new System.Windows.Forms.TextBox();
            this.tab_ByBuilding = new System.Windows.Forms.TabPage();
            this.lbx_BuildingList = new System.Windows.Forms.ListBox();
            this.txt_FilterAddress = new System.Windows.Forms.TextBox();
            this.gbx_ResultFilters = new System.Windows.Forms.GroupBox();
            this.cbx_ShowInactive = new System.Windows.Forms.CheckBox();
            this.cbx_ShowDC = new System.Windows.Forms.CheckBox();
            this.cbx_ShowMD = new System.Windows.Forms.CheckBox();
            this.tab_MainTabControl = new System.Windows.Forms.TabControl();
            this.tab_DatabaseBrowser = new System.Windows.Forms.TabPage();
            this.gbx_ButtonContainer = new System.Windows.Forms.GroupBox();
            this.btn_NewElevator = new System.Windows.Forms.Button();
            this.btn_NewBuilding = new System.Windows.Forms.Button();
            this.btn_AddNewCompany = new System.Windows.Forms.Button();
            this.gbx_Contacts = new System.Windows.Forms.GroupBox();
            this.gbx_ContactInfo = new System.Windows.Forms.GroupBox();
            this.btn_EditContact = new System.Windows.Forms.Button();
            this.txt_Fax = new System.Windows.Forms.TextBox();
            this.txt_CellPhone = new System.Windows.Forms.TextBox();
            this.txt_OfficePhone = new System.Windows.Forms.TextBox();
            this.txt_Email = new System.Windows.Forms.TextBox();
            this.lbl_ContactEmail = new System.Windows.Forms.Label();
            this.lbl_ContactFax = new System.Windows.Forms.Label();
            this.lbl_ContactCellPhone = new System.Windows.Forms.Label();
            this.lbl_ContactOfficePhone = new System.Windows.Forms.Label();
            this.lbl_ContactName = new System.Windows.Forms.Label();
            this.txt_ContactName = new System.Windows.Forms.TextBox();
            this.lbl_BuildingContacts = new System.Windows.Forms.Label();
            this.lbx_BuildingContacts = new System.Windows.Forms.ListBox();
            this.lbl_CompanyContacts = new System.Windows.Forms.Label();
            this.lbx_CompanyContacts = new System.Windows.Forms.ListBox();
            this.tab_UpcomingAndOverdue = new System.Windows.Forms.TabPage();
            this.groupBox1 = new System.Windows.Forms.GroupBox();
            this.gbx_CurrentSchedule = new System.Windows.Forms.GroupBox();
            this.lbx_CurrentSchedule = new System.Windows.Forms.ListBox();
            this.cal_CalendarDisplay = new System.Windows.Forms.MonthCalendar();
            this.gbx_NextAvailable = new System.Windows.Forms.GroupBox();
            this.cbx_Sundays = new System.Windows.Forms.CheckBox();
            this.cbx_Saturdays = new System.Windows.Forms.CheckBox();
            this.cbx_Weekdays = new System.Windows.Forms.CheckBox();
            this.lbl_StartDate = new System.Windows.Forms.Label();
            this.dtp_StartDate = new System.Windows.Forms.DateTimePicker();
            this.lbx_PossibleAppointments = new System.Windows.Forms.ListBox();
            this.lbl_HoursNeeded = new System.Windows.Forms.Label();
            this.nym_HoursNeeded = new System.Windows.Forms.NumericUpDown();
            this.lbl_NoLaterThan = new System.Windows.Forms.Label();
            this.dtp_NoLaterThan = new System.Windows.Forms.DateTimePicker();
            this.lbl_NoEarlierThan = new System.Windows.Forms.Label();
            this.dtp_NoEarlierThan = new System.Windows.Forms.DateTimePicker();
            this.lbl_InspectorToSchedule = new System.Windows.Forms.Label();
            this.cbo_InspectorToSchedule = new System.Windows.Forms.ComboBox();
            this.tlp_UpcomingAndOverdue = new System.Windows.Forms.TableLayoutPanel();
            this.gbx_UpcomingInspections = new System.Windows.Forms.GroupBox();
            this.lbl_days = new System.Windows.Forms.Label();
            this.lbl_InTheNext = new System.Windows.Forms.Label();
            this.cbo_UpcomingDays = new System.Windows.Forms.ComboBox();
            this.lvw_UpcomingInspection = new System.Windows.Forms.ListView();
            this.col_Address = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.col_Type = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.col_DueDate = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.groupBox3 = new System.Windows.Forms.GroupBox();
            this.lvw_OverdueInspections = new System.Windows.Forms.ListView();
            this.col_Over_Address = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.col_OverDays = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.col_OverType = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.tab_Calendar = new System.Windows.Forms.TabPage();
            this.cmu_Contact = new System.Windows.Forms.ContextMenuStrip(this.components);
            this.cmi_AddContact = new System.Windows.Forms.ToolStripMenuItem();
            this.cmi_RemoveContact = new System.Windows.Forms.ToolStripMenuItem();
            this.statusstrip_MainForm = new System.Windows.Forms.StatusStrip();
            this.status_Connection = new System.Windows.Forms.ToolStripStatusLabel();
            this.mnuMainMenuStrip.SuspendLayout();
            this.gbx_InspectionHistory.SuspendLayout();
            this.gbx_Building.SuspendLayout();
            this.gbx_Company.SuspendLayout();
            this.tab_BuildingCompanySelector.SuspendLayout();
            this.tab_ByCompany.SuspendLayout();
            this.tab_ByBuilding.SuspendLayout();
            this.gbx_ResultFilters.SuspendLayout();
            this.tab_MainTabControl.SuspendLayout();
            this.tab_DatabaseBrowser.SuspendLayout();
            this.gbx_ButtonContainer.SuspendLayout();
            this.gbx_Contacts.SuspendLayout();
            this.gbx_ContactInfo.SuspendLayout();
            this.tab_UpcomingAndOverdue.SuspendLayout();
            this.groupBox1.SuspendLayout();
            this.gbx_CurrentSchedule.SuspendLayout();
            this.gbx_NextAvailable.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.nym_HoursNeeded)).BeginInit();
            this.tlp_UpcomingAndOverdue.SuspendLayout();
            this.gbx_UpcomingInspections.SuspendLayout();
            this.groupBox3.SuspendLayout();
            this.cmu_Contact.SuspendLayout();
            this.statusstrip_MainForm.SuspendLayout();
            this.SuspendLayout();
            // 
            // mnuMainMenuStrip
            // 
            this.mnuMainMenuStrip.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.fileToolStripMenuItem,
            this.settingsToolStripMenuItem,
            this.testMethodToolStripMenuItem});
            this.mnuMainMenuStrip.Location = new System.Drawing.Point(0, 0);
            this.mnuMainMenuStrip.Name = "mnuMainMenuStrip";
            this.mnuMainMenuStrip.Size = new System.Drawing.Size(1664, 24);
            this.mnuMainMenuStrip.TabIndex = 0;
            this.mnuMainMenuStrip.Text = "menuStrip1";
            // 
            // fileToolStripMenuItem
            // 
            this.fileToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.forceBackupToolStripMenuItem,
            this.exitToolStripMenuItem});
            this.fileToolStripMenuItem.Name = "fileToolStripMenuItem";
            this.fileToolStripMenuItem.Size = new System.Drawing.Size(37, 20);
            this.fileToolStripMenuItem.Text = "&File";
            // 
            // exitToolStripMenuItem
            // 
            this.exitToolStripMenuItem.Name = "exitToolStripMenuItem";
            this.exitToolStripMenuItem.Size = new System.Drawing.Size(145, 22);
            this.exitToolStripMenuItem.Text = "E&xit";
            this.exitToolStripMenuItem.Click += new System.EventHandler(this.ExitToolStripMenuItem_Click);
            // 
            // settingsToolStripMenuItem
            // 
            this.settingsToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.connectionsToolStripMenuItem,
            this.mnu_Preferances});
            this.settingsToolStripMenuItem.Name = "settingsToolStripMenuItem";
            this.settingsToolStripMenuItem.Size = new System.Drawing.Size(61, 20);
            this.settingsToolStripMenuItem.Text = "&Settings";
            // 
            // connectionsToolStripMenuItem
            // 
            this.connectionsToolStripMenuItem.Name = "connectionsToolStripMenuItem";
            this.connectionsToolStripMenuItem.Size = new System.Drawing.Size(141, 22);
            this.connectionsToolStripMenuItem.Text = "C&onnections";
            this.connectionsToolStripMenuItem.Click += new System.EventHandler(this.OpenConnectionSettingsForm);
            // 
            // mnu_Preferances
            // 
            this.mnu_Preferances.Name = "mnu_Preferances";
            this.mnu_Preferances.Size = new System.Drawing.Size(141, 22);
            this.mnu_Preferances.Text = "&Preferences";
            this.mnu_Preferances.Click += new System.EventHandler(this.OpenChildForm);
            // 
            // testMethodToolStripMenuItem
            // 
            this.testMethodToolStripMenuItem.Name = "testMethodToolStripMenuItem";
            this.testMethodToolStripMenuItem.Size = new System.Drawing.Size(12, 20);
            // 
            // gbx_InspectionHistory
            // 
            this.gbx_InspectionHistory.Controls.Add(this.btn_EnterNewInspection);
            this.gbx_InspectionHistory.Controls.Add(this.lvw_InspectionList);
            this.gbx_InspectionHistory.Location = new System.Drawing.Point(248, 716);
            this.gbx_InspectionHistory.Name = "gbx_InspectionHistory";
            this.gbx_InspectionHistory.Size = new System.Drawing.Size(574, 170);
            this.gbx_InspectionHistory.TabIndex = 2;
            this.gbx_InspectionHistory.TabStop = false;
            this.gbx_InspectionHistory.Text = "Inspection History";
            // 
            // btn_EnterNewInspection
            // 
            this.btn_EnterNewInspection.Location = new System.Drawing.Point(485, 24);
            this.btn_EnterNewInspection.Name = "btn_EnterNewInspection";
            this.btn_EnterNewInspection.Size = new System.Drawing.Size(75, 129);
            this.btn_EnterNewInspection.TabIndex = 16;
            this.btn_EnterNewInspection.Text = "Enter New Inspection";
            this.btn_EnterNewInspection.UseVisualStyleBackColor = true;
            this.btn_EnterNewInspection.Click += new System.EventHandler(this.OpenChildForm);
            // 
            // lvw_InspectionList
            // 
            this.lvw_InspectionList.Columns.AddRange(new System.Windows.Forms.ColumnHeader[] {
            this.col_Date,
            this.col_InspectionType,
            this.col_Status,
            this.col_Inspector,
            this.col_Report});
            this.lvw_InspectionList.FullRowSelect = true;
            this.lvw_InspectionList.Location = new System.Drawing.Point(14, 24);
            this.lvw_InspectionList.MultiSelect = false;
            this.lvw_InspectionList.Name = "lvw_InspectionList";
            this.lvw_InspectionList.Size = new System.Drawing.Size(458, 129);
            this.lvw_InspectionList.TabIndex = 15;
            this.lvw_InspectionList.UseCompatibleStateImageBehavior = false;
            this.lvw_InspectionList.View = System.Windows.Forms.View.Details;
            this.lvw_InspectionList.MouseClick += new System.Windows.Forms.MouseEventHandler(this.Inspection_RightClick);
            // 
            // col_Date
            // 
            this.col_Date.Text = "Date";
            this.col_Date.Width = 70;
            // 
            // col_InspectionType
            // 
            this.col_InspectionType.Text = "Inspection Type";
            this.col_InspectionType.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.col_InspectionType.Width = 100;
            // 
            // col_Status
            // 
            this.col_Status.Text = "Status";
            this.col_Status.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.col_Status.Width = 100;
            // 
            // col_Inspector
            // 
            this.col_Inspector.Text = "Inspector";
            this.col_Inspector.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.col_Inspector.Width = 80;
            // 
            // col_Report
            // 
            this.col_Report.Text = "Report Available";
            this.col_Report.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.col_Report.Width = 100;
            // 
            // gbx_Building
            // 
            this.gbx_Building.Controls.Add(this.cbx_Heats);
            this.gbx_Building.Controls.Add(this.cbo_Contractor);
            this.gbx_Building.Controls.Add(this.cbx_EmPwr);
            this.gbx_Building.Controls.Add(this.cbx_FES);
            this.gbx_Building.Controls.Add(this.btn_EditBuilding);
            this.gbx_Building.Controls.Add(this.cbo_BuildingAnniversary);
            this.gbx_Building.Controls.Add(this.cbo_BuildingCounty);
            this.gbx_Building.Controls.Add(this.lvw_RelatedDocuments);
            this.gbx_Building.Controls.Add(this.btn_AddBldgDocument);
            this.gbx_Building.Controls.Add(this.lbx_ElevatorList);
            this.gbx_Building.Controls.Add(this.btn_ViewMap);
            this.gbx_Building.Controls.Add(this.lbl_Contractor);
            this.gbx_Building.Controls.Add(this.lbl_Anniversary);
            this.gbx_Building.Controls.Add(this.txt_HourlyFee);
            this.gbx_Building.Controls.Add(this.lbl_HourlyFee);
            this.gbx_Building.Controls.Add(this.txt_FirmFee);
            this.gbx_Building.Controls.Add(this.lbl_FirmFee);
            this.gbx_Building.Controls.Add(this.lbl_BuildingCounty);
            this.gbx_Building.Controls.Add(this.lbl_RelatedDocs);
            this.gbx_Building.Controls.Add(this.txt_BuildingName);
            this.gbx_Building.Controls.Add(this.lbl_BuildingName);
            this.gbx_Building.Controls.Add(this.cbx_BuildingActive);
            this.gbx_Building.Controls.Add(this.lbl_BuildingAddress);
            this.gbx_Building.Controls.Add(this.txt_BuildingZip);
            this.gbx_Building.Controls.Add(this.txt_BuildingAddress);
            this.gbx_Building.Controls.Add(this.txt_BuildingState);
            this.gbx_Building.Controls.Add(this.txt_BuildingCity);
            this.gbx_Building.Location = new System.Drawing.Point(248, 216);
            this.gbx_Building.Name = "gbx_Building";
            this.gbx_Building.Size = new System.Drawing.Size(574, 230);
            this.gbx_Building.TabIndex = 7;
            this.gbx_Building.TabStop = false;
            this.gbx_Building.Text = "Building";
            // 
            // cbx_Heats
            // 
            this.cbx_Heats.AutoSize = true;
            this.cbx_Heats.Enabled = false;
            this.cbx_Heats.Location = new System.Drawing.Point(180, 199);
            this.cbx_Heats.Name = "cbx_Heats";
            this.cbx_Heats.Size = new System.Drawing.Size(54, 17);
            this.cbx_Heats.TabIndex = 33;
            this.cbx_Heats.Text = "Heats";
            this.cbx_Heats.UseVisualStyleBackColor = true;
            // 
            // cbo_Contractor
            // 
            this.cbo_Contractor.Enabled = false;
            this.cbo_Contractor.FormattingEnabled = true;
            this.cbo_Contractor.Location = new System.Drawing.Point(247, 171);
            this.cbo_Contractor.Name = "cbo_Contractor";
            this.cbo_Contractor.Size = new System.Drawing.Size(115, 21);
            this.cbo_Contractor.TabIndex = 30;
            // 
            // cbx_EmPwr
            // 
            this.cbx_EmPwr.AutoSize = true;
            this.cbx_EmPwr.Enabled = false;
            this.cbx_EmPwr.Location = new System.Drawing.Point(112, 199);
            this.cbx_EmPwr.Name = "cbx_EmPwr";
            this.cbx_EmPwr.Size = new System.Drawing.Size(62, 17);
            this.cbx_EmPwr.TabIndex = 32;
            this.cbx_EmPwr.Text = "Em Pwr";
            this.cbx_EmPwr.UseVisualStyleBackColor = true;
            // 
            // cbx_FES
            // 
            this.cbx_FES.AutoSize = true;
            this.cbx_FES.Enabled = false;
            this.cbx_FES.Location = new System.Drawing.Point(60, 199);
            this.cbx_FES.Name = "cbx_FES";
            this.cbx_FES.Size = new System.Drawing.Size(46, 17);
            this.cbx_FES.TabIndex = 31;
            this.cbx_FES.Text = "FES";
            this.cbx_FES.UseVisualStyleBackColor = true;
            // 
            // btn_EditBuilding
            // 
            this.btn_EditBuilding.Location = new System.Drawing.Point(236, 19);
            this.btn_EditBuilding.Name = "btn_EditBuilding";
            this.btn_EditBuilding.Size = new System.Drawing.Size(56, 20);
            this.btn_EditBuilding.TabIndex = 29;
            this.btn_EditBuilding.Text = "Edit";
            this.btn_EditBuilding.UseVisualStyleBackColor = true;
            this.btn_EditBuilding.Click += new System.EventHandler(this.EnableEditing);
            // 
            // cbo_BuildingAnniversary
            // 
            this.cbo_BuildingAnniversary.BackColor = System.Drawing.SystemColors.Control;
            this.cbo_BuildingAnniversary.Enabled = false;
            this.cbo_BuildingAnniversary.FormattingEnabled = true;
            this.cbo_BuildingAnniversary.Items.AddRange(new object[] {
            "January",
            "February",
            "March",
            "April",
            "May",
            "June",
            "July",
            "August",
            "September",
            "October",
            "November",
            "December"});
            this.cbo_BuildingAnniversary.Location = new System.Drawing.Point(247, 144);
            this.cbo_BuildingAnniversary.MaxLength = 20;
            this.cbo_BuildingAnniversary.Name = "cbo_BuildingAnniversary";
            this.cbo_BuildingAnniversary.Size = new System.Drawing.Size(115, 21);
            this.cbo_BuildingAnniversary.TabIndex = 28;
            // 
            // cbo_BuildingCounty
            // 
            this.cbo_BuildingCounty.BackColor = System.Drawing.SystemColors.Control;
            this.cbo_BuildingCounty.Enabled = false;
            this.cbo_BuildingCounty.FormattingEnabled = true;
            this.cbo_BuildingCounty.Items.AddRange(new object[] {
            "Allegany",
            "Anne Arundel",
            "Baltimore",
            "Baltimore City",
            "Calvert",
            "Caroline",
            "Carroll",
            "Cecil",
            "Charles",
            "Dorchester",
            "Frederick",
            "Garrett",
            "Harford",
            "Howard",
            "Kent",
            "Montgomery",
            "Prince George\'s",
            "Queen Anne\'s",
            "Saint Mary\'s",
            "Somerset",
            "Talbot",
            "Washington",
            "Washington D.C.",
            "Wicomico",
            "Worcester"});
            this.cbo_BuildingCounty.Location = new System.Drawing.Point(59, 109);
            this.cbo_BuildingCounty.MaxLength = 30;
            this.cbo_BuildingCounty.Name = "cbo_BuildingCounty";
            this.cbo_BuildingCounty.Size = new System.Drawing.Size(113, 21);
            this.cbo_BuildingCounty.TabIndex = 27;
            // 
            // lvw_RelatedDocuments
            // 
            this.lvw_RelatedDocuments.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lvw_RelatedDocuments.Columns.AddRange(new System.Windows.Forms.ColumnHeader[] {
            this.col_Title,
            this.col_Desc});
            this.lvw_RelatedDocuments.Enabled = false;
            this.lvw_RelatedDocuments.Location = new System.Drawing.Point(302, 38);
            this.lvw_RelatedDocuments.Name = "lvw_RelatedDocuments";
            this.lvw_RelatedDocuments.Size = new System.Drawing.Size(266, 87);
            this.lvw_RelatedDocuments.TabIndex = 26;
            this.lvw_RelatedDocuments.UseCompatibleStateImageBehavior = false;
            this.lvw_RelatedDocuments.View = System.Windows.Forms.View.Details;
            // 
            // col_Title
            // 
            this.col_Title.Text = "Title";
            this.col_Title.Width = 100;
            // 
            // col_Desc
            // 
            this.col_Desc.Text = "Description";
            this.col_Desc.Width = 150;
            // 
            // btn_AddBldgDocument
            // 
            this.btn_AddBldgDocument.Enabled = false;
            this.btn_AddBldgDocument.Location = new System.Drawing.Point(479, 15);
            this.btn_AddBldgDocument.Name = "btn_AddBldgDocument";
            this.btn_AddBldgDocument.Size = new System.Drawing.Size(89, 20);
            this.btn_AddBldgDocument.TabIndex = 25;
            this.btn_AddBldgDocument.Text = "Add Document";
            this.btn_AddBldgDocument.UseVisualStyleBackColor = true;
            // 
            // lbx_ElevatorList
            // 
            this.lbx_ElevatorList.FormattingEnabled = true;
            this.lbx_ElevatorList.Location = new System.Drawing.Point(386, 134);
            this.lbx_ElevatorList.Name = "lbx_ElevatorList";
            this.lbx_ElevatorList.Size = new System.Drawing.Size(182, 82);
            this.lbx_ElevatorList.Sorted = true;
            this.lbx_ElevatorList.TabIndex = 7;
            this.lbx_ElevatorList.MouseDown += new System.Windows.Forms.MouseEventHandler(this.ElevatorList_RightClick);
            // 
            // btn_ViewMap
            // 
            this.btn_ViewMap.Enabled = false;
            this.btn_ViewMap.Location = new System.Drawing.Point(178, 107);
            this.btn_ViewMap.Name = "btn_ViewMap";
            this.btn_ViewMap.Size = new System.Drawing.Size(75, 23);
            this.btn_ViewMap.TabIndex = 7;
            this.btn_ViewMap.Text = "View Map";
            this.btn_ViewMap.UseVisualStyleBackColor = true;
            // 
            // lbl_Contractor
            // 
            this.lbl_Contractor.AutoSize = true;
            this.lbl_Contractor.Location = new System.Drawing.Point(181, 173);
            this.lbl_Contractor.Name = "lbl_Contractor";
            this.lbl_Contractor.Size = new System.Drawing.Size(59, 13);
            this.lbl_Contractor.TabIndex = 23;
            this.lbl_Contractor.Text = "Contractor:";
            // 
            // lbl_Anniversary
            // 
            this.lbl_Anniversary.AutoSize = true;
            this.lbl_Anniversary.Location = new System.Drawing.Point(175, 147);
            this.lbl_Anniversary.Name = "lbl_Anniversary";
            this.lbl_Anniversary.Size = new System.Drawing.Size(65, 13);
            this.lbl_Anniversary.TabIndex = 21;
            this.lbl_Anniversary.Text = "Anniversary:";
            // 
            // txt_HourlyFee
            // 
            this.txt_HourlyFee.Location = new System.Drawing.Point(60, 170);
            this.txt_HourlyFee.Name = "txt_HourlyFee";
            this.txt_HourlyFee.ReadOnly = true;
            this.txt_HourlyFee.Size = new System.Drawing.Size(79, 20);
            this.txt_HourlyFee.TabIndex = 20;
            // 
            // lbl_HourlyFee
            // 
            this.lbl_HourlyFee.AutoSize = true;
            this.lbl_HourlyFee.Location = new System.Drawing.Point(11, 173);
            this.lbl_HourlyFee.Name = "lbl_HourlyFee";
            this.lbl_HourlyFee.Size = new System.Drawing.Size(40, 13);
            this.lbl_HourlyFee.TabIndex = 19;
            this.lbl_HourlyFee.Text = "Hourly:";
            // 
            // txt_FirmFee
            // 
            this.txt_FirmFee.Location = new System.Drawing.Point(59, 144);
            this.txt_FirmFee.Name = "txt_FirmFee";
            this.txt_FirmFee.ReadOnly = true;
            this.txt_FirmFee.Size = new System.Drawing.Size(79, 20);
            this.txt_FirmFee.TabIndex = 16;
            // 
            // lbl_FirmFee
            // 
            this.lbl_FirmFee.AutoSize = true;
            this.lbl_FirmFee.Location = new System.Drawing.Point(10, 147);
            this.lbl_FirmFee.Name = "lbl_FirmFee";
            this.lbl_FirmFee.Size = new System.Drawing.Size(29, 13);
            this.lbl_FirmFee.TabIndex = 15;
            this.lbl_FirmFee.Text = "Firm:";
            // 
            // lbl_BuildingCounty
            // 
            this.lbl_BuildingCounty.AutoSize = true;
            this.lbl_BuildingCounty.Location = new System.Drawing.Point(10, 112);
            this.lbl_BuildingCounty.Name = "lbl_BuildingCounty";
            this.lbl_BuildingCounty.Size = new System.Drawing.Size(43, 13);
            this.lbl_BuildingCounty.TabIndex = 7;
            this.lbl_BuildingCounty.Text = "County:";
            // 
            // lbl_RelatedDocs
            // 
            this.lbl_RelatedDocs.AutoSize = true;
            this.lbl_RelatedDocs.Location = new System.Drawing.Point(299, 22);
            this.lbl_RelatedDocs.Name = "lbl_RelatedDocs";
            this.lbl_RelatedDocs.Size = new System.Drawing.Size(101, 13);
            this.lbl_RelatedDocs.TabIndex = 13;
            this.lbl_RelatedDocs.Text = "Related Documents";
            // 
            // txt_BuildingName
            // 
            this.txt_BuildingName.Location = new System.Drawing.Point(59, 19);
            this.txt_BuildingName.MaxLength = 50;
            this.txt_BuildingName.Name = "txt_BuildingName";
            this.txt_BuildingName.ReadOnly = true;
            this.txt_BuildingName.Size = new System.Drawing.Size(171, 20);
            this.txt_BuildingName.TabIndex = 6;
            // 
            // lbl_BuildingName
            // 
            this.lbl_BuildingName.AutoSize = true;
            this.lbl_BuildingName.Location = new System.Drawing.Point(15, 22);
            this.lbl_BuildingName.Name = "lbl_BuildingName";
            this.lbl_BuildingName.Size = new System.Drawing.Size(38, 13);
            this.lbl_BuildingName.TabIndex = 6;
            this.lbl_BuildingName.Text = "Name:";
            // 
            // cbx_BuildingActive
            // 
            this.cbx_BuildingActive.AutoSize = true;
            this.cbx_BuildingActive.Enabled = false;
            this.cbx_BuildingActive.Location = new System.Drawing.Point(240, 73);
            this.cbx_BuildingActive.Name = "cbx_BuildingActive";
            this.cbx_BuildingActive.Size = new System.Drawing.Size(56, 17);
            this.cbx_BuildingActive.TabIndex = 12;
            this.cbx_BuildingActive.Text = "Active";
            this.cbx_BuildingActive.UseVisualStyleBackColor = true;
            // 
            // lbl_BuildingAddress
            // 
            this.lbl_BuildingAddress.AutoSize = true;
            this.lbl_BuildingAddress.Location = new System.Drawing.Point(5, 48);
            this.lbl_BuildingAddress.Name = "lbl_BuildingAddress";
            this.lbl_BuildingAddress.Size = new System.Drawing.Size(48, 13);
            this.lbl_BuildingAddress.TabIndex = 7;
            this.lbl_BuildingAddress.Text = "Address:";
            // 
            // txt_BuildingZip
            // 
            this.txt_BuildingZip.Location = new System.Drawing.Point(178, 71);
            this.txt_BuildingZip.MaxLength = 5;
            this.txt_BuildingZip.Name = "txt_BuildingZip";
            this.txt_BuildingZip.ReadOnly = true;
            this.txt_BuildingZip.Size = new System.Drawing.Size(52, 20);
            this.txt_BuildingZip.TabIndex = 11;
            // 
            // txt_BuildingAddress
            // 
            this.txt_BuildingAddress.Location = new System.Drawing.Point(59, 45);
            this.txt_BuildingAddress.MaxLength = 50;
            this.txt_BuildingAddress.Name = "txt_BuildingAddress";
            this.txt_BuildingAddress.ReadOnly = true;
            this.txt_BuildingAddress.Size = new System.Drawing.Size(171, 20);
            this.txt_BuildingAddress.TabIndex = 8;
            // 
            // txt_BuildingState
            // 
            this.txt_BuildingState.Location = new System.Drawing.Point(145, 71);
            this.txt_BuildingState.MaxLength = 2;
            this.txt_BuildingState.Name = "txt_BuildingState";
            this.txt_BuildingState.ReadOnly = true;
            this.txt_BuildingState.Size = new System.Drawing.Size(27, 20);
            this.txt_BuildingState.TabIndex = 10;
            // 
            // txt_BuildingCity
            // 
            this.txt_BuildingCity.Location = new System.Drawing.Point(59, 71);
            this.txt_BuildingCity.MaxLength = 30;
            this.txt_BuildingCity.Name = "txt_BuildingCity";
            this.txt_BuildingCity.ReadOnly = true;
            this.txt_BuildingCity.Size = new System.Drawing.Size(80, 20);
            this.txt_BuildingCity.TabIndex = 9;
            // 
            // gbx_Company
            // 
            this.gbx_Company.Controls.Add(this.btn_EditCompany);
            this.gbx_Company.Controls.Add(this.txt_CompanyName);
            this.gbx_Company.Controls.Add(this.lbl_OtherBuildings);
            this.gbx_Company.Controls.Add(this.lbl_CompanyName);
            this.gbx_Company.Controls.Add(this.lbx_OtherCompanyBuildings);
            this.gbx_Company.Controls.Add(this.lbl_CompanyAddress);
            this.gbx_Company.Controls.Add(this.txt_CompanyCity);
            this.gbx_Company.Controls.Add(this.txt_CompanyZip);
            this.gbx_Company.Controls.Add(this.txt_CompanyState);
            this.gbx_Company.Controls.Add(this.txt_CompanyStreet);
            this.gbx_Company.Location = new System.Drawing.Point(248, 92);
            this.gbx_Company.Name = "gbx_Company";
            this.gbx_Company.Size = new System.Drawing.Size(574, 118);
            this.gbx_Company.TabIndex = 6;
            this.gbx_Company.TabStop = false;
            this.gbx_Company.Text = "Company";
            // 
            // btn_EditCompany
            // 
            this.btn_EditCompany.Location = new System.Drawing.Point(236, 19);
            this.btn_EditCompany.Name = "btn_EditCompany";
            this.btn_EditCompany.Size = new System.Drawing.Size(56, 20);
            this.btn_EditCompany.TabIndex = 9;
            this.btn_EditCompany.Text = "Edit";
            this.btn_EditCompany.UseVisualStyleBackColor = true;
            this.btn_EditCompany.Click += new System.EventHandler(this.EnableEditing);
            // 
            // txt_CompanyName
            // 
            this.txt_CompanyName.Location = new System.Drawing.Point(59, 19);
            this.txt_CompanyName.MaxLength = 60;
            this.txt_CompanyName.Name = "txt_CompanyName";
            this.txt_CompanyName.ReadOnly = true;
            this.txt_CompanyName.Size = new System.Drawing.Size(171, 20);
            this.txt_CompanyName.TabIndex = 14;
            // 
            // lbl_OtherBuildings
            // 
            this.lbl_OtherBuildings.AutoSize = true;
            this.lbl_OtherBuildings.Location = new System.Drawing.Point(299, 14);
            this.lbl_OtherBuildings.Name = "lbl_OtherBuildings";
            this.lbl_OtherBuildings.Size = new System.Drawing.Size(157, 13);
            this.lbl_OtherBuildings.TabIndex = 13;
            this.lbl_OtherBuildings.Text = "Other Buildings Under Company";
            // 
            // lbl_CompanyName
            // 
            this.lbl_CompanyName.AutoSize = true;
            this.lbl_CompanyName.Location = new System.Drawing.Point(15, 22);
            this.lbl_CompanyName.Name = "lbl_CompanyName";
            this.lbl_CompanyName.Size = new System.Drawing.Size(38, 13);
            this.lbl_CompanyName.TabIndex = 15;
            this.lbl_CompanyName.Text = "Name:";
            // 
            // lbx_OtherCompanyBuildings
            // 
            this.lbx_OtherCompanyBuildings.FormattingEnabled = true;
            this.lbx_OtherCompanyBuildings.Location = new System.Drawing.Point(302, 30);
            this.lbx_OtherCompanyBuildings.Name = "lbx_OtherCompanyBuildings";
            this.lbx_OtherCompanyBuildings.Size = new System.Drawing.Size(266, 82);
            this.lbx_OtherCompanyBuildings.Sorted = true;
            this.lbx_OtherCompanyBuildings.TabIndex = 7;
            this.lbx_OtherCompanyBuildings.SelectedIndexChanged += new System.EventHandler(this.ListBox_ItemSelected);
            // 
            // lbl_CompanyAddress
            // 
            this.lbl_CompanyAddress.AutoSize = true;
            this.lbl_CompanyAddress.Location = new System.Drawing.Point(5, 48);
            this.lbl_CompanyAddress.Name = "lbl_CompanyAddress";
            this.lbl_CompanyAddress.Size = new System.Drawing.Size(48, 13);
            this.lbl_CompanyAddress.TabIndex = 16;
            this.lbl_CompanyAddress.Text = "Address:";
            // 
            // txt_CompanyCity
            // 
            this.txt_CompanyCity.Location = new System.Drawing.Point(59, 71);
            this.txt_CompanyCity.MaxLength = 30;
            this.txt_CompanyCity.Name = "txt_CompanyCity";
            this.txt_CompanyCity.ReadOnly = true;
            this.txt_CompanyCity.Size = new System.Drawing.Size(80, 20);
            this.txt_CompanyCity.TabIndex = 18;
            // 
            // txt_CompanyZip
            // 
            this.txt_CompanyZip.Location = new System.Drawing.Point(178, 71);
            this.txt_CompanyZip.MaxLength = 5;
            this.txt_CompanyZip.Name = "txt_CompanyZip";
            this.txt_CompanyZip.ReadOnly = true;
            this.txt_CompanyZip.Size = new System.Drawing.Size(52, 20);
            this.txt_CompanyZip.TabIndex = 20;
            // 
            // txt_CompanyState
            // 
            this.txt_CompanyState.Location = new System.Drawing.Point(145, 71);
            this.txt_CompanyState.MaxLength = 2;
            this.txt_CompanyState.Name = "txt_CompanyState";
            this.txt_CompanyState.ReadOnly = true;
            this.txt_CompanyState.Size = new System.Drawing.Size(27, 20);
            this.txt_CompanyState.TabIndex = 19;
            // 
            // txt_CompanyStreet
            // 
            this.txt_CompanyStreet.Location = new System.Drawing.Point(59, 45);
            this.txt_CompanyStreet.MaxLength = 50;
            this.txt_CompanyStreet.Name = "txt_CompanyStreet";
            this.txt_CompanyStreet.ReadOnly = true;
            this.txt_CompanyStreet.Size = new System.Drawing.Size(171, 20);
            this.txt_CompanyStreet.TabIndex = 17;
            // 
            // tab_BuildingCompanySelector
            // 
            this.tab_BuildingCompanySelector.Controls.Add(this.tab_ByCompany);
            this.tab_BuildingCompanySelector.Controls.Add(this.tab_ByBuilding);
            this.tab_BuildingCompanySelector.HotTrack = true;
            this.tab_BuildingCompanySelector.Location = new System.Drawing.Point(6, 6);
            this.tab_BuildingCompanySelector.Name = "tab_BuildingCompanySelector";
            this.tab_BuildingCompanySelector.SelectedIndex = 0;
            this.tab_BuildingCompanySelector.Size = new System.Drawing.Size(229, 880);
            this.tab_BuildingCompanySelector.TabIndex = 3;
            this.tab_BuildingCompanySelector.SelectedIndexChanged += new System.EventHandler(this.Filter_TextChanged);
            // 
            // tab_ByCompany
            // 
            this.tab_ByCompany.Controls.Add(this.lbx_CompanyList);
            this.tab_ByCompany.Controls.Add(this.txt_FilterCompany);
            this.tab_ByCompany.Location = new System.Drawing.Point(4, 22);
            this.tab_ByCompany.Name = "tab_ByCompany";
            this.tab_ByCompany.Padding = new System.Windows.Forms.Padding(3);
            this.tab_ByCompany.Size = new System.Drawing.Size(221, 854);
            this.tab_ByCompany.TabIndex = 0;
            this.tab_ByCompany.Text = "By Company";
            this.tab_ByCompany.UseVisualStyleBackColor = true;
            // 
            // lbx_CompanyList
            // 
            this.lbx_CompanyList.FormattingEnabled = true;
            this.lbx_CompanyList.Location = new System.Drawing.Point(6, 32);
            this.lbx_CompanyList.Name = "lbx_CompanyList";
            this.lbx_CompanyList.Size = new System.Drawing.Size(209, 810);
            this.lbx_CompanyList.Sorted = true;
            this.lbx_CompanyList.TabIndex = 1;
            this.lbx_CompanyList.SelectedIndexChanged += new System.EventHandler(this.ListBox_ItemSelected);
            // 
            // txt_FilterCompany
            // 
            this.txt_FilterCompany.Location = new System.Drawing.Point(6, 6);
            this.txt_FilterCompany.Name = "txt_FilterCompany";
            this.txt_FilterCompany.Size = new System.Drawing.Size(209, 20);
            this.txt_FilterCompany.TabIndex = 0;
            this.txt_FilterCompany.TextChanged += new System.EventHandler(this.Filter_TextChanged);
            // 
            // tab_ByBuilding
            // 
            this.tab_ByBuilding.Controls.Add(this.lbx_BuildingList);
            this.tab_ByBuilding.Controls.Add(this.txt_FilterAddress);
            this.tab_ByBuilding.Location = new System.Drawing.Point(4, 22);
            this.tab_ByBuilding.Name = "tab_ByBuilding";
            this.tab_ByBuilding.Padding = new System.Windows.Forms.Padding(3);
            this.tab_ByBuilding.Size = new System.Drawing.Size(221, 854);
            this.tab_ByBuilding.TabIndex = 1;
            this.tab_ByBuilding.Text = "By Address";
            this.tab_ByBuilding.UseVisualStyleBackColor = true;
            // 
            // lbx_BuildingList
            // 
            this.lbx_BuildingList.FormattingEnabled = true;
            this.lbx_BuildingList.Location = new System.Drawing.Point(6, 32);
            this.lbx_BuildingList.Name = "lbx_BuildingList";
            this.lbx_BuildingList.Size = new System.Drawing.Size(209, 810);
            this.lbx_BuildingList.Sorted = true;
            this.lbx_BuildingList.TabIndex = 1;
            this.lbx_BuildingList.SelectedIndexChanged += new System.EventHandler(this.ListBox_ItemSelected);
            // 
            // txt_FilterAddress
            // 
            this.txt_FilterAddress.Location = new System.Drawing.Point(6, 6);
            this.txt_FilterAddress.Name = "txt_FilterAddress";
            this.txt_FilterAddress.Size = new System.Drawing.Size(209, 20);
            this.txt_FilterAddress.TabIndex = 0;
            this.txt_FilterAddress.TextChanged += new System.EventHandler(this.Filter_TextChanged);
            // 
            // gbx_ResultFilters
            // 
            this.gbx_ResultFilters.Controls.Add(this.cbx_ShowInactive);
            this.gbx_ResultFilters.Controls.Add(this.cbx_ShowDC);
            this.gbx_ResultFilters.Controls.Add(this.cbx_ShowMD);
            this.gbx_ResultFilters.Location = new System.Drawing.Point(12, 27);
            this.gbx_ResultFilters.Name = "gbx_ResultFilters";
            this.gbx_ResultFilters.Size = new System.Drawing.Size(391, 40);
            this.gbx_ResultFilters.TabIndex = 2;
            this.gbx_ResultFilters.TabStop = false;
            this.gbx_ResultFilters.Text = "Filters";
            // 
            // cbx_ShowInactive
            // 
            this.cbx_ShowInactive.AutoSize = true;
            this.cbx_ShowInactive.Location = new System.Drawing.Point(252, 18);
            this.cbx_ShowInactive.Name = "cbx_ShowInactive";
            this.cbx_ShowInactive.Size = new System.Drawing.Size(99, 17);
            this.cbx_ShowInactive.TabIndex = 2;
            this.cbx_ShowInactive.Text = "Show Inactives";
            this.cbx_ShowInactive.UseVisualStyleBackColor = true;
            this.cbx_ShowInactive.CheckedChanged += new System.EventHandler(this.FilterChanged);
            // 
            // cbx_ShowDC
            // 
            this.cbx_ShowDC.AutoSize = true;
            this.cbx_ShowDC.Location = new System.Drawing.Point(130, 19);
            this.cbx_ShowDC.Name = "cbx_ShowDC";
            this.cbx_ShowDC.Size = new System.Drawing.Size(116, 17);
            this.cbx_ShowDC.TabIndex = 1;
            this.cbx_ShowDC.Text = "Show DC Buildings";
            this.cbx_ShowDC.UseVisualStyleBackColor = true;
            this.cbx_ShowDC.CheckedChanged += new System.EventHandler(this.FilterChanged);
            // 
            // cbx_ShowMD
            // 
            this.cbx_ShowMD.AutoSize = true;
            this.cbx_ShowMD.Location = new System.Drawing.Point(6, 19);
            this.cbx_ShowMD.Name = "cbx_ShowMD";
            this.cbx_ShowMD.Size = new System.Drawing.Size(118, 17);
            this.cbx_ShowMD.TabIndex = 0;
            this.cbx_ShowMD.Text = "Show MD Buildings";
            this.cbx_ShowMD.UseVisualStyleBackColor = true;
            this.cbx_ShowMD.CheckedChanged += new System.EventHandler(this.FilterChanged);
            // 
            // tab_MainTabControl
            // 
            this.tab_MainTabControl.Controls.Add(this.tab_DatabaseBrowser);
            this.tab_MainTabControl.Controls.Add(this.tab_UpcomingAndOverdue);
            this.tab_MainTabControl.Controls.Add(this.tab_Calendar);
            this.tab_MainTabControl.Location = new System.Drawing.Point(12, 73);
            this.tab_MainTabControl.Name = "tab_MainTabControl";
            this.tab_MainTabControl.SelectedIndex = 0;
            this.tab_MainTabControl.Size = new System.Drawing.Size(902, 930);
            this.tab_MainTabControl.TabIndex = 8;
            this.tab_MainTabControl.SelectedIndexChanged += new System.EventHandler(this.MainTabChanged);
            // 
            // tab_DatabaseBrowser
            // 
            this.tab_DatabaseBrowser.Controls.Add(this.gbx_ButtonContainer);
            this.tab_DatabaseBrowser.Controls.Add(this.gbx_Contacts);
            this.tab_DatabaseBrowser.Controls.Add(this.gbx_InspectionHistory);
            this.tab_DatabaseBrowser.Controls.Add(this.gbx_Building);
            this.tab_DatabaseBrowser.Controls.Add(this.tab_BuildingCompanySelector);
            this.tab_DatabaseBrowser.Controls.Add(this.gbx_Company);
            this.tab_DatabaseBrowser.Location = new System.Drawing.Point(4, 22);
            this.tab_DatabaseBrowser.Name = "tab_DatabaseBrowser";
            this.tab_DatabaseBrowser.Padding = new System.Windows.Forms.Padding(3);
            this.tab_DatabaseBrowser.Size = new System.Drawing.Size(894, 904);
            this.tab_DatabaseBrowser.TabIndex = 0;
            this.tab_DatabaseBrowser.Text = "Database Browser";
            this.tab_DatabaseBrowser.UseVisualStyleBackColor = true;
            // 
            // gbx_ButtonContainer
            // 
            this.gbx_ButtonContainer.Controls.Add(this.btn_NewElevator);
            this.gbx_ButtonContainer.Controls.Add(this.btn_NewBuilding);
            this.gbx_ButtonContainer.Controls.Add(this.btn_AddNewCompany);
            this.gbx_ButtonContainer.Location = new System.Drawing.Point(248, 11);
            this.gbx_ButtonContainer.Name = "gbx_ButtonContainer";
            this.gbx_ButtonContainer.Size = new System.Drawing.Size(574, 75);
            this.gbx_ButtonContainer.TabIndex = 9;
            this.gbx_ButtonContainer.TabStop = false;
            this.gbx_ButtonContainer.Text = "Database Operations";
            // 
            // btn_NewElevator
            // 
            this.btn_NewElevator.Location = new System.Drawing.Point(204, 19);
            this.btn_NewElevator.Name = "btn_NewElevator";
            this.btn_NewElevator.Size = new System.Drawing.Size(93, 23);
            this.btn_NewElevator.TabIndex = 9;
            this.btn_NewElevator.Text = "New Elevator";
            this.btn_NewElevator.UseVisualStyleBackColor = true;
            this.btn_NewElevator.Click += new System.EventHandler(this.OpenChildForm);
            // 
            // btn_NewBuilding
            // 
            this.btn_NewBuilding.Location = new System.Drawing.Point(105, 19);
            this.btn_NewBuilding.Name = "btn_NewBuilding";
            this.btn_NewBuilding.Size = new System.Drawing.Size(93, 23);
            this.btn_NewBuilding.TabIndex = 10;
            this.btn_NewBuilding.Text = "New Building";
            this.btn_NewBuilding.UseVisualStyleBackColor = true;
            this.btn_NewBuilding.Click += new System.EventHandler(this.OpenChildForm);
            // 
            // btn_AddNewCompany
            // 
            this.btn_AddNewCompany.Location = new System.Drawing.Point(6, 19);
            this.btn_AddNewCompany.Name = "btn_AddNewCompany";
            this.btn_AddNewCompany.Size = new System.Drawing.Size(93, 23);
            this.btn_AddNewCompany.TabIndex = 9;
            this.btn_AddNewCompany.Text = "New Company";
            this.btn_AddNewCompany.UseVisualStyleBackColor = true;
            this.btn_AddNewCompany.Click += new System.EventHandler(this.OpenChildForm);
            // 
            // gbx_Contacts
            // 
            this.gbx_Contacts.Controls.Add(this.gbx_ContactInfo);
            this.gbx_Contacts.Controls.Add(this.lbl_BuildingContacts);
            this.gbx_Contacts.Controls.Add(this.lbx_BuildingContacts);
            this.gbx_Contacts.Controls.Add(this.lbl_CompanyContacts);
            this.gbx_Contacts.Controls.Add(this.lbx_CompanyContacts);
            this.gbx_Contacts.Location = new System.Drawing.Point(248, 533);
            this.gbx_Contacts.Name = "gbx_Contacts";
            this.gbx_Contacts.Size = new System.Drawing.Size(574, 177);
            this.gbx_Contacts.TabIndex = 9;
            this.gbx_Contacts.TabStop = false;
            this.gbx_Contacts.Text = "Contacts";
            // 
            // gbx_ContactInfo
            // 
            this.gbx_ContactInfo.Controls.Add(this.btn_EditContact);
            this.gbx_ContactInfo.Controls.Add(this.txt_Fax);
            this.gbx_ContactInfo.Controls.Add(this.txt_CellPhone);
            this.gbx_ContactInfo.Controls.Add(this.txt_OfficePhone);
            this.gbx_ContactInfo.Controls.Add(this.txt_Email);
            this.gbx_ContactInfo.Controls.Add(this.lbl_ContactEmail);
            this.gbx_ContactInfo.Controls.Add(this.lbl_ContactFax);
            this.gbx_ContactInfo.Controls.Add(this.lbl_ContactCellPhone);
            this.gbx_ContactInfo.Controls.Add(this.lbl_ContactOfficePhone);
            this.gbx_ContactInfo.Controls.Add(this.lbl_ContactName);
            this.gbx_ContactInfo.Controls.Add(this.txt_ContactName);
            this.gbx_ContactInfo.Location = new System.Drawing.Point(144, 16);
            this.gbx_ContactInfo.Name = "gbx_ContactInfo";
            this.gbx_ContactInfo.Size = new System.Drawing.Size(256, 153);
            this.gbx_ContactInfo.TabIndex = 14;
            this.gbx_ContactInfo.TabStop = false;
            this.gbx_ContactInfo.Text = "Selected Contact";
            // 
            // btn_EditContact
            // 
            this.btn_EditContact.Location = new System.Drawing.Point(190, 71);
            this.btn_EditContact.Name = "btn_EditContact";
            this.btn_EditContact.Size = new System.Drawing.Size(56, 20);
            this.btn_EditContact.TabIndex = 25;
            this.btn_EditContact.Text = "Edit";
            this.btn_EditContact.UseVisualStyleBackColor = true;
            this.btn_EditContact.Click += new System.EventHandler(this.EnableEditing);
            // 
            // txt_Fax
            // 
            this.txt_Fax.Location = new System.Drawing.Point(84, 97);
            this.txt_Fax.Name = "txt_Fax";
            this.txt_Fax.ReadOnly = true;
            this.txt_Fax.Size = new System.Drawing.Size(100, 20);
            this.txt_Fax.TabIndex = 24;
            // 
            // txt_CellPhone
            // 
            this.txt_CellPhone.Location = new System.Drawing.Point(84, 71);
            this.txt_CellPhone.Name = "txt_CellPhone";
            this.txt_CellPhone.ReadOnly = true;
            this.txt_CellPhone.Size = new System.Drawing.Size(100, 20);
            this.txt_CellPhone.TabIndex = 23;
            // 
            // txt_OfficePhone
            // 
            this.txt_OfficePhone.Location = new System.Drawing.Point(84, 45);
            this.txt_OfficePhone.Name = "txt_OfficePhone";
            this.txt_OfficePhone.ReadOnly = true;
            this.txt_OfficePhone.Size = new System.Drawing.Size(125, 20);
            this.txt_OfficePhone.TabIndex = 22;
            // 
            // txt_Email
            // 
            this.txt_Email.Location = new System.Drawing.Point(84, 123);
            this.txt_Email.MaxLength = 50;
            this.txt_Email.Name = "txt_Email";
            this.txt_Email.ReadOnly = true;
            this.txt_Email.Size = new System.Drawing.Size(160, 20);
            this.txt_Email.TabIndex = 21;
            // 
            // lbl_ContactEmail
            // 
            this.lbl_ContactEmail.AutoSize = true;
            this.lbl_ContactEmail.Location = new System.Drawing.Point(39, 126);
            this.lbl_ContactEmail.Name = "lbl_ContactEmail";
            this.lbl_ContactEmail.Size = new System.Drawing.Size(39, 13);
            this.lbl_ContactEmail.TabIndex = 20;
            this.lbl_ContactEmail.Text = "E-Mail:";
            // 
            // lbl_ContactFax
            // 
            this.lbl_ContactFax.AutoSize = true;
            this.lbl_ContactFax.Location = new System.Drawing.Point(51, 100);
            this.lbl_ContactFax.Name = "lbl_ContactFax";
            this.lbl_ContactFax.Size = new System.Drawing.Size(27, 13);
            this.lbl_ContactFax.TabIndex = 18;
            this.lbl_ContactFax.Text = "Fax:";
            // 
            // lbl_ContactCellPhone
            // 
            this.lbl_ContactCellPhone.AutoSize = true;
            this.lbl_ContactCellPhone.Location = new System.Drawing.Point(17, 74);
            this.lbl_ContactCellPhone.Name = "lbl_ContactCellPhone";
            this.lbl_ContactCellPhone.Size = new System.Drawing.Size(61, 13);
            this.lbl_ContactCellPhone.TabIndex = 16;
            this.lbl_ContactCellPhone.Text = "Cell Phone:";
            // 
            // lbl_ContactOfficePhone
            // 
            this.lbl_ContactOfficePhone.AutoSize = true;
            this.lbl_ContactOfficePhone.Location = new System.Drawing.Point(6, 48);
            this.lbl_ContactOfficePhone.Name = "lbl_ContactOfficePhone";
            this.lbl_ContactOfficePhone.Size = new System.Drawing.Size(72, 13);
            this.lbl_ContactOfficePhone.TabIndex = 14;
            this.lbl_ContactOfficePhone.Text = "Office Phone:";
            // 
            // lbl_ContactName
            // 
            this.lbl_ContactName.AutoSize = true;
            this.lbl_ContactName.Location = new System.Drawing.Point(39, 22);
            this.lbl_ContactName.Name = "lbl_ContactName";
            this.lbl_ContactName.Size = new System.Drawing.Size(38, 13);
            this.lbl_ContactName.TabIndex = 9;
            this.lbl_ContactName.Text = "Name:";
            // 
            // txt_ContactName
            // 
            this.txt_ContactName.Location = new System.Drawing.Point(84, 19);
            this.txt_ContactName.MaxLength = 30;
            this.txt_ContactName.Name = "txt_ContactName";
            this.txt_ContactName.ReadOnly = true;
            this.txt_ContactName.Size = new System.Drawing.Size(160, 20);
            this.txt_ContactName.TabIndex = 13;
            // 
            // lbl_BuildingContacts
            // 
            this.lbl_BuildingContacts.AutoSize = true;
            this.lbl_BuildingContacts.Location = new System.Drawing.Point(7, 97);
            this.lbl_BuildingContacts.Name = "lbl_BuildingContacts";
            this.lbl_BuildingContacts.Size = new System.Drawing.Size(92, 13);
            this.lbl_BuildingContacts.TabIndex = 12;
            this.lbl_BuildingContacts.Text = "Building Contacts:";
            // 
            // lbx_BuildingContacts
            // 
            this.lbx_BuildingContacts.FormattingEnabled = true;
            this.lbx_BuildingContacts.Location = new System.Drawing.Point(9, 113);
            this.lbx_BuildingContacts.Name = "lbx_BuildingContacts";
            this.lbx_BuildingContacts.Size = new System.Drawing.Size(120, 56);
            this.lbx_BuildingContacts.TabIndex = 11;
            this.lbx_BuildingContacts.Click += new System.EventHandler(this.Contact_Selected);
            this.lbx_BuildingContacts.MouseDown += new System.Windows.Forms.MouseEventHandler(this.Contacts_MouseClick);
            // 
            // lbl_CompanyContacts
            // 
            this.lbl_CompanyContacts.AutoSize = true;
            this.lbl_CompanyContacts.Location = new System.Drawing.Point(6, 16);
            this.lbl_CompanyContacts.Name = "lbl_CompanyContacts";
            this.lbl_CompanyContacts.Size = new System.Drawing.Size(99, 13);
            this.lbl_CompanyContacts.TabIndex = 10;
            this.lbl_CompanyContacts.Text = "Company Contacts:";
            // 
            // lbx_CompanyContacts
            // 
            this.lbx_CompanyContacts.FormattingEnabled = true;
            this.lbx_CompanyContacts.Location = new System.Drawing.Point(9, 32);
            this.lbx_CompanyContacts.Name = "lbx_CompanyContacts";
            this.lbx_CompanyContacts.Size = new System.Drawing.Size(120, 56);
            this.lbx_CompanyContacts.TabIndex = 9;
            this.lbx_CompanyContacts.Click += new System.EventHandler(this.Contact_Selected);
            this.lbx_CompanyContacts.MouseDown += new System.Windows.Forms.MouseEventHandler(this.Contacts_MouseClick);
            // 
            // tab_UpcomingAndOverdue
            // 
            this.tab_UpcomingAndOverdue.Controls.Add(this.groupBox1);
            this.tab_UpcomingAndOverdue.Controls.Add(this.tlp_UpcomingAndOverdue);
            this.tab_UpcomingAndOverdue.Location = new System.Drawing.Point(4, 22);
            this.tab_UpcomingAndOverdue.Name = "tab_UpcomingAndOverdue";
            this.tab_UpcomingAndOverdue.Padding = new System.Windows.Forms.Padding(3);
            this.tab_UpcomingAndOverdue.Size = new System.Drawing.Size(894, 904);
            this.tab_UpcomingAndOverdue.TabIndex = 1;
            this.tab_UpcomingAndOverdue.Text = "Upcoming / Overdue ";
            this.tab_UpcomingAndOverdue.UseVisualStyleBackColor = true;
            // 
            // groupBox1
            // 
            this.groupBox1.Controls.Add(this.gbx_CurrentSchedule);
            this.groupBox1.Controls.Add(this.cal_CalendarDisplay);
            this.groupBox1.Controls.Add(this.gbx_NextAvailable);
            this.groupBox1.Controls.Add(this.lbl_InspectorToSchedule);
            this.groupBox1.Controls.Add(this.cbo_InspectorToSchedule);
            this.groupBox1.Location = new System.Drawing.Point(427, 9);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new System.Drawing.Size(461, 536);
            this.groupBox1.TabIndex = 9;
            this.groupBox1.TabStop = false;
            this.groupBox1.Text = "Scheduling";
            this.groupBox1.Visible = false;
            // 
            // gbx_CurrentSchedule
            // 
            this.gbx_CurrentSchedule.Controls.Add(this.lbx_CurrentSchedule);
            this.gbx_CurrentSchedule.Location = new System.Drawing.Point(12, 221);
            this.gbx_CurrentSchedule.Name = "gbx_CurrentSchedule";
            this.gbx_CurrentSchedule.Size = new System.Drawing.Size(227, 153);
            this.gbx_CurrentSchedule.TabIndex = 4;
            this.gbx_CurrentSchedule.TabStop = false;
            this.gbx_CurrentSchedule.Text = "Schedule";
            // 
            // lbx_CurrentSchedule
            // 
            this.lbx_CurrentSchedule.FormattingEnabled = true;
            this.lbx_CurrentSchedule.Location = new System.Drawing.Point(6, 19);
            this.lbx_CurrentSchedule.Name = "lbx_CurrentSchedule";
            this.lbx_CurrentSchedule.Size = new System.Drawing.Size(215, 121);
            this.lbx_CurrentSchedule.TabIndex = 5;
            // 
            // cal_CalendarDisplay
            // 
            this.cal_CalendarDisplay.Location = new System.Drawing.Point(12, 52);
            this.cal_CalendarDisplay.Name = "cal_CalendarDisplay";
            this.cal_CalendarDisplay.TabIndex = 3;
            this.cal_CalendarDisplay.DateChanged += new System.Windows.Forms.DateRangeEventHandler(this.CalendarDisplay_DateChanged);
            // 
            // gbx_NextAvailable
            // 
            this.gbx_NextAvailable.Controls.Add(this.cbx_Sundays);
            this.gbx_NextAvailable.Controls.Add(this.cbx_Saturdays);
            this.gbx_NextAvailable.Controls.Add(this.cbx_Weekdays);
            this.gbx_NextAvailable.Controls.Add(this.lbl_StartDate);
            this.gbx_NextAvailable.Controls.Add(this.dtp_StartDate);
            this.gbx_NextAvailable.Controls.Add(this.lbx_PossibleAppointments);
            this.gbx_NextAvailable.Controls.Add(this.lbl_HoursNeeded);
            this.gbx_NextAvailable.Controls.Add(this.nym_HoursNeeded);
            this.gbx_NextAvailable.Controls.Add(this.lbl_NoLaterThan);
            this.gbx_NextAvailable.Controls.Add(this.dtp_NoLaterThan);
            this.gbx_NextAvailable.Controls.Add(this.lbl_NoEarlierThan);
            this.gbx_NextAvailable.Controls.Add(this.dtp_NoEarlierThan);
            this.gbx_NextAvailable.Location = new System.Drawing.Point(251, 19);
            this.gbx_NextAvailable.Name = "gbx_NextAvailable";
            this.gbx_NextAvailable.Size = new System.Drawing.Size(204, 327);
            this.gbx_NextAvailable.TabIndex = 2;
            this.gbx_NextAvailable.TabStop = false;
            this.gbx_NextAvailable.Text = "Next Available Appointments";
            // 
            // cbx_Sundays
            // 
            this.cbx_Sundays.AutoSize = true;
            this.cbx_Sundays.Location = new System.Drawing.Point(96, 210);
            this.cbx_Sundays.Name = "cbx_Sundays";
            this.cbx_Sundays.Size = new System.Drawing.Size(67, 17);
            this.cbx_Sundays.TabIndex = 11;
            this.cbx_Sundays.Text = "Sundays";
            this.cbx_Sundays.UseVisualStyleBackColor = true;
            // 
            // cbx_Saturdays
            // 
            this.cbx_Saturdays.AutoSize = true;
            this.cbx_Saturdays.Location = new System.Drawing.Point(96, 187);
            this.cbx_Saturdays.Name = "cbx_Saturdays";
            this.cbx_Saturdays.Size = new System.Drawing.Size(73, 17);
            this.cbx_Saturdays.TabIndex = 10;
            this.cbx_Saturdays.Text = "Saturdays";
            this.cbx_Saturdays.UseVisualStyleBackColor = true;
            // 
            // cbx_Weekdays
            // 
            this.cbx_Weekdays.AutoSize = true;
            this.cbx_Weekdays.Checked = true;
            this.cbx_Weekdays.CheckState = System.Windows.Forms.CheckState.Checked;
            this.cbx_Weekdays.Location = new System.Drawing.Point(14, 187);
            this.cbx_Weekdays.Name = "cbx_Weekdays";
            this.cbx_Weekdays.Size = new System.Drawing.Size(77, 17);
            this.cbx_Weekdays.TabIndex = 9;
            this.cbx_Weekdays.Text = "Weekdays";
            this.cbx_Weekdays.UseVisualStyleBackColor = true;
            // 
            // lbl_StartDate
            // 
            this.lbl_StartDate.AutoSize = true;
            this.lbl_StartDate.Location = new System.Drawing.Point(27, 85);
            this.lbl_StartDate.Name = "lbl_StartDate";
            this.lbl_StartDate.Size = new System.Drawing.Size(58, 13);
            this.lbl_StartDate.TabIndex = 7;
            this.lbl_StartDate.Text = "Start Date:";
            // 
            // dtp_StartDate
            // 
            this.dtp_StartDate.Format = System.Windows.Forms.DateTimePickerFormat.Short;
            this.dtp_StartDate.Location = new System.Drawing.Point(96, 79);
            this.dtp_StartDate.MinDate = new System.DateTime(2015, 4, 20, 11, 15, 34, 812);
            this.dtp_StartDate.Name = "dtp_StartDate";
            this.dtp_StartDate.Size = new System.Drawing.Size(99, 20);
            this.dtp_StartDate.TabIndex = 2;
            // 
            // lbx_PossibleAppointments
            // 
            this.lbx_PossibleAppointments.FormattingEnabled = true;
            this.lbx_PossibleAppointments.Location = new System.Drawing.Point(9, 239);
            this.lbx_PossibleAppointments.Name = "lbx_PossibleAppointments";
            this.lbx_PossibleAppointments.Size = new System.Drawing.Size(186, 82);
            this.lbx_PossibleAppointments.TabIndex = 2;
            // 
            // lbl_HoursNeeded
            // 
            this.lbl_HoursNeeded.AutoSize = true;
            this.lbl_HoursNeeded.Location = new System.Drawing.Point(11, 159);
            this.lbl_HoursNeeded.Name = "lbl_HoursNeeded";
            this.lbl_HoursNeeded.Size = new System.Drawing.Size(79, 13);
            this.lbl_HoursNeeded.TabIndex = 6;
            this.lbl_HoursNeeded.Text = "Hours Needed:";
            // 
            // nym_HoursNeeded
            // 
            this.nym_HoursNeeded.Location = new System.Drawing.Point(96, 157);
            this.nym_HoursNeeded.Maximum = new decimal(new int[] {
            8,
            0,
            0,
            0});
            this.nym_HoursNeeded.Minimum = new decimal(new int[] {
            1,
            0,
            0,
            0});
            this.nym_HoursNeeded.Name = "nym_HoursNeeded";
            this.nym_HoursNeeded.Size = new System.Drawing.Size(99, 20);
            this.nym_HoursNeeded.TabIndex = 2;
            this.nym_HoursNeeded.Value = new decimal(new int[] {
            1,
            0,
            0,
            0});
            // 
            // lbl_NoLaterThan
            // 
            this.lbl_NoLaterThan.AutoSize = true;
            this.lbl_NoLaterThan.Location = new System.Drawing.Point(6, 137);
            this.lbl_NoLaterThan.Name = "lbl_NoLaterThan";
            this.lbl_NoLaterThan.Size = new System.Drawing.Size(79, 13);
            this.lbl_NoLaterThan.TabIndex = 5;
            this.lbl_NoLaterThan.Text = "No Later Than:";
            // 
            // dtp_NoLaterThan
            // 
            this.dtp_NoLaterThan.Format = System.Windows.Forms.DateTimePickerFormat.Time;
            this.dtp_NoLaterThan.Location = new System.Drawing.Point(96, 131);
            this.dtp_NoLaterThan.Name = "dtp_NoLaterThan";
            this.dtp_NoLaterThan.ShowUpDown = true;
            this.dtp_NoLaterThan.Size = new System.Drawing.Size(99, 20);
            this.dtp_NoLaterThan.TabIndex = 4;
            this.dtp_NoLaterThan.Value = new System.DateTime(2015, 4, 20, 15, 0, 0, 0);
            // 
            // lbl_NoEarlierThan
            // 
            this.lbl_NoEarlierThan.AutoSize = true;
            this.lbl_NoEarlierThan.Location = new System.Drawing.Point(6, 111);
            this.lbl_NoEarlierThan.Name = "lbl_NoEarlierThan";
            this.lbl_NoEarlierThan.Size = new System.Drawing.Size(84, 13);
            this.lbl_NoEarlierThan.TabIndex = 3;
            this.lbl_NoEarlierThan.Text = "No Earlier Than:";
            // 
            // dtp_NoEarlierThan
            // 
            this.dtp_NoEarlierThan.Format = System.Windows.Forms.DateTimePickerFormat.Time;
            this.dtp_NoEarlierThan.Location = new System.Drawing.Point(96, 105);
            this.dtp_NoEarlierThan.Name = "dtp_NoEarlierThan";
            this.dtp_NoEarlierThan.ShowUpDown = true;
            this.dtp_NoEarlierThan.Size = new System.Drawing.Size(99, 20);
            this.dtp_NoEarlierThan.TabIndex = 2;
            this.dtp_NoEarlierThan.Value = new System.DateTime(2015, 4, 20, 7, 0, 0, 0);
            // 
            // lbl_InspectorToSchedule
            // 
            this.lbl_InspectorToSchedule.AutoSize = true;
            this.lbl_InspectorToSchedule.Location = new System.Drawing.Point(15, 22);
            this.lbl_InspectorToSchedule.Name = "lbl_InspectorToSchedule";
            this.lbl_InspectorToSchedule.Size = new System.Drawing.Size(54, 13);
            this.lbl_InspectorToSchedule.TabIndex = 8;
            this.lbl_InspectorToSchedule.Text = "Inspector:";
            // 
            // cbo_InspectorToSchedule
            // 
            this.cbo_InspectorToSchedule.FormattingEnabled = true;
            this.cbo_InspectorToSchedule.Location = new System.Drawing.Point(80, 19);
            this.cbo_InspectorToSchedule.Name = "cbo_InspectorToSchedule";
            this.cbo_InspectorToSchedule.Size = new System.Drawing.Size(159, 21);
            this.cbo_InspectorToSchedule.TabIndex = 2;
            this.cbo_InspectorToSchedule.SelectedIndexChanged += new System.EventHandler(this.SchedulingDataChanged);
            // 
            // tlp_UpcomingAndOverdue
            // 
            this.tlp_UpcomingAndOverdue.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left)));
            this.tlp_UpcomingAndOverdue.ColumnCount = 1;
            this.tlp_UpcomingAndOverdue.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 40F));
            this.tlp_UpcomingAndOverdue.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 60F));
            this.tlp_UpcomingAndOverdue.Controls.Add(this.gbx_UpcomingInspections, 0, 0);
            this.tlp_UpcomingAndOverdue.Controls.Add(this.groupBox3, 0, 1);
            this.tlp_UpcomingAndOverdue.Location = new System.Drawing.Point(7, 6);
            this.tlp_UpcomingAndOverdue.Name = "tlp_UpcomingAndOverdue";
            this.tlp_UpcomingAndOverdue.RowCount = 2;
            this.tlp_UpcomingAndOverdue.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 43.32211F));
            this.tlp_UpcomingAndOverdue.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 56.67789F));
            this.tlp_UpcomingAndOverdue.Size = new System.Drawing.Size(414, 892);
            this.tlp_UpcomingAndOverdue.TabIndex = 1;
            // 
            // gbx_UpcomingInspections
            // 
            this.gbx_UpcomingInspections.Controls.Add(this.lbl_days);
            this.gbx_UpcomingInspections.Controls.Add(this.lbl_InTheNext);
            this.gbx_UpcomingInspections.Controls.Add(this.cbo_UpcomingDays);
            this.gbx_UpcomingInspections.Controls.Add(this.lvw_UpcomingInspection);
            this.gbx_UpcomingInspections.Location = new System.Drawing.Point(3, 3);
            this.gbx_UpcomingInspections.Name = "gbx_UpcomingInspections";
            this.gbx_UpcomingInspections.Size = new System.Drawing.Size(402, 380);
            this.gbx_UpcomingInspections.TabIndex = 0;
            this.gbx_UpcomingInspections.TabStop = false;
            this.gbx_UpcomingInspections.Text = "Upcoming";
            // 
            // lbl_days
            // 
            this.lbl_days.AutoSize = true;
            this.lbl_days.Location = new System.Drawing.Point(107, 22);
            this.lbl_days.Name = "lbl_days";
            this.lbl_days.Size = new System.Drawing.Size(32, 13);
            this.lbl_days.TabIndex = 3;
            this.lbl_days.Text = "days.";
            // 
            // lbl_InTheNext
            // 
            this.lbl_InTheNext.AutoSize = true;
            this.lbl_InTheNext.Location = new System.Drawing.Point(6, 22);
            this.lbl_InTheNext.Name = "lbl_InTheNext";
            this.lbl_InTheNext.Size = new System.Drawing.Size(57, 13);
            this.lbl_InTheNext.TabIndex = 2;
            this.lbl_InTheNext.Text = "In the next";
            // 
            // cbo_UpcomingDays
            // 
            this.cbo_UpcomingDays.FormattingEnabled = true;
            this.cbo_UpcomingDays.Items.AddRange(new object[] {
            "10",
            "15",
            "30",
            "60",
            "90"});
            this.cbo_UpcomingDays.Location = new System.Drawing.Point(64, 19);
            this.cbo_UpcomingDays.Name = "cbo_UpcomingDays";
            this.cbo_UpcomingDays.Size = new System.Drawing.Size(41, 21);
            this.cbo_UpcomingDays.TabIndex = 1;
            this.cbo_UpcomingDays.Text = "30";
            this.cbo_UpcomingDays.SelectedValueChanged += new System.EventHandler(this.UpcomingDays_SelectedValueChanged);
            // 
            // lvw_UpcomingInspection
            // 
            this.lvw_UpcomingInspection.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.lvw_UpcomingInspection.Columns.AddRange(new System.Windows.Forms.ColumnHeader[] {
            this.col_Address,
            this.col_Type,
            this.col_DueDate});
            this.lvw_UpcomingInspection.Location = new System.Drawing.Point(7, 46);
            this.lvw_UpcomingInspection.Name = "lvw_UpcomingInspection";
            this.lvw_UpcomingInspection.Size = new System.Drawing.Size(389, 328);
            this.lvw_UpcomingInspection.TabIndex = 0;
            this.lvw_UpcomingInspection.UseCompatibleStateImageBehavior = false;
            this.lvw_UpcomingInspection.View = System.Windows.Forms.View.Details;
            // 
            // col_Address
            // 
            this.col_Address.Text = "Address";
            this.col_Address.Width = 180;
            // 
            // col_Type
            // 
            this.col_Type.Text = "Type";
            this.col_Type.Width = 120;
            // 
            // col_DueDate
            // 
            this.col_DueDate.Text = "Due Date";
            this.col_DueDate.Width = 80;
            // 
            // groupBox3
            // 
            this.groupBox3.Controls.Add(this.lvw_OverdueInspections);
            this.groupBox3.Location = new System.Drawing.Point(3, 389);
            this.groupBox3.Name = "groupBox3";
            this.groupBox3.Size = new System.Drawing.Size(408, 500);
            this.groupBox3.TabIndex = 1;
            this.groupBox3.TabStop = false;
            this.groupBox3.Text = "Overdue";
            // 
            // lvw_OverdueInspections
            // 
            this.lvw_OverdueInspections.Columns.AddRange(new System.Windows.Forms.ColumnHeader[] {
            this.col_Over_Address,
            this.col_OverDays,
            this.col_OverType});
            this.lvw_OverdueInspections.Location = new System.Drawing.Point(7, 19);
            this.lvw_OverdueInspections.Name = "lvw_OverdueInspections";
            this.lvw_OverdueInspections.Size = new System.Drawing.Size(395, 475);
            this.lvw_OverdueInspections.TabIndex = 1;
            this.lvw_OverdueInspections.UseCompatibleStateImageBehavior = false;
            this.lvw_OverdueInspections.View = System.Windows.Forms.View.Details;
            // 
            // col_Over_Address
            // 
            this.col_Over_Address.Text = "Address";
            this.col_Over_Address.Width = 177;
            // 
            // col_OverDays
            // 
            this.col_OverDays.Text = "Days Past";
            this.col_OverDays.Width = 79;
            // 
            // col_OverType
            // 
            this.col_OverType.Text = "Type";
            this.col_OverType.Width = 128;
            // 
            // tab_Calendar
            // 
            this.tab_Calendar.Location = new System.Drawing.Point(4, 22);
            this.tab_Calendar.Name = "tab_Calendar";
            this.tab_Calendar.Size = new System.Drawing.Size(894, 904);
            this.tab_Calendar.TabIndex = 2;
            this.tab_Calendar.Text = "Calendar / Scheduling";
            this.tab_Calendar.UseVisualStyleBackColor = true;
            // 
            // cmu_Contact
            // 
            this.cmu_Contact.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.cmi_AddContact,
            this.cmi_RemoveContact});
            this.cmu_Contact.Name = "cmu_Contact";
            this.cmu_Contact.Size = new System.Drawing.Size(163, 48);
            // 
            // cmi_AddContact
            // 
            this.cmi_AddContact.Name = "cmi_AddContact";
            this.cmi_AddContact.Size = new System.Drawing.Size(162, 22);
            this.cmi_AddContact.Text = "Add Contact";
            this.cmi_AddContact.Click += new System.EventHandler(this.AddContact);
            // 
            // cmi_RemoveContact
            // 
            this.cmi_RemoveContact.Name = "cmi_RemoveContact";
            this.cmi_RemoveContact.Size = new System.Drawing.Size(162, 22);
            this.cmi_RemoveContact.Text = "Remove Contact";
            this.cmi_RemoveContact.Click += new System.EventHandler(this.RemoveContact);
            // 
            // statusstrip_MainForm
            // 
            this.statusstrip_MainForm.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.status_Connection});
            this.statusstrip_MainForm.Location = new System.Drawing.Point(0, 1009);
            this.statusstrip_MainForm.Name = "statusstrip_MainForm";
            this.statusstrip_MainForm.Size = new System.Drawing.Size(1664, 22);
            this.statusstrip_MainForm.TabIndex = 9;
            this.statusstrip_MainForm.Text = "statusStrip1";
            // 
            // status_Connection
            // 
            this.status_Connection.Name = "status_Connection";
            this.status_Connection.Size = new System.Drawing.Size(205, 17);
            this.status_Connection.Text = "Attempting to Establish Connection...";
            // 
            // Main_Form
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1664, 1031);
            this.Controls.Add(this.statusstrip_MainForm);
            this.Controls.Add(this.tab_MainTabControl);
            this.Controls.Add(this.mnuMainMenuStrip);
            this.Controls.Add(this.gbx_ResultFilters);
            this.MainMenuStrip = this.mnuMainMenuStrip;
            this.MaximizeBox = false;
            this.MinimizeBox = false;
            this.Name = "Main_Form";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "TII Inspection Database";
            this.Load += new System.EventHandler(this.Main_Form_Load);
            this.mnuMainMenuStrip.ResumeLayout(false);
            this.mnuMainMenuStrip.PerformLayout();
            this.gbx_InspectionHistory.ResumeLayout(false);
            this.gbx_Building.ResumeLayout(false);
            this.gbx_Building.PerformLayout();
            this.gbx_Company.ResumeLayout(false);
            this.gbx_Company.PerformLayout();
            this.tab_BuildingCompanySelector.ResumeLayout(false);
            this.tab_ByCompany.ResumeLayout(false);
            this.tab_ByCompany.PerformLayout();
            this.tab_ByBuilding.ResumeLayout(false);
            this.tab_ByBuilding.PerformLayout();
            this.gbx_ResultFilters.ResumeLayout(false);
            this.gbx_ResultFilters.PerformLayout();
            this.tab_MainTabControl.ResumeLayout(false);
            this.tab_DatabaseBrowser.ResumeLayout(false);
            this.gbx_ButtonContainer.ResumeLayout(false);
            this.gbx_Contacts.ResumeLayout(false);
            this.gbx_Contacts.PerformLayout();
            this.gbx_ContactInfo.ResumeLayout(false);
            this.gbx_ContactInfo.PerformLayout();
            this.tab_UpcomingAndOverdue.ResumeLayout(false);
            this.groupBox1.ResumeLayout(false);
            this.groupBox1.PerformLayout();
            this.gbx_CurrentSchedule.ResumeLayout(false);
            this.gbx_NextAvailable.ResumeLayout(false);
            this.gbx_NextAvailable.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.nym_HoursNeeded)).EndInit();
            this.tlp_UpcomingAndOverdue.ResumeLayout(false);
            this.gbx_UpcomingInspections.ResumeLayout(false);
            this.gbx_UpcomingInspections.PerformLayout();
            this.groupBox3.ResumeLayout(false);
            this.cmu_Contact.ResumeLayout(false);
            this.statusstrip_MainForm.ResumeLayout(false);
            this.statusstrip_MainForm.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.TabControl tab_BuildingCompanySelector;
        private System.Windows.Forms.TabPage tab_ByCompany;
        private System.Windows.Forms.ListBox lbx_CompanyList;
        private System.Windows.Forms.TextBox txt_FilterCompany;
        private System.Windows.Forms.TabPage tab_ByBuilding;
        private System.Windows.Forms.TextBox txt_FilterAddress;
        private System.Windows.Forms.GroupBox gbx_ResultFilters;
        private System.Windows.Forms.CheckBox cbx_ShowInactive;
        private System.Windows.Forms.CheckBox cbx_ShowDC;
        private System.Windows.Forms.CheckBox cbx_ShowMD;
        private System.Windows.Forms.ListBox lbx_BuildingList;
        private System.Windows.Forms.ToolStripMenuItem testMethodToolStripMenuItem;
        private System.Windows.Forms.GroupBox gbx_Company;
        private System.Windows.Forms.TextBox txt_CompanyName;
        private System.Windows.Forms.Label lbl_OtherBuildings;
        private System.Windows.Forms.Label lbl_CompanyName;
        private System.Windows.Forms.ListBox lbx_OtherCompanyBuildings;
        private System.Windows.Forms.Label lbl_CompanyAddress;
        private System.Windows.Forms.TextBox txt_CompanyCity;
        private System.Windows.Forms.TextBox txt_CompanyZip;
        private System.Windows.Forms.TextBox txt_CompanyState;
        private System.Windows.Forms.TextBox txt_CompanyStreet;
        private System.Windows.Forms.GroupBox gbx_Building;
        private System.Windows.Forms.ListView lvw_RelatedDocuments;
        private System.Windows.Forms.ColumnHeader col_Title;
        private System.Windows.Forms.ColumnHeader col_Desc;
        private System.Windows.Forms.Button btn_AddBldgDocument;
        private System.Windows.Forms.ListBox lbx_ElevatorList;
        private System.Windows.Forms.Button btn_ViewMap;
        private System.Windows.Forms.Label lbl_Contractor;
        private System.Windows.Forms.Label lbl_Anniversary;
        private System.Windows.Forms.TextBox txt_HourlyFee;
        private System.Windows.Forms.Label lbl_HourlyFee;
        private System.Windows.Forms.TextBox txt_FirmFee;
        private System.Windows.Forms.Label lbl_FirmFee;
        private System.Windows.Forms.Label lbl_BuildingCounty;
        private System.Windows.Forms.Label lbl_RelatedDocs;
        private System.Windows.Forms.TextBox txt_BuildingName;
        private System.Windows.Forms.Label lbl_BuildingName;
        private System.Windows.Forms.CheckBox cbx_BuildingActive;
        private System.Windows.Forms.Label lbl_BuildingAddress;
        private System.Windows.Forms.TextBox txt_BuildingZip;
        private System.Windows.Forms.TextBox txt_BuildingAddress;
        private System.Windows.Forms.TextBox txt_BuildingState;
        private System.Windows.Forms.TextBox txt_BuildingCity;
        private System.Windows.Forms.ComboBox cbo_BuildingCounty;
        private System.Windows.Forms.ComboBox cbo_BuildingAnniversary;
        private System.Windows.Forms.GroupBox gbx_InspectionHistory;
        private System.Windows.Forms.Button btn_EnterNewInspection;
        private System.Windows.Forms.ListView lvw_InspectionList;
        private System.Windows.Forms.ColumnHeader col_Date;
        private System.Windows.Forms.ColumnHeader col_InspectionType;
        private System.Windows.Forms.ColumnHeader col_Status;
        private System.Windows.Forms.ColumnHeader col_Inspector;
        private System.Windows.Forms.ColumnHeader col_Report;
        private System.Windows.Forms.TabControl tab_MainTabControl;
        private System.Windows.Forms.TabPage tab_DatabaseBrowser;
        private System.Windows.Forms.TabPage tab_UpcomingAndOverdue;
        private System.Windows.Forms.GroupBox gbx_Contacts;
        private System.Windows.Forms.Label lbl_BuildingContacts;
        private System.Windows.Forms.ListBox lbx_BuildingContacts;
        private System.Windows.Forms.Label lbl_CompanyContacts;
        private System.Windows.Forms.ListBox lbx_CompanyContacts;
        private System.Windows.Forms.GroupBox gbx_ContactInfo;
        private System.Windows.Forms.TextBox txt_Fax;
        private System.Windows.Forms.TextBox txt_CellPhone;
        private System.Windows.Forms.TextBox txt_OfficePhone;
        private System.Windows.Forms.TextBox txt_Email;
        private System.Windows.Forms.Label lbl_ContactEmail;
        private System.Windows.Forms.Label lbl_ContactFax;
        private System.Windows.Forms.Label lbl_ContactCellPhone;
        private System.Windows.Forms.Label lbl_ContactOfficePhone;
        private System.Windows.Forms.Label lbl_ContactName;
        private System.Windows.Forms.TextBox txt_ContactName;
        private System.Windows.Forms.TableLayoutPanel tlp_UpcomingAndOverdue;
        private System.Windows.Forms.GroupBox gbx_UpcomingInspections;
        private System.Windows.Forms.GroupBox groupBox3;
        private System.Windows.Forms.Button btn_EditCompany;
        private System.Windows.Forms.GroupBox gbx_ButtonContainer;
        private System.Windows.Forms.Button btn_AddNewCompany;
        private System.Windows.Forms.Button btn_EditBuilding;
        private System.Windows.Forms.Button btn_EditContact;
        private System.Windows.Forms.Button btn_NewBuilding;
        private System.Windows.Forms.ContextMenuStrip cmu_Contact;
        private System.Windows.Forms.ToolStripMenuItem cmi_AddContact;
        private System.Windows.Forms.ToolStripMenuItem cmi_RemoveContact;
        private System.Windows.Forms.Button btn_NewElevator;
        private System.Windows.Forms.ComboBox cbo_Contractor;
        private System.Windows.Forms.ListView lvw_UpcomingInspection;
        private System.Windows.Forms.ColumnHeader col_Address;
        private System.Windows.Forms.ColumnHeader col_Type;
        private System.Windows.Forms.ListView lvw_OverdueInspections;
        private System.Windows.Forms.ColumnHeader col_Over_Address;
        private System.Windows.Forms.ColumnHeader col_OverType;
        private System.Windows.Forms.ColumnHeader col_OverDays;
        private System.Windows.Forms.CheckBox cbx_Heats;
        private System.Windows.Forms.CheckBox cbx_EmPwr;
        private System.Windows.Forms.CheckBox cbx_FES;
        private System.Windows.Forms.Label lbl_days;
        private System.Windows.Forms.Label lbl_InTheNext;
        private System.Windows.Forms.ComboBox cbo_UpcomingDays;
        private System.Windows.Forms.ColumnHeader col_DueDate;
        private System.Windows.Forms.TabPage tab_Calendar;
        private System.Windows.Forms.GroupBox groupBox1;
        private System.Windows.Forms.GroupBox gbx_CurrentSchedule;
        private System.Windows.Forms.ListBox lbx_CurrentSchedule;
        private System.Windows.Forms.MonthCalendar cal_CalendarDisplay;
        private System.Windows.Forms.GroupBox gbx_NextAvailable;
        private System.Windows.Forms.CheckBox cbx_Sundays;
        private System.Windows.Forms.CheckBox cbx_Saturdays;
        private System.Windows.Forms.CheckBox cbx_Weekdays;
        private System.Windows.Forms.Label lbl_InspectorToSchedule;
        private System.Windows.Forms.ComboBox cbo_InspectorToSchedule;
        private System.Windows.Forms.Label lbl_StartDate;
        private System.Windows.Forms.DateTimePicker dtp_StartDate;
        private System.Windows.Forms.ListBox lbx_PossibleAppointments;
        private System.Windows.Forms.Label lbl_HoursNeeded;
        private System.Windows.Forms.NumericUpDown nym_HoursNeeded;
        private System.Windows.Forms.Label lbl_NoLaterThan;
        private System.Windows.Forms.DateTimePicker dtp_NoLaterThan;
        private System.Windows.Forms.Label lbl_NoEarlierThan;
        private System.Windows.Forms.DateTimePicker dtp_NoEarlierThan;
        private System.Windows.Forms.StatusStrip statusstrip_MainForm;
        private System.Windows.Forms.ToolStripStatusLabel status_Connection;
    }
}